### ISSUE TITLE
Wallet not remembered from session to session

### ISSUE THREAD

**Issue by desakota** [NemProject/NanoWallet#100]
I am using NanoWallet in Firefox.  Every time I exit and restart Firefox, and relaunch NanoWallet, I need to 'Import Wallet' again.  The previously opened wallet disappears from the list of wallets in local storage, from session to session.  This is inconvenient and not at all user-friendly.  Can this be fixed so wallets are remembered, please?
Thanks.

**Comment by QuantumMechanics** [comment]
Hi,

Please check your browser settings. Make sure you keep history or do not use private mode. 

Works perfectly here on latest FF.

**Comment by tongoongo** [comment]
HI.
Same on my FF (latest), everything working properly.
All wallets are in memory of NanoWallet even after system restart.
