### ISSUE TITLE
Xem Nano Wallet Exchange, Etc to Xem.. not working?

### ISSUE THREAD

**Issue by nickpk8** [NemProject/NanoWallet#101]
Dear,

I bought myself 1855 Xem for 52.95 Etc today in the Nem nano wallet exchange, however.. still not receiving them after 4 hours? did their went anything wrong?
Or do i need to complain somewhere else to solve it?

thanks.. 
Nick

**Comment by remy777** [comment]
did you receive your nem ?
i sent eth directly to the link and did not receive the converted NEM as well . 
Need support

**Comment by stefanbx** [comment]
Any of you find a sollution for this issue since i bought also some xem and did not receive them.

**Comment by QuantumMechanics** [comment]
Hi, 

It may have some delay I guess, otherwise you need to contact Changelly
