### ISSUE TITLE
Nano Wallet Error Messages

### ISSUE THREAD

**Issue by attilol** [NemProject/NanoWallet#105]
Good Day

I saw the following errors while using Nano Wallet

![wallet error 2](https://cloud.githubusercontent.com/assets/28824150/26275365/16a62d40-3d5f-11e7-9b30-04705702afc3.jpg)
![wallet error](https://cloud.githubusercontent.com/assets/28824150/26275366/1dbff070-3d5f-11e7-8f10-f63bdb2f3440.jpg)

**Comment by jabo38** [comment]
Hi.  Thank you.  Can you tell us how to reproduce the errors?

**Comment by attilol** [comment]
Im sorry i can't tell you how to reproduce this.. i know these are the worst errors...

However i can say i didnt do anything while these errors appeared, also im not feeling that something doesnt work like it should.

**Comment by QuantumMechanics** [comment]
Hi,

First error is because market providers api was probably down at this moment.

Second error is nothing, just something returned by the NIS error channel sometimes. It affects nothing and I am aware of it :)
