### ISSUE TITLE
Sending mosaic

### ISSUE THREAD

**Issue by RobertoSnap** [NemProject/NanoWallet#106]
First time trying to send mosaic I was a little confused how to add another mosaic then XEM because the currency select box was placed on top of the "Mosaic transfer" checkbox. And I didn't read upwards. 

Maybe consider placing it below? 

![image](https://cloud.githubusercontent.com/assets/4772930/26276425/c8214768-3d77-11e7-8289-6854f39f5ae9.png)

Also, if there is no original intention in always adding XEM mosaic (?), maybe consider not adding XEM mosaic as default.

**Comment by QuantumMechanics** [comment]
Hi,

> Maybe consider placing it below? 

Yeah even me got confused by that (not my design ^^). Will fix

> Also, if there is no original intention in always adding XEM mosaic (?), maybe consider not adding XEM mosaic as default.

Will consider it, could be confusing indeed

**Comment by QuantumMechanics** [comment]
Fixed in 2.0
