### ISSUE TITLE
multisig fees bad calculated

### ISSUE THREAD

**Issue by aleixmorgadas** [NemProject/NanoWallet#107]
**Scenario: A multisig account with 2 co-signatories**
Given a multisig account (2/2), 
When it has send successfully send a transaction
And the transaction is signed by two co-signatories
Then the fee is 1+2*6 = 13.

Right now, it assumes the next calculation 1+6.

**Comment by QuantumMechanics** [comment]
Hi,

Indeed transaction details show wrong multisig fee, will fix.

Thanks

**Comment by QuantumMechanics** [comment]
Seems good now https://github.com/NemProject/NanoWallet/commit/61620695ae5e9143fc839d09f4b213dfc6b8b25f
