### ISSUE TITLE
Cannot buy XEM with EU/USD?

### ISSUE THREAD

**Issue by sjorsbeans** [NemProject/NanoWallet#108]
I'm new to XEM and would like to get involved with this amazing project. Althought i'm trying to get for a coulpe of euro's XEM. But whenever i put in let's say 20EU it says i will get 0 XEM for it and the option to proceed is not there, what are my options?

**Comment by epix** [comment]
Tried in vain too, also using LTC I keep getting the error msg:
"This address is not valid." a few secs after klick on Exchange.

**Comment by QuantumMechanics** [comment]
Hi,

@sjorsbeans 

Just checked and indeed EUR seems to have a problem. We do no have control on that, basically changelly gives us a piece of code to put on our page so need to contact them.

@epix 

Weird, what is the address ?

**Comment by epix** [comment]
> Weird, what is the address ? Check you are not using testnet (address starts with T)

Well looks like it: TAFUT.....

What do to? THX  :-)

**Comment by QuantumMechanics** [comment]
Create a Mainnet wallet and make sure you have backed up the .wlt file + password and the private key before buying.

**Comment by QuantumMechanics** [comment]
EUR seems back now.
