### ISSUE TITLE
my wallet doesn't show the received amount !!

### ISSUE THREAD

**Issue by annemsujan** [NemProject/NanoWallet#109]
Under the dashboard page, I don't see the previously received amount. What should I do ?

**Comment by QuantumMechanics** [comment]
Hi,

Make sure you are connected to a node and check that the transaction you are expecting has been sent to your account

**Comment by QuantumMechanics** [comment]
Is it solved ?

**Comment by gimer** [comment]
This is NOT the kind of problem that should be reported here and even if it was, you have provided NO DETAILS whatsoever.
Please go to forum.nem.io for help and do not open tickets here.
