### ISSUE TITLE
only password protection is not safe enough

### ISSUE THREAD

**Issue by michael8908** [NemProject/NanoWallet#112]
maybe adding 2FA into ncc-wallet and nano-wallet is a good idea.

**Comment by hazelvvood** [comment]
I agree!!!!!!!!

**Comment by gimer** [comment]
You obviously can't have SMS-based 2FA.
Google Authenticator (or any other authenticator ):
a) won't work - as you need developer key INSIDE the application
b) won't increase security in any way, as you need to link device with an app, so app (nano), would have to store token

There's someone working on 2FC though:
https://medium.com/@aleixmorgadas/nem-authenticator-2fc-ab607513c62d
