### ISSUE TITLE
XEM received from faucet is not being transferred to NEM Wallet?

### ISSUE THREAD

**Issue by khh1** [NemProject/NanoWallet#113]
Hi, 

I received free xem(nem) from the faucet but noticed that it has not been synced to my Nano Wallet account. How can I get it to show in my account that I have .08 xem at the moment?

**Comment by QuantumMechanics** [comment]
Hi,

There is no syncing in Nano, if your are connected to a node and faucet sent the transaction to your address it should immediately appear in your wallet.

You should contact the faucet owner to know if the transaction has been sent out.
