### ISSUE TITLE
Cannot see account info or Coins when logging into nano wallet

### ISSUE THREAD

**Issue by brixx22** [NemProject/NanoWallet#114]
Not sure what is happening but I logged into my nanowallet and I see none of my coins or account info transfers etc under dashboard.

Id appreciate your help

Thanks

**Comment by hazelvvood** [comment]
It's doing the same thing to me?  First time it took to minutes to pull up dashboard as if it was an empty wallet. The second time it took like 5 minutes and I was freaking out!!!!!!    I''m scared to close my NEM wallet.  Wondering if I should empty it into an exchange until resolved????

**Comment by arbooz** [comment]
doing same to me. looks all as if gone. how can we get help from admin. such issues will have an effect on confidence and will translate to price. Very strange and unexpected at all from a team like this

**Comment by brixx22** [comment]
Figured it out... Either you can wait for it to connect to the node or you can click on the red circle next to node and pick a different one from the drop down list and it should work :)

**Comment by arbooz** [comment]
worked. Resolved.thanks

**Comment by rawells14** [comment]
Looks like the main-net server is down currently. There are plenty of backups you can choose from, from the drop down list of nodes.
