### ISSUE TITLE
Payment has not  been received :(

### ISSUE THREAD

**Issue by nicosnako** [NemProject/NanoWallet#115]
Hello, I sent 2062 XEM from my NANO Wallet on 22 may and it has not been received by Changelly:
Changelly indicate "a waiting for payment"

**Comment by QuantumMechanics** [comment]
Hi,

Please contact changelly and show them the transaction you made to their address.

**Comment by nicosnako** [comment]
Thank you 
i contacted them but no response at this time...

**Comment by QuantumMechanics** [comment]
Try to insist if they take too long to reply. I guess their support gets tons of messages.
