### ISSUE TITLE
Sent nem to poloniex and it never arrived

### ISSUE THREAD

**Issue by hazelvvood** [NemProject/NanoWallet#118]
Just did this, this morning and its on nem explorer. Does anybody have any ideas of how to get my nem back?   I made a ticket at poloniex but they havent responded to a ticket i sent them on april 20.   what a joke?   I need help please

**Comment by GodTanu** [comment]
It should be said to Poloniex!
This is a place of development. Wallet has no problem.

**Comment by hazelvvood** [comment]
I know it is not a problem of the nano wallet.   I was just wondering if there's anyway nem could help since it does show on nem explorer?   Just asking?   Would be greatly appreciated if there is anything Nem could do to assist me?

**Comment by QuantumMechanics** [comment]
>  I made a ticket at poloniex but they havent responded to a ticket i sent them on april 20.

Only thing you can do is to insist if they don't reply. They probably receive a lots of tickets every day.
