### ISSUE TITLE
My account with my nem coins are gone??

### ISSUE THREAD

**Issue by Kevvv10** [NemProject/NanoWallet#120]
I had a seccond account where i stored my nem coins, when i clicked on primary i can switch to my other account. Now this is not possible so i cannot see my coins can somebody tell me what happend?

**Comment by evias** [comment]
* Did you backup your .wlt file after creating the *second* account ?
* Did you backup the private key of each of those accounts ? **important**

As it is explained in the nanowallet when adding new accounts, they are derived from the your private key + password: 
![image](https://cloud.githubusercontent.com/assets/141805/26551294/1670edea-4482-11e7-8076-2d28a0da25ee.png)

Please always make sure to backup your .wlt file when adding new accounts.. If you did not and recover your Primary account with private key *but with another password*, the created derived accounts will be different.

**Comment by QuantumMechanics** [comment]
Hi,

Adding an account only update the wallet in local storage because javascript do not allow us to update the file in your computer directly. 

If you have the wallet file and the password, just login and create the second account again, it will be the same.

**Comment by gimer** [comment]
Please go to forum.nem.io for help and do not open tickets here.
