### ISSUE TITLE
Where are my XEM?

### ISSUE THREAD

**Issue by wheregonemymoney** [NemProject/NanoWallet#121]
Hello
I have exchanged my btc with your system inside of my wallet (Changelly Instant Exchange
Use the Changelly widget to buy XEM at the best rates!). 
I have sent them to address that you gave me and still don't see them in my wallet.
When will they come? I don't see anything.
The address is right and I can prove it

**Comment by QuantumMechanics** [comment]
Hi,

We can't do anything, widget is provided by Changelly. 

Contact them and tell them you did not received your XEM at your address

**Comment by wheregonemymoney** [comment]
thnx

**Comment by gimer** [comment]
Please go to forum.nem.io for help and do not open tickets here.
