### ISSUE TITLE
NEM is gone

### ISSUE THREAD

**Issue by kamuflage** [NemProject/NanoWallet#123]
Where did my NEM go? I know it was in my NanoWallet last night, and now it's gone. Is this a technical problem or something?

**Comment by QuantumMechanics** [comment]
Hi,

If you are logged in the right wallet they should be there.

**Comment by kamuflage** [comment]
I found the problem, the node was red so i picked another one.
Kind regards

Op 29-mei-2017 23:54 schreef "QuantumMechanics" <notifications@github.com>:
