### ISSUE TITLE
My Nem Is Gone?!?

### ISSUE THREAD

**Issue by Gbonikz** [NemProject/NanoWallet#124]
I opened the Nem Wallet Yesterday. Everything was fine and I logged out fine. I saved the recovery passphrase and my Nem is still missing. It shows on the Nem Blockchain explorer to be there. Still at my address. Whats going on? How do I recover my Nem ?

**Comment by atomholc** [comment]
Are you using the browser based one? I recently ran into an issue and was freaking out a bit since I couldn't get any of my NEM to load. 

I was able to use the iPhone app with my key + wallet name and it all loaded.

**Comment by gimer** [comment]
Please go to forum.nem.io for help and do not open tickets here.
