### ISSUE TITLE
No Record Of Funds Arriving

### ISSUE THREAD

**Issue by ElloEff** [NemProject/NanoWallet#125]
I deposited −0.00435551 BTC to the bitcoin address specified when trying to purchase NEM, and now there is no record of me ever having made that purchase although it was confirmed 1269 times according to blockchain!
https://btc.blockr.io/tx/info/e92d0d1e12e095eceb187da850c04116a6d751658d0612e968223558cf1da1b3

What is going on and how do I get my funds back?

**Comment by gimer** [comment]
This  is NOT nem wallet related, so please do not abuse ticket system.
For general help go to forum.nem.io.
