### ISSUE TITLE
Public Key Not Displayed When Transactions Made

### ISSUE THREAD

**Issue by jalsck** [NemProject/NanoWallet#128]
Hi, I'm using Nano Wallet 1.3.4 and have made several transactions including purchasing some XEM. The Public Key isn't displayed on the Accounts page, instead the message "You need to make a transaction to get a public key" is displayed. Thanks.
![nano_wallet_no_public_key](https://cloud.githubusercontent.com/assets/7773533/26629642/9a20a124-4646-11e7-9a51-e5e9d6e7b7cc.PNG)

**Comment by evias** [comment]
you need to SEND a transaction, not receive.

**Comment by gimer** [comment]
as commented by @evias
