### ISSUE TITLE
Importing wallet upgrades but doesn't download

### ISSUE THREAD

**Issue by PaulBendall** [NemProject/NanoWallet#13]
Nano Wallet BETA 1.2.12 
Browser : Microsoft Edge build 40.15048.0.0
OS : Windows 10 Insider Fast Ring - Creators branch build 15048

1. Successfully exported wallet from NCC client in Lightwallet format, imported into Nano wallet.
2. Nano wallet upgrade successful
3. No prompt after upgrade to download as suggested in Upgrade warning text
4. Selecting download under account doesn't do anything 

Attached - screenshot recording of steps taken
[NanoWalletStepsRecorded.zip](https://github.com/NemProject/NanoWallet/files/819317/NanoWalletStepsRecorded.zip)

**Comment by QuantumMechanics** [comment]
Hi,

For safety reasons the new version will lock access to the app if using this browser as well as IE until full support is added. 

A pop-up will show a message and recommended browsers.
