### ISSUE TITLE
Delegated harvesting turns off when performing transaction and still having 10000 XEM

### ISSUE THREAD

**Issue by crazyexpert** [NemProject/NanoWallet#137]
Using  NanoWalet Version: BETA 1.3.4
1) I had around 11500 XEM
2) Got vested balance little bit more than 10000 XEM and turned on delegated harvesting
3) Then transferred 1000 XEM and had left in my account little bit more than 10000 XEM
Observed: vested balance was just little bit more than 9000 XEM and delegated harvesting has been turned off (looks like first is spend vested XEM).

I expected that first are spent unvested XEMs and only then is spent vested. At current XEM price for newcomers it is not practical to do delegated harvesting if it can turn off even when You still have 10 000 XEM in your account (for me turning it back might take several days). Freezing my 11000 XEM account (not using it for my practical needs) just to be able to do delegated harvesting is not practical.
If spending vested balance first is intended behavior, then at least the user should be notified that making transaction will turn off delegated harvesting. Valet should be safe - when user performs one action, it should not break other activities without notifying the user. But better do not turn off delegated harvesting if the user still has 10000 XEM.

My account: NBOHE6-2PDBPJ-OYCURL-24ZBKJ-36VIGA-EML7AN-BGMW

**Comment by gimer** [comment]
no spending, spends unvested

**Comment by crazyexpert** [comment]
Did You checked or just closed the bug? Because this bug costs me XEM and a lot of time!!! Not mentioning my time in reproducing the bug and reporting. You say, that it spends unvested (in my understanding that is how it should work), but it does not work that way! 
Full description You can see in my first comment. This time I will try visual. Delegated harvesting turned on:
![1delegatedturnedon](https://user-images.githubusercontent.com/1577754/26960965-ea788ad0-4ce3-11e7-8ed1-d9d3a9cd7e31.png)
Transferring unvested balance:
![2transferunvestedbalance](https://user-images.githubusercontent.com/1577754/26960964-ea76ae86-4ce3-11e7-965c-54e7c737561d.png)
Delegated harvesting turns off and vested balance is reduced although I still have in my account more than 10 000 XEM:
![3bugturnsoffharvesting](https://user-images.githubusercontent.com/1577754/26960966-ea78c798-4ce3-11e7-9845-aa38d8207211.png)

In current nanowallet version, if You do not have a lot of XEM the nanowalet is usable only for one thing: harvesting or XEM sending transactions. You can't do both!

**Comment by QuantumMechanics** [comment]
It is normal behaviour of the network. If your **vested** coins goes below 10'000, your account will stop harvesting.

> Because this bug costs me XEM and a lot of time!!!

Not sure what costs you lot of XEM because activating the remote via importance transfer transaction is a one process. No need to redo it. And starting / stopping delegated harvesting is free.

**Comment by crazyexpert** [comment]
Yes, it is normal behavior of the network to turn off delegated harvesting if vested coins goes below 10 000, but the question still is: "Why vested balance went below 10 000 if in my account coins did not went below 10 000?"
It is not obvious which coins are spent first (vested or unvested)! "gimmer" commented "no spending, spends unvested". So, if it is intended that first is spent unvested coints, then why my vested coins went below 10 000?

My testing strategy to transfer coins was not very smart, but that is my problem, next time will fix it.

Can You clarify what I can do with my wallet when it is harvesting and what I should not do? I want to do harvesting and use the walled for what it is intended (for spending).

Thanks for reply!
