### ISSUE TITLE
unable to send XEM from nanowallet

### ISSUE THREAD

**Issue by sudhanshu1234** [NemProject/NanoWallet#139]
I was able to receive XEM to my Nanowallet. But when I tried to do the send I see SEND as DISABLED. 
I cannot send XEM.

Can you please help

**Comment by QuantumMechanics** [comment]
Hi, 

Button shouldn't be disabled if you have set a recipient and your password

**Comment by sudhanshu1234** [comment]
I have set receipient address. I am transfering to one of the exchanges.
Also password is right.
I do not know what is the issue.

**Comment by sudhanshu1234** [comment]
Can anybody help please?

**Comment by QuantumMechanics** [comment]
If recipient, amount and password are correct I don't see what could lock the button.

Did you tried in a different browser to see ?

**Comment by salon888** [comment]
Have the same prob, can enter my account but cant send my coins.
I can receive coins but cant send

**Comment by sudhanshu1234** [comment]
Yes. Changing browser does not help. I am using Chrome. Salon88 please let
me know if you figure out anything. I have not yet found any solution.
It is quite wierd that I can receive XEM but not send.

**Comment by salon888** [comment]
yep, i installed the ios app on my phone scanned the qr code and sending on the phone app is no problem!

**Comment by sudhanshu1234** [comment]
Ok. cool. I will try with Android :)
Thanks

**Comment by saura007** [comment]
Hello Sudhanshu and salon888, I'm having the same kind of problem, Please help me.

**Comment by cryptoBeliever** [comment]
Since this issue is very old and there was no similar one I'm closing. However, if you @saura007 or @sudhanshu1234 have still this issue, please raise a new one (and link this issue) and give more details on what values are you putting into the form (a screenshot would be good too). Please use the latest version (2.6.2).
