### ISSUE TITLE
About XEM forced remittance when transmitting only mosaic

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#143]
There is a problem with the money transfer menu of NanoWallet.
When checking mosaic transmission, remittance of XEM is fixed to 1 (GrayOut).
In fact this XEM will not be remitted.
The meaning of GrayOut in NanoWallet so far means that it can not be changed, this does not mean that this item is no longer necessary.

![2017-06-08 4 15 19](https://user-images.githubusercontent.com/1645189/26975183-b18923a8-4d59-11e7-8204-0e661a7a82cc.png)

I tried attaching multiple Mosaic.
I also attached 'NEM:XEM', but it does not reflect this.

![2017-06-09 20 15 33](https://user-images.githubusercontent.com/1645189/26975458-d17fea92-4d5a-11e7-9472-4d17f9ac46f8.png)

This means that if a general person sees it, 1 XEM will be fixed and remitted.

I propose the following.
· Set the display to 0 or '--'.
· Make the form reflecting the mosaic attachment of 'NEM: XEM'.

Along with this problem, NEM Authenticater has confirmed that it will be displayed as 1 XEM when remitting only mosaic.
I will report this to you separately.

thanks
BBP ADR: @mizunashi

**Comment by mizunashi** [comment]
Append.

XEM is not remitted on a balance basis, but it looks like 1 XEM is remitted when viewed on the dashboard.

![2017-06-21 5 51 57](https://user-images.githubusercontent.com/1645189/27355507-384c341c-5646-11e7-94b5-73bec8dc3f87.png)

And it looks like Nembex also sent XEM.
![2017-06-21 5 53 45](https://user-images.githubusercontent.com/1645189/27355543-5c43b340-5646-11e7-81c4-6b1193f9130c.png)

**Comment by QuantumMechanics** [comment]
Fixed in 2.0
