### ISSUE TITLE
Blanco opening screen after log in

### ISSUE THREAD

**Issue by Microove** [NemProject/NanoWallet#144]
When opening Nano Wallet by signing in, it turns to a blanco page,
you can't navigate and see your funds.
This was on Firefox.

Now you need to switch nodes, but it would be a good thing to
get a pop up telling to change nodes.

**Comment by QuantumMechanics** [comment]
Hi, 

I have added a section about that into the help here: https://forum.nem.io/t/nano-wallet-beta-1-3-12-500-xem-bug-bounty/2791

Next version will have auto-reconnect to different nodes

**Comment by Microove** [comment]
Great, hope I could help a bit with this information. All the best
