### ISSUE TITLE
ALL MY XEM IS GONE FROM YOUR FUCKING NANO WALLET!!!

### ISSUE THREAD

**Issue by HIHIHIMEMEME** [NemProject/NanoWallet#146]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jabo38** [comment]
you need to describe you problem or list a way to contact you.  you can contact me on Telegram @jabo38

**Comment by HIHIHIMEMEME** [comment]
I opened my wallet and all my XEM is gone.. My wallet is blank... What is going on and where is my XEM???

**Comment by jabo38** [comment]
please change the node, and refresh.
