### ISSUE TITLE
Rendering in IE11

### ISSUE THREAD

**Issue by PaulBendall** [NemProject/NanoWallet#15]
Using Nano wallet in IE11 results in poor rendering in a number of pages, see below. Maybe on the splash screen advise the use of Edge (assuming issue #13 is fixed), Firefox, Chrome over IE11 as even Microsoft are trying to kill it off

![image](https://cloud.githubusercontent.com/assets/22103900/23632225/eaff20f6-02b8-11e7-95cd-e9002f5e7fc1.png)

**Comment by QuantumMechanics** [comment]
https://github.com/NemProject/NanoWallet/issues/13
