### ISSUE TITLE
Nem Wallet...hi, I logged into my NEM wallet today and all of my transaction info is gone...I cant get into anything other than Dashboard and Languages and Log out. I was supposed to start harvesting. Thanks. I am using Google Chrome.

### ISSUE THREAD

**Issue by Melissa108** [NemProject/NanoWallet#150]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jabo38** [comment]
change your server and/or refresh

**Comment by Melissa108** [comment]
I tried to log in on firefox but it is not letting me. I went here: http://mijin.io/nanowallet/start.html#!/login/
How do I log in from a different server?

**Comment by bretondamien** [comment]
Hey, just to say : I experience EXACTELY the same problem. I have firefox. Works perfectely yesterday ... and today same problem as melissa108

**Comment by cryptoczars** [comment]
I am having the same issue on firefox. I just downloaded the wallet but can only see the dashboard. Cannot see Send, Services or Explorer tabs.

**Comment by mizunashi** [comment]
Here, Change Server means changing the NIS server referred to by NanoWallet as shown below.

![2017-06-11 1 37 26](https://user-images.githubusercontent.com/1645189/27004654-bf8a79ae-4e47-11e7-9ee8-12e9134723bc.png)


Also, if you change the server that loads the NanoWallet program (agree with the URL of the browser), you can not refer to the LocalDB you used before the change.
The same is true when using different browsers.

In this case, it is necessary to read the. Wlt file or the direct secret key directly from the backup to the NanoWallet.

**Comment by bretondamien** [comment]
THANKS WORKS !

**Comment by jabo38** [comment]
Thank you Rin!

**Comment by Melissa108** [comment]
Got it!! Thank you :)

**Comment by omerhar206** [comment]
i had the same heart attack and took 2 hours trying to figure out what the heck I was doing wrong. I dont care for stupid harvesting anymore, immediately moving funds out. I read all over this BETA that NEM team is not responsible for losing my NEM, thats BS. Why even use the wallet then
