### ISSUE TITLE
I opened my wallet and it is blank... All my XEM is gone! 

### ISSUE THREAD

**Issue by HIHIHIMEMEME** [NemProject/NanoWallet#151]
How do I reclaim my wallet... All my XEM are missing. My wallet is blank. I have my recovery key and phrase. What do I do?

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mizunashi** [comment]
Did you see the answer to Issue # 146?

I am neither a developer nor an administrator, but please do not disturb inadvertent issues.

**Comment by HIHIHIMEMEME** [comment]
If you are not a developer or admin and you dont have an answer for me then go fuck yourself.

**Comment by mizunashi** [comment]
I am not an administrator or a developer, but I am rewriting the program mainly by using this for translation.
Therefore, I say it as a member who is working here.
Please do not vandalize.
As jabo 38 says, please contact me on Telegram.
If you do not want it, please write it to https: // forum.nem.io/.
Your writing is not the content to write here, it is the content to write in the above URL.
It is very annoying and disturbing work.

**Comment by jabo38** [comment]
this is not a place to be rude to people being helpful.  I'm closing this issue.

**Comment by HIHIHIMEMEME** [comment]
That dude tells me I'm being "annoying" and somehow I'm the rude one...
Fuck you also.
