### ISSUE TITLE
I am new to NanoWallet. Managed to transfer NEM and back-up files but now when re-logging Node is red and I can't see the dashboard, send, services or any other options. What should I do? help pls

### ISSUE THREAD

**Issue by CryptoLeyvraz** [NemProject/NanoWallet#152]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Click on `Node` and select another.

**Comment by CryptoLeyvraz** [comment]
Got it. Thank you. 




Winner of Golden Fork award for LONDON'S BEST FOOD 2013 AND 2015, 31 Gold Stars & 4 UK Top 50 foods at Great Taste Awards. 

Glynn Christian says "La Gelatiera's Sicilian Pistachio Sorbet is sorbet but not as you know it" - click here to see why.
 
NEWS!!! La Gelatiera East Village is now OPEN. Come visit our stylish new cafe and see how we hand craft our artisan gelato on 1 West Park Walk, e20 1dh, East Village, Stratford International tube station.

www.lagelatiera.co.uk
www.facebook.com/lagelatiera
www.twitter.com/lagelatiera
