### ISSUE TITLE
Not able to see my Xem balance.. I was using chrome in windows 10  

### ISSUE THREAD

**Issue by abhiis245** [NemProject/NanoWallet#154]
![capture](https://user-images.githubusercontent.com/29358006/27013491-84fe7f22-4f02-11e7-8a0f-6fae85ad443f.PNG)
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tongokongo** [comment]
Hey, click on the red dot Node and try to change the node. It should be green and then all of your buttons will apppear!

**Comment by mizunashi** [comment]
1. Click RED Circle.
2. Select another NIS Server from Node list.

thanks
