### ISSUE TITLE
Nano Wallet Balance Missing

### ISSUE THREAD

**Issue by jamestrader9** [NemProject/NanoWallet#155]
Hello, 

I have logged into my NEM nano wallet and it says "nothing to show" in balance.
There should be 498 XEM in this wallet.
Can you tell me how to get them back?
I have my private key and wallet file etc.
There is a red circle beside the word node on the top right. Is this okay?

Thanks.

**Comment by QuantumMechanics** [comment]
Click on `Node` and select another.

**Comment by jamestrader9** [comment]
thanks.. that worked :)
