### ISSUE TITLE
I sent my XEM to Bittrex and forgot to add the message... My XEM is not showing up on BITTREX how do I get my XEM back???

### ISSUE THREAD

**Issue by HIHIHIMEMEME** [NemProject/NanoWallet#156]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Contact Bittrex and tell them you forgot the message

**Comment by HIHIHIMEMEME** [comment]
So they shouldnt have a problem getting my XEM back???

THANK YOU!

On Mon, Jun 12, 2017 at 12:51 PM, QuantumMechanics <notifications@github.com
