### ISSUE TITLE
Error fetching market information?

### ISSUE THREAD

**Issue by zephyraijunzo** [NemProject/NanoWallet#16]
Hi,

Anyone know why this error occurred (see image below) and does it affect my account in harvesting, etc? Thanks

![image](https://cloud.githubusercontent.com/assets/25127799/23883711/1e4121e0-0826-11e7-9549-53a9fcd6776a.png)

**Comment by saulgray** [comment]
This is a known issue, and will be fixed on next release

**Comment by zephyraijunzo** [comment]
Okay thank you

**Comment by QuantumMechanics** [comment]
saulgray is right, it is fixed in upcoming version.

It is just due to CoinMarketCap API and it only affect market data display.

Nothing to worry about.

**Comment by zephyraijunzo** [comment]
Fantastic and thank you
