### ISSUE TITLE
NanoWallet problem.

### ISSUE THREAD

**Issue by Chybane** [NemProject/NanoWallet#161]
Any ideas why my dashboard of nanoWallet looks like this? There are no options, no visible XEM etc. 

![image](https://user-images.githubusercontent.com/29466975/27200196-2edba56a-5219-11e7-9d7b-95c84d9a314a.png)

**Comment by tongokongo** [comment]
Please look at the tutorial :)

https://youtu.be/Qi575qugdX0

**Comment by Chybane** [comment]
Thanks for so fast response! :)

**Comment by mizunashi** [comment]
@tongokongo  think that various videos are made public and it is wonderful.
Because I do not speak English, I can only make videos for Japanese. . .
