### ISSUE TITLE
Harvesting XEM

### ISSUE THREAD

**Issue by alaingb** [NemProject/NanoWallet#162]
I am a new subscriber in NEM - XEM. I have a quite a bunch of them now. 

I signed up for the Delegated Harvesting program. Paid my activation fee a week ago and nothing happens. I see no harvesting going on. 

What did I do wrong? Is there a guide somewhere I can read? 

Or can you help me figure it out. 

Thank you, 

alaingb

Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mizunashi** [comment]
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. 

Questions about how to use it will be helpful if you mention it on the Technical Support page.
https://forum.nem.io/c/tech-support

thanks

**Comment by mizunashi** [comment]
Thank you for your cooperation!
