### ISSUE TITLE
Error? no menu showing in nano wallet can't do anything except login and logout 

### ISSUE THREAD

**Issue by holland001** [NemProject/NanoWallet#163]
Strange ..

I downloaded the files on https://www.nem.io/install.html

Then when opening the start.html file:

I can: 

- create account
- login
- logout

Thats it, nothing more. 

NO menu seen as in the tutorial: https://blog.nem.io/nanowallet-tutorial/

![nano](https://user-images.githubusercontent.com/29493103/27245122-144164a2-52ea-11e7-83a6-d4a9aaab3546.jpg)

I am doing something wrong?

![nano](https://user-images.githubusercontent.com/29493103/27245154-40ddc56e-52ea-11e7-85df-12d7d62504a2.jpg)

**Comment by tongokongo** [comment]
Common problem, please look at the tutorial:

https://youtu.be/Qi575qugdX0

**Comment by holland001** [comment]
omg so simple, thank you

Please ad that youtube link to this page: https://blog.nem.io/nanowallet-tutorial/

You will depresure ur support staff and reduce error posts on github

Again, thank you amazing support (fast!)

**Comment by holland001** [comment]
I had to use "hachi.nem.ninja" for the menu to show up. I think its okay like this?

**Comment by tongokongo** [comment]
Hey, yes, as long as your circle is green. Nodes may go through some maintenace so be aware of that in future. Tutorial is my private one and I am not a part of NEM team so I don't have priviliges to post it anywhere on the NEM official. But thank you for your kind words, I just like helping this great community of NEMbers. Good luck with NEM! :)

**Comment by holland001** [comment]
Thank you so much, its amazing your support. You are the ones who make it happen !! Thank you for your good luck and will visit you again !! Have a great weekend!
