### ISSUE TITLE
decimal separator 

### ISSUE THREAD

**Issue by aenima86** [NemProject/NanoWallet#166]
The NanoWallet will not sent the correct amount of xem >1 using decimal separator "."

## Expected Behavior
When i send "0.2" xem using the english version the wallet should send 0.2 xem.

## Current Behavior
The wallet sends 0 xem. If I instead uses "," as decimal separator it sends the correct amount.

## Possible Solution
Changes the decimal separator from "," to "." whan using the english version.

## Steps to Reproduce
1. send "0.2" xem using the english version and "." as decimal separator.
2. the wallet will send 0 xem

## Details
bounty address: NBSTZ5FIQHZ2LOICL3X2NAEP53OIQS6LZOUXIAR4

**Comment by QuantumMechanics** [comment]
Hi,

What version are you using ?

Just tested, both `0.2` and `0,2` are working properly

**Comment by aenima86** [comment]
Version: BETA 1.3.12

Using google chrome version 58.0.3029.110 (64-bit) on a windows 10

**Comment by mizunashi** [comment]
In my environment it will be remitted correctly.
Is there a repeatability?

**Comment by cryptoBeliever** [comment]
I'm not able to reproduce on the latest version either.
