### ISSUE TITLE
Showing Balace

### ISSUE THREAD

**Issue by Belipapa** [NemProject/NanoWallet#167]
I can´t fing my balance status in my wallet. 
After login to my wallet I see only this:
![obrazok](https://user-images.githubusercontent.com/29638919/27450000-7be46b8c-578a-11e7-9533-2c4a82007afc.png)

What is the problem?
thx

**Comment by tongokongo** [comment]
Please look at this tutorial:
https://youtu.be/Qi575qugdX0
