### ISSUE TITLE
Doesnt show "Account" in Wallet

### ISSUE THREAD

**Issue by jopjopkop** [NemProject/NanoWallet#169]
Windows 10, Chrome, current version - Laptop with 1920x1080 resolution. I thought it had to do with my default 125% font size, but even when trying it with 100% font size, same result.

## Expected Behavior
According to the Guide https://blog.nem.io/nanowallet-tutorial/ the word "account" should appear in the top right hand corner of the wallet

## Current Behavior
It is cut off and unclickable.
Screenshot: https://ibb.co/f2pAJQ

No idea how to fix this.

**Comment by mizunashi** [comment]
The selected Node is not working.
Please click on Node and select another Node (SN) from the pull down.
