### ISSUE TITLE
transaction message issue

### ISSUE THREAD

**Issue by NEMDEBUGER** [NemProject/NanoWallet#17]
i had an issue with the wallet nano version Version: BETA 1.3.0
im using windows 10 

the transaction before submitting it
https://i.imgur.com/yIYFt6v.png

when i send a transaction with a text+emoji  the emoji become unreadable 
https://i.imgur.com/EMVCxVt.png

block explorer
https://i.imgur.com/ith6hsY.png

**# emoji+latin           latin ok   emoji unreadable
emoji+other languages          all  unreadable**

my xem :NBVEVB2Y6262IFUS7JMM5ERAUZNTZMDWHJCP525E

**Comment by QuantumMechanics** [comment]
Hi,

Indeed, thanks for your report, I'll look into solving this issue very soon.

**Comment by NEMDEBUGER** [comment]
good... i gave you my nem adress for the  bounty 😀

**Comment by NEMDEBUGER** [comment]
am i elegible for a bounty or not? thx

**Comment by QuantumMechanics** [comment]
You are, sorry for delay.

**Comment by jabo38** [comment]
Bounty Paid Transaction hash: 775b4c1de7c6595a5bd72bc3f882bac79aad86e736756a17fa21d2efbf43ae92
