### ISSUE TITLE
I try to withdraw XEM and it has been 24hs waiting for the funds to arrive in my Poloniex account. They charged me the 2 XEM coins twice but have not get my money yet. Thks, Rod.

### ISSUE THREAD

**Issue by sicalorod** [NemProject/NanoWallet#171]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mizunashi** [comment]
Did you write a character string for personal identification displayed in Poloniex at the time of remittance in the message column at XEM transmission?
In that case, fill in the transaction hash and contact Poloniex support.

READ
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.

**Comment by sicalorod** [comment]
Yes, I wrote the character string from Poliniex.
