### ISSUE TITLE
[bug] "this transaction needs your signature"

### ISSUE THREAD

**Issue by tongokongo** [NemProject/NanoWallet#172]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior
Message "this transaction needs your signature" should be fully visible. The same in other languages.

## Current Behavior
Mozilla firefox - it cuts the "transaction needs your signature" descritpion. The same in other languages.

## Possible Solution
It works on hrrome, there is no description at all. 

## Steps to Reproduce

1. Create multisig transaction on firefox.
2. Go into one of signers accoun -dashboard -> unconfirmed
3.
4.

## Details
1366 x 768, resizing window doesn't help. Windows 7, with newest chrome and firefox.

![chrome_en](https://user-images.githubusercontent.com/29152385/27655314-47212394-5c45-11e7-9c21-3f77cd85217c.png)
![firefox_en](https://user-images.githubusercontent.com/29152385/27655315-4721c1c8-5c45-11e7-8706-92b0339f1ba4.png)
![firefox_pl](https://user-images.githubusercontent.com/29152385/27655316-472816c2-5c45-11e7-8604-89e8813c9e3b.png)

**Comment by mizunashi** [comment]
The signature request is probably notified from NIS via WebSocket.
The problem probably resides in WebSocket, but it is currently not improved.
Although it should be displayed, many things that are not displayed are confirmed.

Previously, we operated foundation in multi-sig environment of 6-of-12.
But at NanoWallet, everyone never succeeded in receiving.
Some people or mobile wallet can receive, but never reached the number of signatures.

The solution at that time was to set fullhode on localhost. However, it was not so real that every individual had fullnode, so @QuantumMechanics  had NanoWallet add a new module.

That is the part below.
By doing this you solve the problem in front of you.
![2017-06-29 4 14 17](https://user-images.githubusercontent.com/1645189/27655856-cad0787a-5c81-11e7-951c-f972053d2540.png)

**Comment by tongokongo** [comment]
Yup, it's not that I can't sign multiaccount transactions, but there is cut string, which doesn't look good and which I am calling bug.

**Comment by QuantumMechanics** [comment]
Hi,

Fixed it just now for upcoming version
