### ISSUE TITLE
EURO Exchange Widget not work as expected

### ISSUE THREAD

**Issue by Gahzayah** [NemProject/NanoWallet#177]
Before submitting your issue, please review the following checklist:

- [Changelly Instant Exchange with EUR not work as expected. Cant pay with Creditcar ]
- [Chrome Version 59.0.3071.115  , Wallet 1.4.0 ]

## Expected Behavior
Next Step to Payment for Creditcard. Next Step to insert Creditcard Informations.Done.

## Current Behavior
Sometimes is display the Payment sometimes not. Pay with Master/Visa Button not work.

## Possible Solution
Maybe a Browser Problem. No Idea.

## Steps to Reproduce
1. Changelly Instant Exchange
2. Buy XEM
3. 30 EUR
4. Pay with VISA / Mastercard

## Details
Bug Bounty
NC7XTQD6Q427PWX733JXPBH4J6QDBLPV2KJVMXEV

**Comment by QuantumMechanics** [comment]
Hi,

I guess they might have problems, it happens sometimes.

We don't have control on the widget
