### ISSUE TITLE
No Valid Server:Dashboard Not showing any XEM

### ISSUE THREAD

**Issue by arbooz** [NemProject/NanoWallet#178]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by arbooz** [comment]
No balance or anything seen

**Comment by mizunashi** [comment]
Is red circle displayed next to node?
If so, please click on node and specify another NIS server from the pull down menu.

**Comment by arbooz** [comment]
Yes. Tried all. each single one but not resolved

**Comment by mizunashi** [comment]
What content will be returned if I access the next address from a browser using NanoWallet?

http://sn1.minarin.moe:7890/node/info

**Comment by arbooz** [comment]
Don't know what to do. Not resolving after trying all and waiting on it. Is anybody else facing similar issue

**Comment by mizunashi** [comment]
We can not solve it unless you help us.
This problem is not a structural problem of NanoWallet, so please ask at forum.nem.io afterwards.

Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.

**Comment by laxstar1** [comment]
Same exact problem, red next to Node and no NEM or XEM  showing in my account

**Comment by laxstar1** [comment]
nevermind i just clicked on the node that displayed my IP address and everything was back to normal, Maybe the issue is using the same ip address as you did when you delt with the transactions?

**Comment by arbooz** [comment]
I added my IP address and tried to use it as a node. It didn't work. Nothing changed

**Comment by QuantumMechanics** [comment]
Hi,

If you can't connect to any of the preset nodes the problem might be from your network.
