### ISSUE TITLE
XEM never arrived in my Nanowallet

### ISSUE THREAD

**Issue by wlehr2000** [NemProject/NanoWallet#181]
Address: NBQ32F5FI3HR66SPSGQUNIB74TLZIL7VFKECOK2Q
TxId: 5f3741180a40057161d399ba013b0c8b515e89fdc786866526c8830d93286c73

XEM was sent from bittrex- never arrived

**Comment by rourke121** [comment]
In the exact same position!

I transferred NEM from bittrex to my nanowallet 24 hours ago and still nothing. Details below...PLEASE HELP!

Address: NBUOWZBSGFGGHZ2CAU4MXDXLBGPRGCZZMCFCBRX6
TRANS ID: 0xd14cCC72dF063db59386c371e00292CA529400ac

**Comment by ShenDo7** [comment]
In the same position as well.

I sent from Bittrex 24 hours ago. It says complete on their end.

Address: NCI7B3-EPF3LV-QXCIJB-XQEWZM-U47K4Y-45D6GQ-34IQ
TxId: f780bdd2f3d99731f5c0c9904ada7b7137c35fee9e31dfde0b74ed9b3ffa733e

**Comment by cryptodownunder** [comment]
Same thing has happened to me via CoinSpot. Transaction was made 8.5hrs ago

**Comment by mizunashi** [comment]
Same topic?
https://forum.nem.io/t/bittrex-issues-how-long-does-it-take-to-show-up-in-wallet/5904

**Comment by QuantumMechanics** [comment]
Hi,

Check on the exchange that you have withdrawn to the correct address and contact them. None of the hashes you gave is pointing to a transaction and one is an eth hash..

**Comment by wlehr2000** [comment]
Look again:

That's a XEM address from Nanowallet - see attached screenshot


   - Address: NBQ32F5FI3HR66SPSGQUNIB74TLZIL7VFKECOK2Q
   - TxId: 5f3741180a40057161d399ba013b0c8b515e89fdc786866526c8830d93286c73


Sincerely,

Will Lehr
Managing Partner & Co Founder
P 888-281-2630
F 877-637-2742
will@perpetualassets.com
www.perpetualassets.com

This electronic mail transmission is from Perpetual Assets, LLC and is
confidential and/or privileged. The information is intended solely for its
authorized recipient(s), individual or entity named above. If you are not
the intended recipient, be aware that any disclosure, copying,
distribution, or use of the contents of this message is prohibited. If you
have received this electronic message in error, please notify us
immediately by telephone at 888-281-2630 or by electronic mail to the
sender of this message and destroy the original transmission and
attachments.

**Comment by rourke121** [comment]
hi all,

I've finally got my NEM back! this is how to resolve this issue:

1) raise a support ticket in Bittrex
2) tell them that NEM stated this is a problem of Bittrex's servers, not NEMs and that the transaction has 'orphaned'. I presume this means gone into dead space!
3) They will then admit to this and credit your account back with the relevant NEM you wanted to withdraw.
4) DON'T USE NANOWALLET AGAIN. USE DEPOTWALLET INSTEAD TO WITHDRAW YOUR FUNDS FROM BITTREX TO. 
5) ALSO don't forgot to include an alphanumeric message when prompted by Bittrex. this can be anything you like.
6) Wait 5 mins and you should have your XEM in your DepotWallet.

Good luck!
Steve

**Comment by wlehr2000** [comment]
Thanks so much for your help mate!

Sincerely,

Will Lehr
Managing Partner & Co Founder
P 888-281-2630
F 877-637-2742
will@perpetualassets.com
www.perpetualassets.com

This electronic mail transmission is from Perpetual Assets, LLC and is
confidential and/or privileged. The information is intended solely for its
authorized recipient(s), individual or entity named above. If you are not
the intended recipient, be aware that any disclosure, copying,
distribution, or use of the contents of this message is prohibited. If you
have received this electronic message in error, please notify us
immediately by telephone at 888-281-2630 or by electronic mail to the
sender of this message and destroy the original transmission and
attachments.

**Comment by rourke121** [comment]
no worries Will - these last 2 days have been rough!

**Comment by QuantumMechanics** [comment]
> DON'T USE NANOWALLET AGAIN. USE DEPOTWALLET INSTEAD TO WITHDRAW YOUR FUNDS FROM BITTREX TO.

Nano Wallet is safe to use and works as it should. It is an exchange problem
