### ISSUE TITLE
downloded XEM nano wallet. Created an address and can't figure out how to access the public address. there is no menu bar etc

### ISSUE THREAD

**Issue by prodigydefender** [NemProject/NanoWallet#182]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

There is a menu bar.. Make sure the circle next to `Node` is green, otherwise click on it and select another one.
