### ISSUE TITLE
External links in 1.4 don't open the default browser

### ISSUE THREAD

**Issue by PaulRieger** [NemProject/NanoWallet#183]
## Expected Behavior
Clicking an external link should open a new browser window/tab in the system's default browser.

## Current Behavior
Clicking an external link opens a new native chrome app window without address bar.

## Possible Solution
https://stackoverflow.com/a/30349259/3000330

## Steps to Reproduce
1. Go to NanoWallet Dashboard
2. Click on the link in the right sidebar: Please report issues here.

**Comment by QuantumMechanics** [comment]
Hi,

All external links open into a new tab, `Please report issues here` is okay for me on Chrome and FireFox.

**Comment by PaulRieger** [comment]
Hi QM!

> All external links open into a new tab, Please report issues here is okay for me on Chrome and FireFox.

I tested the packaged Chrome app on macOS Sierra. Clicking here

![image](https://user-images.githubusercontent.com/6204141/27873705-5e098264-61ad-11e7-9d31-ac4f82afed00.png)

Results in a new in-app Chrome window opening like so:

![image](https://user-images.githubusercontent.com/6204141/27873607-02108282-61ad-11e7-8282-d7254ff88f1d.png)

The stackoverflow reply linked in the original post explains a workaround that should solve this behaviour for packaged Chrome apps.

**Comment by QuantumMechanics** [comment]
Ha the Chrome packaged apps, indeed thanks :)

**Comment by cryptoBeliever** [comment]
Works fine in 2.6.2
