### ISSUE TITLE
Funds gone

### ISSUE THREAD

**Issue by lilswmj** [NemProject/NanoWallet#185]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used
Chrome and windows 10

## Expected Behavior
Xem should be in wallet

## Current Behavior
None of my xem are in my wallet, no history of my xem appear as they have for the past month or two

## Possible Solution
unknown

## Steps to Reproduce
Logging in

## Details
Today I logged in to check my balance and make sure everything was as it should be and there were 0 xem in my wallet and no history of any being deposited.

**Comment by QuantumMechanics** [comment]
Hi,

Make sure the circle next to `Node` is green, otherwise click on it and select another one.
