### ISSUE TITLE
NO MENU BAR IN MY DASHBOARD 

### ISSUE THREAD

**Issue by Vickatai** [NemProject/NanoWallet#187]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.
![gcch classic](https://user-images.githubusercontent.com/29926388/27875763-446286e0-61ac-11e7-8407-8547d8e84654.jpeg)

**Comment by tongokongo** [comment]
Please look at the tutorial:
https://youtu.be/Qi575qugdX0

**Comment by mizunashi** [comment]
It is not a NanoWallet distributed by NEM.io.
GCCH COIN is making a project.
Please make the question to GCCH.

https://github.com/gcchcoin/NanoWallet
