### ISSUE TITLE
Didn´t receive XEM

### ISSUE THREAD

**Issue by FedorMF** [NemProject/NanoWallet#189]
Hello,
I bought 300 XEM couple days ago and sent them to my nanowalltet. At this time I still don´t have the XEM in my wallet. What went wrong? Can you help me please?
Thank you.

**Comment by QuantumMechanics** [comment]
Hi,

Nothing can go wrong with the app.

If you have sent your XEM to the right account address and you are connected to a node (`Node` circle is green), it should be there.

**Comment by newarcc** [comment]
Did FedorMF recieve the XEM?  I am having the same problem, used the Changelly app to trade 1 ETH for XEM.  Have not gotten any XEM.   What went wrong? Can you help me please?
Thank you.

**Comment by QuantumMechanics** [comment]
Same as above, please look at my reply and contact exchange if all good for you

**Comment by newarcc** [comment]
Thank you for the information.  I sent an email request to Changelly yesterday.  I am waiting for a response.  I will post here how Changelly fixes this.  I had this problem one time before.  I was using the Exodus wallet and the Shapeshift exchange app.  They were able to fix it very quickly.  I hope for the same resolute from nanoWallet and Changelly.

**Comment by newarcc** [comment]
Follow up.  I sent a second request today to the Changelly help and they recovered my Ether and returned it to my wallet.  They did it very quickly and professionally.  I will be happy to use Changelly again.

**Comment by FedorMF** [comment]
Hi,
I was offline for a few days. XEM should be there but it´s not. NODE circle
is green. See the attachment. Any advice?

**Comment by newarcc** [comment]
Thank you for your email, Changelly found and returned my ether, all good now.
Steve


newarcc@verizon.net




-----Original Message-----

**Comment by FedorMF** [comment]
Problem solved.
