### ISSUE TITLE
[Request] Introduce proper release standards

### ISSUE THREAD

**Issue by Mexxerio** [NemProject/NanoWallet#190]
Me and and a lot of other people in the community would really appreciate if you could introduce proper release standards when publishing new releases.

Meaning:
- Changelog
- Tag releases on github
- No Dropbox hosting (For hosting you could just use github or bob.nem.ninja) (a lot of people complained about that already)

**Comment by OldCole** [comment]
Agree with above, especially in terms of binary repos. For NIS if the change is security related then state security update no new features

**Comment by QuantumMechanics** [comment]
Hi,

I post a `changelog` on the forum everytime I make an update. Will move everything to the op.
I use dropbox because I can't put Apostilled files on Github.

**Comment by Mexxerio** [comment]
@QuantumMechanics What about tags and hosting it on `bob.nem.ninja`? Or another cheap self hosting service?

**Comment by QuantumMechanics** [comment]
I have no access to bob.nem.ninja but will ask for release to be put there. 

>  Or another cheap self hosting service?

Dropbox is the best service for files, I use it since years without any trouble of any kind.

I just changed the links on the forum op so you don't even go to dropbox to download the file. You click and it start downloading.

**Comment by QuantumMechanics** [comment]
Added changelog

**Comment by Mexxerio** [comment]
@QuantumMechanics So, this happened today:

![dropbox](https://user-images.githubusercontent.com/11925037/27995908-c777dd3c-64d6-11e7-8b75-0b98c27931d0.png)
![dropbox2](https://user-images.githubusercontent.com/11925037/27995907-c775c772-64d6-11e7-90fe-23d9efd5d352.jpg)

**Comment by QuantumMechanics** [comment]
Lol I never had any problems in years and now look..

Someone spammed my public links to get it banned. Thanks
