### ISSUE TITLE
File open dialog shows squares instead of the correct font

### ISSUE THREAD

**Issue by akkie** [NemProject/NanoWallet#193]
## Expected Behavior
The file open dialog should use the correct font to display the files and the folders.

## Current Behavior
![wallet-file-open-dialog](https://user-images.githubusercontent.com/307006/28084978-a67fc5d6-667a-11e7-8266-bd28dd96bf7e.png)

## Possible Solution
Maybe an issue with [NW.js](https://nwjs.io/)

## Steps to Reproduce
1. Download NanoWallet from GitHub
2. Click "Login" button in the header bar
3. Click "Import Wallet" button

## Details
```bash
$ uname -a
Linux shlomo 4.11.7-1-ARCH #1 SMP PREEMPT Sat Jun 24 09:07:09 CEST 2017 x86_64 GNU/Linux
```

```bash
$ locale -a
C
de_DE.utf8
en_US.utf8
POSIX

```

NanoWallet 1.3.4 works as expected.

Bounty address: NCZ7JL-IG2PVY-JGN7IN-HS65TB-SW66AT-4INETE-TUGJ

**Comment by dessalines** [comment]
I'm getting this issue too, in Arch linux.

**Comment by matiwinnetou** [comment]
@dessalines +1 I am getting this issue in latest Manjaro Linux as of today. Manjaro is based on Arch Linux though.

**Comment by amarekano** [comment]
Hi guys,  I'm facing the very same issue.

locale -a
C
en_GB.utf8
en_US.utf8
POSIX

uname -a
Linux SV2 4.9.34-1-MANJARO #1 SMP PREEMPT Sat Jun 24 07:06:59 UTC 2017 x86_64 GNU/Linux

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 376aea8a2856bf4dd58ee72bd05490fc7d27b57e2e0f7e7c0416fd5897a561b3
