### ISSUE TITLE
Account Tab not visible

### ISSUE THREAD

**Issue by miracom1** [NemProject/NanoWallet#195]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior

I should see "Account" so I can click on it and see the addresses, etc.  

## Current Behavior

All I can see is ": Primary" whereas I should be seeing "Account: Primary".  Account is obscurred by the Node field.  Cannot therefore access account and see its addresses.  Big problem.

## Steps to Reproduce

1.  Created Wallet
2.  Opened up, and it was working fine. 
3.  Closed wallet.  Later reopened, Account field not visible.
4.

**Comment by hakimka** [comment]
I have the same thing on Chrome.
![01](https://user-images.githubusercontent.com/3639143/28244905-346fb1d2-69c6-11e7-8d67-30cca4af7867.jpg)

**Comment by mizunashi** [comment]
I will ask two people. Does it happen every time when logging in?

**Comment by dniezby** [comment]
You're not connected to a Node.  

- Click on the word Node
- When the options window opens, select a different node until you find one that turns the node icon green.
