### ISSUE TITLE
Nano wallet Doesn't let me send XEM

### ISSUE THREAD

**Issue by saura007** [NemProject/NanoWallet#197]
Hello Sir,

I just got Nano wallet and xem in it through changelly exchange,  however when I tried to send it to another address, It won't let me send any xem, even I tried write password many times correctly, no errors nothing,  also changed the node and it's showing green but still doesn't let me send xem.

Please help me sir, Thanking you in advance.

**Comment by tongokongo** [comment]
Did you type password in (one row above send button)?

**Comment by saura007** [comment]
yes, I typed correct password

**Comment by mizunashi** [comment]
@QuantumMechanics 
 Solved. Please close it.
https://forum.nem.io/t/nano-wallet-cant-send-xem/6235/7?u=mizunashi
