### ISSUE TITLE
[Vote module] Change Date/Time on your computer

### ISSUE THREAD

**Issue by getcoinToday** [NemProject/NanoWallet#205]
1.Go To Create Pool
2. Fill Calendar DateDate of ending: 06/30/2017 at 01:00AM for example

Its 06/30/2017 at 01:01AM now. System doesn't allow me to vote.

Change Date/Time on your computer (06/30/2017 at 00:55 AM) and you can Vote

## Expected Behavior
you cant vote

## Current Behavior
you can vote

[https://forum.nem.io/t/nano-wallet-beta-1-4-0-up-to-500-xem-bug-bounty/2791/149](url)

**Comment by shierve** [comment]
the time that matters is the block of the vote, not the client. The vote is not counted.
