### ISSUE TITLE
[Vote module] wait until your Date of ending passed

### ISSUE THREAD

**Issue by getcoinToday** [NemProject/NanoWallet#206]
Bug11.

1.Create pool with Date of ending +5min from current time
2. Go to your pool, select it and wait until your Date of ending passed.

## Expected Behavior
you can't vote

## Current Behavior
You can vote

## Possible Solution
Need to add some Refresh section action at Date of ending time

[https://forum.nem.io/t/nano-wallet-beta-1-4-0-up-to-500-xem-bug-bounty/2791/150](url)

**Comment by shierve** [comment]
the vote after the doe will not be counted
