### ISSUE TITLE
[Vote module] vote several time -->no results

### ISSUE THREAD

**Issue by getcoinToday** [NemProject/NanoWallet#211]
Created **TestDouble** in TestNetwork
Voted: Yes, No, Yes, No and have 4 Unconfirmed txs.
Wait for confirmation, go to your pool and check Resutls

## Expected Behavior
Any results

## Current Behavior
yes
votes: 0
weighted score*: 0.0000e+0
percentage: 0.00
no
votes: 0
weighted score*: 0.0000e+0
percentage: 0.00

[https://forum.nem.io/t/nano-wallet-beta-1-4-0-up-to-500-xem-bug-bounty/2791/159](url)

**Comment by shierve** [comment]
if you vote for different options your votes are nullified as expected.
