### ISSUE TITLE
[Vote module] Able to see vote

### ISSUE THREAD

**Issue by getcoinToday** [NemProject/NanoWallet#213]
Create new pool with white list type.
Add your address

Login using 2nd account.
Vote --> Options tab, insert the address pool above (for ex TCZPQZOLMJRXA6VMCXGHFFNQYCDZADOOJJSS2SCS ).
Select check Box Show only polls you can vote on
Click Find

## Expected Behavior
empty, no results.

## Current Behavior
I see pool (cant vote as designed)

[https://forum.nem.io/t/nano-wallet-beta-1-4-0-up-to-500-xem-bug-bounty/2791/166](url)

**Comment by shierve** [comment]
If you explicitly search for a poll by address it will be shown, the preferences are for the poll list.
