### ISSUE TITLE
[Vote module]  I see all pools (poi+whitelist)

### ISSUE THREAD

**Issue by getcoinToday** [NemProject/NanoWallet#214]
Go to Options tab, unselect check box, insert some address/leave it empty and click Find
Click Ongoing/Ended tab.be first place to visit.

## Expected Behavior
should be some ui restrictions of data

## Current Behavior
 I see all pools (poi+whitelist)

[https://forum.nem.io/t/nano-wallet-beta-1-4-0-up-to-500-xem-bug-bounty/2791/167](url)

**Comment by shierve** [comment]
since the polls are on the blockchain there is no point in hiding polls from people. Polls you can not vote on are disabled by default.
