### ISSUE TITLE
[Vote module] Multisignature Account can't Vote

### ISSUE THREAD

**Issue by getcoinToday** [NemProject/NanoWallet#215]
Multisignature Account can't Vote, but I see the following:

Image
https://forum.nem.io/uploads/default/optimized/2X/8/8152c38dfc3355f084afca279b9a089164c9688d_1_690x446.png

[https://forum.nem.io/t/nano-wallet-beta-1-4-0-up-to-500-xem-bug-bounty/2791/168](url)

**Comment by QuantumMechanics** [comment]
Fixed in 1.4.3
