### ISSUE TITLE
Private Key in NANO Wallet Android not valid when porting to Desktop Client

### ISSUE THREAD

**Issue by dooley1001** [NemProject/NanoWallet#216]
If a user wants to move from the desktop wallet to the android or the other way round the pirvate keys should be valid. The Android wallet should be able to send MOSAIC coins

I have installed the nano wallet for android and have been using it a while. I have a good amount of fund but want to move to the desktop wallet to see my mosaics for DIMCOIN. However when i try to create a private key wallet on the desktop version i enter my nano wallet private key from my phone and it says invalid. Is there another way i can import my wallet from android to the desktop. 

The key is 100% copied from the APP into the desktop client so I know its 100% but the client wont recongnise it. As it wont recongnise the private key i have no other way to tranfer my funds than sending them from one wallet to the next. The issue lies with having DIMCOIN. This does not show in the mobile app so how can i send it to another wallet. I need to be able to send my mosaics to another wallet.

**Comment by QuantumMechanics** [comment]
Hi,

Make sure you are providing the exact private key, it must be 64 or 66 characters long. 
When the private key is correct your address will show up below the private key input field.

**Comment by QuantumMechanics** [comment]
Is it fixed ?

**Comment by dooley1001** [comment]
Nahh it wouldn't work front he app. i used the web client and it accepted it created a wallet file and then imported it to the desktop client.
