### ISSUE TITLE
NanoWallet Hosted behind SSL Doesn't Work

### ISSUE THREAD

**Issue by dniezby** [NemProject/NanoWallet#218]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used
OS - Windows 10
Browsers - Chrome, Firefox, Explorer, and Edge.

## Expected Behavior

Log into Nanowallet and send / receive as usual 

## Current Behavior

The wallet loads but cannot connect to ANY nodes.

## Possible Solution

Fix coding to allow for SSL Support on a server. 

## Steps to Reproduce

1. Upload Nanowallet to a server - run and view wallet 
2. Now, upload Nanowallet to a server that is https secured.   
3. Try to view your assets. 

## Details

Works fine unsecured with standard http but if you install an SSL Certi it loads the page but none of the data.

**Comment by QuantumMechanics** [comment]
Hi,

It is not an app problem, when using SSL you cannot get data from non SSL sources.

Solution would be to setup your own SSL nodes.

**Comment by dniezby** [comment]
How do I do that?? 

Should I install Standalone Client on my server too?

**Comment by QuantumMechanics** [comment]
You can ask for ssl nodes, I think there is a few.

> How do I do that??
> 
> Should I install Standalone Client on my server too?

I don't know but you can probably get an answer on forum.nem.io
