### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Kryptolivier** [NemProject/NanoWallet#219]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Kryptolivier** [comment]
I have installed nanoWallet on my desktop. When I log in, I would expect to see on the navigation bar <Account : Primary >. Unfortunately, this is not desplayed. I see only < : Primary> and cannot click on this. Thus it is not possible for me to access my account information

**Comment by mizunashi** [comment]
@QuantumMechanics please close.
