### ISSUE TITLE
Navigation bar Account : primary

### ISSUE THREAD

**Issue by Kryptolivier** [NemProject/NanoWallet#220]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Kryptolivier** [comment]
I have installed nanoWallet on my desktop. When I log in, I would expect to see Account : Primary on the navigation bar . Unfortunately, this is not desplayed. I see only < : Primary> and cannot click on this. Thus it is not possible for me to access my account information

**Comment by mizunashi** [comment]
Click "node" next to it, and select a different node from the pull down menu of the node.

May I delete the issue #219 ?

**Comment by Kryptolivier** [comment]
yes, thx
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 18/07/2017 - 09:29 (UTC)
An : NanoWallet@noreply.github.com
Cc : olivier.privat@bluewin.ch, author@noreply.github.com
Betreff : Re: [NemProject/NanoWallet] Navigation bar Account : primary (#220)
Click "node" next to it, and select a different node from the pull down menu of the node.
May I delete the issue #219 ?
