### ISSUE TITLE
Reloading page causes logout from wallet

### ISSUE THREAD

**Issue by ncry3q** [NemProject/NanoWallet#221]
## Expected Behavior
Reloading NanoWallet should leave current view intact like in any well behaving application (example: Gmail).

## Current Behavior
Reloading NanoWallet causes logout from the current wallet with error message: "You can't access the dashboard without a wallet"
![reload](https://user-images.githubusercontent.com/30273033/28390220-a638dcee-6cc8-11e7-9adf-a99909887914.png)

## Steps to Reproduce
1. Open NanoWallet in the browser and login to existing wallet
2. While logged-in press F5 or click reload button in the browser

## Details
NanoWallet 1.4.0 tested on
- Chromium 59.0.3071.104 on Debian 9.0
- Firefox 52.2.0 on Debian 9.0

NCRY3Q-R4I5DB-IH6UKC-D5O5K6-FM52M7-6PRKSX-B2KA

**Comment by QuantumMechanics** [comment]
Hi,

It is the expected behavior, all services holding temporary data are emptied on reset.
