### ISSUE TITLE
[Vote module] Address not sanitized before sending request to Find Poll

### ISSUE THREAD

**Issue by ncry3q** [NemProject/NanoWallet#222]
## Expected Behavior
Hyphens should be stripped from the address before sending request to Find Poll. Spinner should not stay visible.

## Current Behavior
1. Address is not sanitized (hyphens not stripped) before sending request
2. Back-end is hit with invalid request and returns 400 error: Bad Request / address must be valid
3. Spinner keeps spinning even though request already finished
![sanitize](https://user-images.githubusercontent.com/30273033/28391145-53941266-6ccc-11e7-9673-676b6dc95b13.png)

## Possible Solution
Sanitize address and strip hyphens before submitting request like it happens in "Send & Receive".

## Steps to Reproduce
1. Got to Services -> Voting/See Polls -> Options
2. Put valid address with hyphens in the "Search for a poll or a poll Index:" box
3. Click "Find Poll"

## Details
NanoWallet 1.4.0 tested on
- Chromium 59.0.3071.104 on Debian 9.0
- Firefox 52.2.0 on Debian 9.0

NCRY3Q-R4I5DB-IH6UKC-D5O5K6-FM52M7-6PRKSX-B2KA

**Comment by ncry3q** [comment]
Was that a bug?
Reported Jul 19
Fixed on Jul 26
Still no bounty

**Comment by jabo38** [comment]
Bounty paid. Tx hash: e2b051ed373f9fc9cde623690bd7fedd7c86acf53ec6f12fd5defb5e7836ca49
