### ISSUE TITLE
Attempting to send transaction with empty encrypted message locks Send

### ISSUE THREAD

**Issue by ncry3q** [NemProject/NanoWallet#223]
## Expected Behavior            
Transaction with empty message should go through regardless of "Encrypt message" state. Sending transaction with empty message body should never attempt to encrypt.                            

## Current Behavior             
Attempting to send encrypted message results in locking "Send" button on "Send & Receive" view for any further transactions, regardless of values of Amount, To, Message and state of "Encrypt message".
                                                        
![lockout](https://user-images.githubusercontent.com/30273033/28393359-cdd1c6f0-6cd5-11e7-935a-c213e780a440.png)

Users unfamiliar with this problem may be unable to send anything using NanoWallet when they check 'Encrypt message' but leave Message: empty.                  

## Possible Solution            
Do not attempt to encrypt empty message. Ignore checked state of "Encrypt message" if no message was provided.                      

## Steps to Reproduce           
1. Go to Services -> Send & Receive / Send                      
2. Put valid address in the To: field                           
3. Check "Encrypt message" leaving message body empty           
4. Put Password:                
5. Click "Send"                 
6. From now on it is impossible to send ANY further transaction without changing current view                                   
7. Try changing Amount, Message body, checking/unchecking "Encrypt message", "Mosaic transfer" etc. "Send" button stays locked, only changing view and going back to "Send & Receive" unlocks "Send" on further attempts                                        

## Details                      
Console error:                  

    main.js:31261 Error: No message to encode               
    at Object.encode (main.js:121525)                           
    at Object.prepareMessage (main.js:123368)                   
    at Transactions.prepareTransfer (main.js:119202)            
    at TransferTransactionCtrl.send (main.js:114976)            
    at fn (eval at compile (main.js:32094), <anonymous>:4:174)  
    at callback (main.js:43730) 
    at ChildScope.$eval (main.js:34897)                         
    at ChildScope.$apply (main.js:34997)                        
    at HTMLButtonElement.<anonymous> (main.js:43735)            
    at defaultHandlerWrapper (main.js:20470)                    

NanoWallet 1.4.0 tested on      
- Chromium 59.0.3071.104 on Debian 9.0                          
- Firefox 52.2.0 on Debian 9.0  

NCRY3Q-R4I5DB-IH6UKC-D5O5K6-FM52M7-6PRKSX-B2KA

**Comment by QuantumMechanics** [comment]
This is already fixed in 2.0

**Comment by ncry3q** [comment]
It seems that development of Nano Wallet is not happening in the open here. Can you point me to current (upcoming 2.0) repository for future reference?

**Comment by jabo38** [comment]
Bounty paid. Tx hash: e8e194c84f059ad87e1b6b56e77dd0a295129f5a03baf7b270a46886869b18e4
