### ISSUE TITLE
Freeze when hitting "Purge" 

### ISSUE THREAD

**Issue by aenima86** [NemProject/NanoWallet#225]
Program freezes when trying to use "Purge"

Windows 10, compiled version NanoWallet-1.4.0-win64

## Expected Behavior
The program should remove all wallets

## Current Behavior
Program freezes

## Possible Solution
NaN

## Steps to Reproduce

1. Open Nano Wallet
2. Push "purge"

## Details
NBSTZ5FIQHZ2LOICL3X2NAEP53OIQS6LZOUXIAR4

**Comment by asifssarker** [comment]
Having same issue, How to solve it?

**Comment by aenima86** [comment]
@QuantumMechanics any solutions on the table?

**Comment by janmannl** [comment]
I purged my nem testnet wallets and had no freeze.

**Comment by yaaccount** [comment]
Same issue. Windows 10, compiled version NanoWallet-1.4.13-win64.

Workaround:

(after you hit "purge" and it seems to be frozen)

1) close your eyes and imagine an invisible modal dialog asking if you really want to delete them all and if you really have all private keys stored somehere
2) if you changed your mind, hit esc
3) if you still want to purge all, hit enter

**Comment by QuantumMechanics** [comment]
Fixed in 2.0 https://github.com/NemProject/NanoWallet/commit/59110f3d09ad8987afac7ec144a96af22a141610

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 21d5213a9686ba78ff75d657ef60eb31f422fffdb89a803e5386c5f62225e5a0
