### ISSUE TITLE
Features are missing in menu bar

### ISSUE THREAD

**Issue by frankyflash** [NemProject/NanoWallet#226]
Nano Wallet Beta 1.4.0 was just installed. Opening the nano wallet, main features are missing in the menu bar. see below in screenshot:

![image](https://user-images.githubusercontent.com/30374504/28492980-dbffda52-6f0d-11e7-8c95-7826980970b7.png)

**Comment by mizunashi** [comment]
Click on the Node in which the red circle is displayed and select a different node from the pull down menu.

thanks
