### ISSUE TITLE
About password input when multiple signatures are requested

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#229]
In the same multi-sig group, the behavior when multiple signature requests arrive is strange.
I have not tested the case where signature requests of different groups are lined up.
Although there is no problem in the end, I will report it.
However, there is a possibility of inducing a mis-sign.

![sign](https://user-images.githubusercontent.com/1645189/28574069-bdbf59ce-7187-11e7-922e-712b141c3368.gif)

thanks
BBP ADR: NCVGXT-CV7YYG-CUTOWR-SEALEV-HVTDFR-J54BQY-DKTI

**Comment by QuantumMechanics** [comment]
Fixed in 2.0 https://github.com/NemProject/NanoWallet/commit/fd6c284f5c9a08f7cc4b672b0b6f32a433a8daa1
