### ISSUE TITLE
Mouseover info when "x" encrypted message not allowed to click

### ISSUE THREAD

**Issue by r3n3x** [NemProject/NanoWallet#23]
Encrypted messages need the recipient account's public key to be known to the network. Than means the receiving account of the "encr." message would need to have sent at least one Tx in the past.
It is confusing many, why they can't send an encr. message to another account - when they don't know the above info.
Add a mouseover text "The recipient's public key is not known to the NEM network yet. Make sure the recipient sent at least one transaction before you can send an encrypted message to them."
This suggestion had been discussed with Jabo on 19/MAR, too. - Rene

**Comment by QuantumMechanics** [comment]
Hi,

> It is confusing many

Yes I read that on Telegram and added a mouseover yesterday
