### ISSUE TITLE
Voting module results not loading

### ISSUE THREAD

**Issue by emperswow** [NemProject/NanoWallet#234]
Using the nanowallet 1.4.3 on windows 10

## Expected Behavior
Pressing the result tab should show a diagram with the current results of the vote.

## Current Behavior
It seems like the large votes are currently not loading when results is clicked the loading symbol shows indefinitely. 
## Possible Solution
I'm pretty sure the bug is linked to the amount of results that have to be processed. Maybe look into optimizing the code used for that part.

## Steps to Reproduce

1.In nanowallet go to services.
2.Click "See polls".
3.Click results on any poll.
4.You should see only about half of them loading any results.(Note these are the polls with relatively few voters).

## Details
If any further input from me is required just reply to this issue.

If this happens to be a confirmed bug I would like to receive the bounty at this address: 
NBEKFQ4JO2P4CJWZLLKLRYTJ7YEFRYGHXJXHF6J7

**Comment by QuantumMechanics** [comment]
Hi,

We know about this issue and are working on a fix.

With the increase of voters, the number of requests triggered the node spam protection.

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 891a970064bbc3c75b8959841150ce412a8e2c6250640696dafba9665c12b197
