### ISSUE TITLE
Poll vote (multisig account) needed cosignatory dashboard don't show pending transaction

### ISSUE THREAD

**Issue by quasarblue** [NemProject/NanoWallet#237]
## Expected Behavior
After cosignatory account of a multisig account initiates
poll transaction, transaction is waiting to be signed, and 
could be seen among transactions list in all the cosigners dasboard.

## Current Behavior
After a cosignatory initiator voted a poll.
needed cosigner to complete initiated multisig transaction
doesn't see waiting transaction on his transaction list dashboard.

## Steps to Reproduce
0. Use multisig account 2 of 3
1. enter cosignatory account (is the transaction initiator)
2. vote a poll for multisig account
3.exit cosignatory account (initiator)
4. enter cosignatory account (the needed to complete transaction)
5. dashboard do not report transaction waiting to be signed (must go to services)

## Details
bounty address:
NBBTEDR3LHFAXJQOM53BFH3VQWDMB2H5JMKXDKFH

**Comment by mizunashi** [comment]
Problems are reported on the known issue at the bottom of this page.
https://github.com/NemProject/NanoWallet

As for how to deal with, please select "Sign multisig transaction" of "Services".

![2017-07-28 20 34 31](https://user-images.githubusercontent.com/1645189/28715844-f9a167e4-73d4-11e7-92a1-12d4f43ea349.png)

**Comment by quasarblue** [comment]
Yes, using services is succesful workaround.
Thanks
