### ISSUE TITLE
[Issue memo] Multilingualization of Voting Module

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#238]
Many documents in the Voting module are hard-coded in English.
If there is room in Core, or if someone is dealing with it, it is necessary to extract the document into the language file of each country so that it can be used in multi language.

If you did that work, please do not forget to include the English version in all language files.

I think that work at Core currently has a low priority, so can I live a bit in my impression? I feel it.

**Comment by janmannl** [comment]
I commited translations for the issue you are addressing (see above this comment), it's awaiting feedback.
