### ISSUE TITLE
Data is not reflected in nano wallet

### ISSUE THREAD

**Issue by kenzuici** [NemProject/NanoWallet#239]
I accessed nanoWallet this morning, but no data is displayed on the screen. What on earth happened?
I upgraded to the latest version yesterday(beta 1.4.3).At that time the data was reflected correctly. 
Currently I can not know the number of coins I own or the harvest achievement.

**Comment by kenzuici** [comment]
And I can not press the "primary" on the screen.

**Comment by mizunashi** [comment]
It seems that we have failed to acquire the initial data at wallet startup. It is confirmed as a rare phenomenon.
Please start wallet again and try logging in.
As a precaution, we recommend you change the SuperNode you are referring to.

thanks

**Comment by QuantumMechanics** [comment]
Hi,

I confirm @mizunashi, if you are connected to a node (circle is green) and you don't see all buttons in the top navbar, refresh the page and login again.
