### ISSUE TITLE
Missing market information refresh button in Services Tab

### ISSUE THREAD

**Issue by evias** [NemProject/NanoWallet#24]
The Widget for Widget Information is displayed correctly on the right side of the modules list but the Refresh button is missing when I visit the Services page as shown in the screenshot below:
![image](https://cloud.githubusercontent.com/assets/141805/24100944/9cbadcfa-0d76-11e7-875e-216c0b47f7ed.png)

Following screenshot is the Widget with functioning refresh button on the Dashboard page:
![image](https://cloud.githubusercontent.com/assets/141805/24100964/b32eeb52-0d76-11e7-8a4c-ba0d27129ec8.png)

I am using Chrome for Ubuntu (16.04) in version: Version 57.0.2987.98 (64-bit), which should be up to date.
I checked the developer console but there don't seem to be any error happening about this.

My Payout Address in case this bug can be reproduced is: NB72EM6TTSX72O47T3GQFL345AB5WYKIDODKPPYW

Thank you and I hope to be helping, great job on the update Wallet by the way!

**Comment by QuantumMechanics** [comment]
Hi,

Refresh button not showing there because not added.  I thought only dashboard was okay but I can add it in next release.

> Thank you and I hope to be helping, great job on the update Wallet by the way!

Thanks :)
