### ISSUE TITLE
Transfer Not Reflecting from Changelly

### ISSUE THREAD

**Issue by Vivek99277** [NemProject/NanoWallet#240]
Hi All,

I tried to tranfer .0x amount of bitcoins through nano wallet and enen after 45 minutes the transaction the exchnage is not successful .interesting thing is thatthereis no history for the transaction being initiated from my wallet 
Please look into it in or confirm if this is temporary delay .
BTW ; i am new to Nano wallet but the delay is concerning

**Comment by QuantumMechanics** [comment]
Hi,

The delay is not from the wallet but from Changelly.

You need to contact them if you have issue using their widget
