### ISSUE TITLE
Explorer: displays wrong amount of mosaics after transactions

### ISSUE THREAD

**Issue by marc0olo** [NemProject/NanoWallet#242]
## Expected Behavior
When I am using NanoWallet and receive/send transactions and switch in NanoWallet to explorer I want to see my current balance of mosaics.

## Current Behavior
Amount of mosaics doesn't get refreshed and cannot be refreshed in the explorer. To see the correct balance in explorer I have to sign out and sign in.

## Possible Solution
- a refresh button
- update the state-model of the explorer mosaics when receiving/sending transactions (which is working in general)

### bug-bounty
NAAEWH-QWSAU3-5EFTMK-DU3UPT-H35WLD-G3JKLZ-3MYB

**Comment by QuantumMechanics** [comment]
Fixed in 2.0

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 1c5adefe221caa4651d5391a4ca7fc20afe4383425004be6254148fad07d4cc7
