### ISSUE TITLE
[Vote module] Infinite loop on /block/at/public OPTIONS+POST requests

### ISSUE THREAD

**Issue by ncry3q** [NemProject/NanoWallet#243]
## Expected Behavior
After clicking on poll name network requests required to construct poll view should eventually stop.

## Current Behavior
Sometimes clicking on poll name triggers infinite loop of OPTIONS and POST requests on /block/at/public resulting in spamming the node (no 503 Service Unavailable responses from NIS).

## Steps to Reproduce
Try clicking on any poll twice, then click on other polls. This happens undeterministically (possible race condition?) Please don't close this bug just because it is not trivial to reproduce.

## Details
NanoWallet 1.4.3 tested on
* Chromium 59.0.3071.104 on Debian 9.0
![loop-chromium](https://user-images.githubusercontent.com/30273033/28996008-e2dea694-79e6-11e7-9581-13834549fd3e.png)

* Firefox 52.2.0 on Debian 9.0
![loop-firefox](https://user-images.githubusercontent.com/30273033/28996010-ec470226-79e6-11e7-87c4-38df5fd32238.png)

I think it's not related to issue #234 where node spam protection triggers "503 Service Unavailable" on /account/historical/get requests for nodes that don't have HISTORICAL_ACCOUNT_DATA set in nis.optionalFeatures.

NCRY3Q-R4I5DB-IH6UKC-D5O5K6-FM52M7-6PRKSX-B2KA

**Comment by mizunashi** [comment]
API /account/historical/get has nothing to do with "HISTORICAL_ACCOUNT_DATA" specified in the NIS option.
At the time of origin, the NanoWallet corresponding to that NIS option is not officially released.

**Comment by ncry3q** [comment]
@mizunashi According to documentation it is related.

https://bob.nem.ninja/docs/#retrieving-historical-account-data

It might be unrelated to that specific issue though.

**Comment by mizunashi** [comment]
I do not understand the program around so well.
I will answer in the range to understand.
In today's update of NanoWallet, an API not on the API list is used.
Perhaps I understand that it depends on the setting of NIS HISTORICAL_DATA.

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 96ed3eb06920f6baf5e363823b2da698f0e677a95d9fd69e65874af86965a96f
