### ISSUE TITLE
Voting Module Charging NEM? :O(

### ISSUE THREAD

**Issue by deanopt** [NemProject/NanoWallet#245]
If you're asking the NEM Community to vote on some of the silly polls that are currently in the voting module, why would we be charged for each vote? Is this normal behavior? I was confused when I logged in to the Nano Wallet and had three (3) negative entries. This basically cost me almost 1 USD to vote on three fluff questions...not happy!

**Comment by QuantumMechanics** [comment]
Hi,

1 vote = 1 transaction = 0 XEM + minimum fee.

The upcoming fork will have cheaper fee.

**Comment by deanopt** [comment]
Well I was charge 1 XEM for each vote and there should be no charge for voting...that's just not acceptable.

**Comment by QuantumMechanics** [comment]
> there should be no charge for voting

It works with transactions and you have to pay minimum fee for them to get accepted by the network.

There is no other way to do vote on a blockchain....

I will ask the dev to show the fee for voting

**Comment by deanopt** [comment]
So you're saying the minimum fee ended up one (1) XEM...because I was charged one for each vote? Minimally...I should have been told I was being charged....frankly, I wouldn't have voted.

**Comment by tongokongo** [comment]
-Fee change will be at block height 1250000: https://forum.nem.io/t/nem-beta-0-6-93/6599
-'I will ask the dev to show the fee for voting", Yes, it will be changed. Sorry for trouble!
