### ISSUE TITLE
No Place to Change Password

### ISSUE THREAD

**Issue by deanopt** [NemProject/NanoWallet#246]
I have looked multiple time where I can change the password but cannot find where to do so. Can someone point me in the right direction or let me know if this feature does not exist.? Thank you!

**Comment by QuantumMechanics** [comment]
Hi,

You can take your primary private key, go to signup and create a private key wallet with it and your new password.

Keep in mind that if you have created **secondary accounts** into your **old** wallet and change password as explained above it will generate **different secondary accounts** in your **new** wallet.

**Comment by deanopt** [comment]
Why is it that one has to go to a convoluted situation in order to just change a password? It seems this should be something addressed for the general public's easy of use.

**Comment by QuantumMechanics** [comment]
It is complicated, changing the password affect the wallet too much (remote account, secondary accounts and other data) so it is to be considered as new wallet. 

The process of changing password if already logged into a wallet would be more confusing.
