### ISSUE TITLE
Missing Toolbar

### ISSUE THREAD

**Issue by sheats** [NemProject/NanoWallet#247]
Before submitting your issue, please review the following checklist:

## Expected Behavior
I should be able to open an account by following instructions on this site: https://blog.nem.io/nanowallet-tutorial/

## Current Behavior
Same thing as when I tried a few months ago, I set up a wallet, login, and I see nothing on the top nav bar:
![screen shot 2017-08-10 at 9 24 28 am](https://user-images.githubusercontent.com/243014/29172372-c5c74a64-7dad-11e7-81d5-bead0366a943.png)

## Steps to Reproduce
1.  Mac 10.12.6, Chrome Version 59.0.3071.115 (Official Build) (64-bit)
2. Follow the instructions on the nanowallet tutorial up to Login and Backup
3. Login and notice no options at top of app.

## Details
I'm guessing there's a log file somewhere I can access to figure out what's going on but I can't find the details of how to find it.

**Comment by mizunashi** [comment]
Does the same phenomenon occur even if I start up again?

If it is the same phenomenon, there may be a problem with the currently selected node.
Please click the node button near the red circle and select a different node from the pull down menu.

thanks

**Comment by sheats** [comment]
Yup, same thing if I close everything, then open and log back in.  

I tried switching to every Node on there, nothing changed.

**Comment by sheats** [comment]
Is there a log file somewhere I can access?

**Comment by QuantumMechanics** [comment]
Hi, 

There is no log file, if you cannot connect it probably means your firewall, router configuration or ISP is blocking it. I don't see any other reason

**Comment by sheats** [comment]
Yup, you are right.  Issue resolved, thank you!
