### ISSUE TITLE
XEM missing from nano wallet  

### ISSUE THREAD

**Issue by fredrica27** [NemProject/NanoWallet#249]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mizunashi** [comment]
Please fill in the question contents.
I do not understand your environment at all, so I answer only general solutions.

Does the same phenomenon occur even if I start up again?
If it is the same phenomenon, there may be a problem with the currently selected node.
Please click the node button near the red circle and select a different node from the pull down menu.

thanks

**Comment by fredrica27** [comment]
Thanks, I logged in another node and the XEM came back.
Raj

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
