### ISSUE TITLE
QR Code Issue 

### ISSUE THREAD

**Issue by Ryan-Gordon** [NemProject/NanoWallet#25]
Flow to get the error :
In account there is an option to click QR ( Android and iOS)
Clickingg button asks for wallet password.
Successful password then displays a QR Code.

If a user leaves this flow either from closing it/ Clicking outside the modal and then reopening it they see a blank area where a QR should be. No Request for a password 

Screenshots 👍 
This is the first view shown, request for password as expected
<img width="609" alt="screen shot 2017-03-20 at 20 30 57" src="https://cloud.githubusercontent.com/assets/11082710/24120650/44f6ecfc-0dad-11e7-8f07-1c47976db18b.png">

After successful password we see this as expected 👍 
(Scribbled over my QR)
<img width="614" alt="screen shot 2017-03-20 at 20 31 10" src="https://cloud.githubusercontent.com/assets/11082710/24120704/71d53a08-0dad-11e7-8b21-8552ea186ab0.png">

If we leave 

this flow and come back we only get this 👍 

<img width="654" alt="screen shot 2017-03-20 at 20 30 39" src="https://cloud.githubusercontent.com/assets/11082710/24120726/80dd86b8-0dad-11e7-8260-11221150280d.png">

**Comment by mizunashi** [comment]
**Additional Information:**
In my case, after entering the password,

-  Account QR
-  Wallet QR
-  Wallet QR (Android and iOS)

I will be able to see all these.
And I can see it without a password any number of times.

However, once I move to a different page and come back, I will need a password.

The environment is MacOS Chrome V57.

**Comment by FlashGordon95** [comment]
Adding NEM address for bounty: NBUBD6-IFUUY3-7Z7FMR-2CUYOV-PJK2CS-OPPLDJ-L32S

**Comment by QuantumMechanics** [comment]
Fixed in 2.0

**Comment by Ryan-Gordon** [comment]
Any update on bounty? :)
