### ISSUE TITLE
wrong withdrawl/ main adress

### ISSUE THREAD

**Issue by ghdtjr963** [NemProject/NanoWallet#250]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior

Nano wallet main server adrees is  ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR.

--

## Current Behavior

I mistakenly thought that address was mine. So i send my nem wrong adress. I send my ticket. But I don't return any answer.

## Possible Solution

Main adress and user adress is so same. I was so confused.
## Steps to Reproduce

1.

Complete | XEM | 9300.00000000
-- | -- | --
  | 2017-06-10 13:04:05			
Address: ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR
Txid: be65fbde0b4784783301df24a60e2e459907ff00adef0b0386709240cf144439

This is my wrong withdrawl. So i want return.
2.
3.
4.

**Comment by mizunashi** [comment]
I think that it is a remittance from Poloniex to Bittrex, but how about it?
This is the place to report bugs about NanoWallet.

For questions, please go to https://forum.nem.io.

**Comment by QuantumMechanics** [comment]
Blockchain are immutable, only way to get a refund is to contact owner of ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR and wait for them to reply.
