### ISSUE TITLE
Enforce strong password !!!

### ISSUE THREAD

**Issue by patmast3r** [NemProject/NanoWallet#251]
People do not understand brainwallets. They don't understand the neccessity of very strong passwords. Nano needs to enforce strong passwords. 
Nobody reads the warnings and even if they do it is not being made clear to them how great the danger is. 
How many more people are going to lose their XEM and then spread the word that NEM is insecure (which is obviously incorrect).

This needs to happen imho. 
Alternatively drop the functionality for brainwallets entirely.

**Comment by jabo38** [comment]
I agree. Even though there is a strong warning, it doesn't matter, people are not following.  I think maybe the min character should be 24 when making a passphrase? maybe longer?

**Comment by QuantumMechanics** [comment]
Okay, will be 24 characters minimum in next update

**Comment by mizunashi** [comment]
These two passwords are of equal intensity.

  ~UfC%Ghe&azRVv3
  estop mixing edelweiss conduct rejoin flexitime

Both are pretty strong passwords with entropy of over 90.
log2((26 + 26 + 10 + 10)^15) = approx. 92.548875

**Comment by mizunashi** [comment]
There are 40 chars or more written in the warning.
![2017-08-16 6 11 07](https://user-images.githubusercontent.com/1645189/29336811-1206b4aa-824a-11e7-82d3-32cb93bb4b01.png)

**Comment by patmast3r** [comment]
Awesome. I think this would warrant an emergency release tbh but at least it's coming. 
24 chars isn't a lot though. It's already too long to remember for most so we might as well go all out with 40 as is suggested now or even more. Once they need to use a password manager it doesn't matter how many chars.

**Comment by mizunashi** [comment]
Again, big damage was made.
Discussions are also being held at NEM :: RED.
It is better to issue a corresponding version as soon as possible.

Someone already using a short password with BrainWallet.
I think that the countermeasure here is also necessary.

**Comment by jabo38** [comment]
@QuantumMechanics please make the limit 40 characters as Pat suggests.  

Anybody making a new wallet will have to use 40 or more characters.  

Anybody with an existing brainwallet with less than 40 characters will be able to log in but will get a warning to upgrade their wallet to a new wallet with a passphrase with 40 or more characters.

**Comment by QuantumMechanics** [comment]
https://github.com/NemProject/NanoWallet/commit/7631bbabc27e9fc3a1c9210a488ffbb6a429ad02
https://github.com/NemProject/NanoWallet/commit/2ecd959f1b49d76026486966d8e680c2fbce3ee2
