### ISSUE TITLE
mosaic divisibility

### ISSUE THREAD

**Issue by pmtolk** [NemProject/NanoWallet#253]
Before submitting your issue, please review the following checklist:

- [ ] **DO** describe operating system and browser used

MAC nano wallet Beta 1.4.3 on testnet

## Expected Behavior

I created a namespace and mosaic with divisibility 2 and supply 1,000,000
I send the mosaic in the amount of 23.15 and the total shows 23.15 and 23.15 is sent and confirmed by receiving party

## Current Behavior
I send the mosaic in the amount of 23.15 and the total shows 0.23 and 0.23 is sent and confirmed by receiving party

## Possible Solution
when a user tries to send a mosaic amount with a divisibility of 2 for example 23.15
then the total amount should be 23.15 and not .23
Please fix the location of the decimal place with the divisibility

**Comment by mizunashi** [comment]
I am not good at English, so my understanding of the question may be incorrect.

In the transaction that transmits mosaic (NEM Transfer Transaction Ver. 2), the minimum unit is 1.
If this is analogous to BTC, input is done in Satoshi.

This also applies to XEM itself, In Ver.2 Transaction, entering 1000000 for ammount will result in 1XEM.

**Comment by pmtolk** [comment]
The current functionality you explained is working.
However, most people will not be able to understand or relate to this functionality imho.

Think about it analogous to dollars whole numbers and cents fractions of whole numbers in this case divisible by 2.

For example, If soda costs $0.50 then I want to be able to send $0.5 and not 50 Cents
because of the use of the decimal place to specify the unit.

The mosaic amount is ignoring the decimal place even though the mosaic is divisible by 2.

Thus sending 0.50 is 0 when it should be 0.5 and sending 50.00 is sending 0.5 when it should be 50.00

This is just my opinion on how the majority of people will understand how the decimal place is used in the divisibility portion of the mosaic and the sending portion.

**Comment by mizunashi** [comment]
@QuantumMechanics  It may be better to enter Total.

**Comment by QuantumMechanics** [comment]
Fixed. In 2.0 you can enter the real amount directly.
