### ISSUE TITLE
Nanowallet 1.4.3 beta not working on latest Chrome-Stable for Linux 

### ISSUE THREAD

**Issue by johmut65** [NemProject/NanoWallet#254]
Trying to install NEM NanoWallet on Linux
- Linux Client : Unpacked .zip but no instructions ? 
- Universal Client : Start.html launches NEM NanoWallet; Setup completed fine, but ...

Chrome does not display the horizontal navigation bar > impossible to use 
Chromium on the other hand works fine, on the same system/os

It's not the extensions, because I have the same loaded in Chromium. It's really an issue in Chrome only.

Links to screenshots:

- [Chrome version](http://i.imgur.com/3AJxp4y.png)
- [Navigation bar not showing](http://i.imgur.com/Z7gQMuQ.png)
- [Chromium version](http://i.imgur.com/cT3WpxU.png)
- [Navigation bar showing as expected](http://i.imgur.com/OQiGI6R.png)

Bug Bounty still on ? Payout address NA7RWPAG5EAV3SKX5G7UJX654ZDZ2CW2SYDE3B66

TIA,
Johan

**Comment by mizunashi** [comment]
Is the NIS server set for the node setting on the Chromium side the same as the NIS server set on the Chrome side?
If this is not the case, try setting the same NIS server as Chromium side on Chrome side.

NIS settings can be checked and changed in the node menu of NanoWallet top screen.

thanks

**Comment by johmut65** [comment]
Hi Rin, 

Node setting was indeed different. I have set Chrome the same as Chromium and now it works. My bad, me sad. No bug bounty for me :-( 

Don't know why they were different in the first place though ? 
Chromium was set to : Blockchain height 1242109; Current Node 164.132.102.85
Chrome was set to : Blockchain height 0; Current Node hokkaido.zapto.org
I had to manually add the 164.132.102.85 Node though ? Anything I should worry about ?

TIA,
Johan

**Comment by mizunashi** [comment]
I am not a NEM Core as an ordinary person, so I have nothing to do with the Bug Boundary.

The problem with this time is that the NIS server that is running is not selected when it is started for the first time.
This is considered a fine bug, but it is also true that it has already been reported by other people.

I just helped to get rid of the problem in a way that I can do now.

Thanks

**Comment by johmut65** [comment]
OK. Thanks for helping out.
KR, 
Johan
