### ISSUE TITLE
Not recieving my NEM

### ISSUE THREAD

**Issue by kthonenice** [NemProject/NanoWallet#256]
I bought some NEM over a week ago at Poloniex. I have tried to contact them three times, but they are not answering. The transaction is completed at Poloniex, but they never reached my wallet. And yes the addresses are correct.

I am aware that this is GitHub and mainly evolves around issues regarding the wallet, but Im thinking some of you might have an idea about what I can do.

Any help is appreciated.

Thank you.

**Comment by mizunashi** [comment]
Have you accessed the URL of the mail received from Poloniex at the time of withdrawal?
If still not sent, I would like to investigate the transaction of NEM.
If you do not mind, could you tell me the payee's address from Ploniex?

Thanks

**Comment by kthonenice** [comment]
Yes I did. I approved it the minute I received it.

My Poloniex NEM receive address is:

6c3f53421a45e2d2

The Poloniex transaction ID is:
12a1235570e4108bcd7c0895334656a6bba6617bbd18346c375f263e69d99a54

Thank you.

________________________________
Fra: MIZUNASHI, Rin <notifications@github.com>
Sendt: 20. august 2017 19:51:50
Til: NemProject/NanoWallet
Cc: Nick; Author
Emne: Re: [NemProject/NanoWallet] Not recieving my NEM (#256)


Have you accessed the URL of the mail received from Poloniex at the time of withdrawal?
If still not sent, I would like to investigate the transaction of NEM.
If you do not mind, could you tell me the payee's address from Ploniex?

Thanks

**Comment by mizunashi** [comment]
Explanation was inadequate. I'm sorry.
Could you tell me your NEM address?

Thank you.

**Comment by kthonenice** [comment]
Ah yes of course. My NEM address is:
NATKG5O4QSIQVOH5KMJEIEKLQ5TFKNLWG4ZDIJKQ

Thank you.

All the best,
Nick

________________________________
Fra: MIZUNASHI, Rin <notifications@github.com>
Sendt: 21. august 2017 00:16:52
Til: NemProject/NanoWallet
Cc: Nick; Author
Emne: Re: [NemProject/NanoWallet] Not recieving my NEM (#256)


Explanation was inadequate. I'm sorry.
Could you tell me your NEM address?

Thank you.

**Comment by mizunashi** [comment]
There are 3 payments to your NEM address from Poloniex.
This means on the block chain that funds have arrived at your address.

If you are using NanoWallet:
Is a green circle displayed in the top left node menu part of the TOP screen?
If red circle is displayed, select another server from the node menu.

If you use MobileWallet:
There is a possibility that the currently set server is stopped.
Change the server from the server menu.

Thanks

**Comment by kthonenice** [comment]
The circle is green in my Nanowallet. The thing is, I made a transaction on the 10th of August, of 253 NEM. The last transaction that went through was on the 3rd of August of 273 NEM. I am still missing my 253 NEM from Poloniex. Since the circle is green (and has always been) What can I do?

The three transactions you can see, what are they?

Thank you!

________________________________
Fra: MIZUNASHI, Rin <notifications@github.com>
Sendt: 21. august 2017 14:00:35
Til: NemProject/NanoWallet
Cc: Nick; Author
Emne: Re: [NemProject/NanoWallet] Not recieving my NEM (#256)


There are 3 payments to your NEM address from Poloniex.
This means on the block chain that funds have arrived at your address.

If you are using NanoWallet:
Is a green circle displayed in the top left node menu part of the TOP screen?
If red circle is displayed, select another server from the node menu.

If you use MobileWallet:
There is a possibility that the currently set server is stopped.
Change the server from the server menu.

Thanks

**Comment by QuantumMechanics** [comment]
Hi,

> The Poloniex transaction ID is: 12a1235570e4108bcd7c0895334656a6bba6617bbd18346c375f263e69d99a54

You should contact Poloniex because this hash is not on NEM chain http://chain.nem.ninja/#/transfer/12a1235570e4108bcd7c0895334656a6bba6617bbd18346c375f263e69d99a54

 > The three transactions you can see, what are they?

http://chain.nem.ninja/#/search/NATKG5O4QSIQVOH5KMJEIEKLQ5TFKNLWG4ZDIJKQ

**Comment by kthonenice** [comment]
Hello! Thank you for clearing that up.

The transactions I see are the following:
- 273 NEM on August 3rd
- 329 NEM on July 15th
- 1166 NEM on July 14th
- 447 NEM on July 13th

So basically all the rest. I did contact Poloniex, but they are of course not answering. Fucking retards.
I appreciate the help though, but I am not expecting Poloniex to reply at all. Guess the 253 NEM are just gone. Could you tell me the best exchange to buy NEM in the future? I will not be doing business with Poloniex again.

________________________________
Fra: QuantumMechanics <notifications@github.com>
Sendt: 23. august 2017 17:43:48
Til: NemProject/NanoWallet
Cc: Nick; Author
Emne: Re: [NemProject/NanoWallet] Not recieving my NEM (#256)


Hi,

The Poloniex transaction ID is: 12a1235570e4108bcd7c0895334656a6bba6617bbd18346c375f263e69d99a54

You should contact Poloniex because this hash is not on NEM chain http://chain.nem.ninja/#/transfer/12a1235570e4108bcd7c0895334656a6bba6617bbd18346c375f263e69d99a54

The three transactions you can see, what are they?

http://chain.nem.ninja/#/search/NATKG5O4QSIQVOH5KMJEIEKLQ5TFKNLWG4ZDIJKQ
