### ISSUE TITLE
Please correct the link destination of the language file. （V.1.4.10)

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#261]
ALERT_BRAIN_WALLET_UPGRADE:  ...........  https://forum.nem.io/t/nano-wallet-beta-1-4-3-up-to-500-xem-bug-bounty  .........

      ↓

ALERT_BRAIN_WALLET_UPGRADE:  ...........  https://forum.nem.io/t/2791  .......

BBP: @mizunashi

**Comment by archiii92** [comment]
https://github.com/NemProject/NanoWallet/pull/157
Can you give me a answer? ) And i will fix link also of course.

**Comment by mizunashi** [comment]
I am an ordinary person.
Could you ask Core/Dev?

**Comment by archiii92** [comment]
I don't know any of them unfortunately

**Comment by QuantumMechanics** [comment]
https://github.com/NemProject/NanoWallet/commit/0a7961e40708efbca0f560e79627f41592237793
