### ISSUE TITLE
Fee display incorrect for Mosaic

### ISSUE THREAD

**Issue by dali1986** [NemProject/NanoWallet#263]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mizunashi** [comment]
Are you using version 1.4.10 of NanoWallet?

**Comment by dali1986** [comment]
Hi, I did not realise this had been saved - I was originally using the latest version on the website (was 1.4.3 for a few hours after the fork) but then dug deeper and saw the link the the new release. 

Then checked it out and all seemed to be fine - made a transfer of 1 xem and a message and was charged 1.1 which was displayed correctly.

The problem now seems to be with Mosaics and I think the title is probably still appropriate as the correct fee appears to be charged but the display seems incorrect.

To recreate.

Send a transaction with zero Xem and some mosaic.  ( charge = 0.1 XEM)
The dashboard will state -2 mosaic symbol   <- [But you have only sent 1 mosaic and no XEM]
The details show: -

Amount 1.000000 XEM  <- [This should be zero]
Fee 0.100000 XEM
Mosaics attached: 2 
 Name: Namespace:Mosaic
 Quantity: 500.000000
 Name: nem:xem
 Quantity: 0.000000

Regards,

Rob
NATYNB-AL7ZYH-T6OWGY-2MKDPQ-LPVQKG-FN5PLS-XGTK

**Comment by mizunashi** [comment]
same issue? https://github.com/NemProject/NanoWallet/issues/143

**Comment by dali1986** [comment]
Yes - seems to be the same
