### ISSUE TITLE
If you register 25 or more mosaics, it will not be displayed in Explorer (Report on the rush from users)

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#266]
Register namespace.
Multiple mosaics registered under the namespace.
Currently about 50 items have been registered.

However, **NanoWallet Explorer does not display more than 25**.
In nembex, all can be displayed.

http://chain.nem.ninja/#/browse/myheart

Namespace: myheart
Mosaic: about 50

Bug Boundary Program:
Reporter NEM Address: NDW4ET2EF5LTK3FKBVNYNBIXME6D5FA3F7NFA6LD

**Comment by janmannl** [comment]
Which page doesn't show all mosaics? Tried explorer/home and explorer/namespaces-and-mosaics and both show either paging or all items

**Comment by mizunashi** [comment]
explorer/namespaces-and-mosaics
serch Namespace "myhert"
Only 25 mosaics are displayed.

**Comment by QuantumMechanics** [comment]
It seems that the API and websockets only return 25 mosaics owned... 

It is a big problem, some mosaics cannot be sent because it's not showing in the wallet.

Asked @BloodyRookie for a solution

**Comment by BloodyRookie** [comment]
will look into it
