### ISSUE TITLE
The description of the namespace is different from the current specification.

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#268]
![2017-08-23 1 53 14](https://user-images.githubusercontent.com/1645189/29581382-0c903d88-87b4-11e7-8ae8-7351a4748ea1.png)

In the current specification, you can get a namespace that starts with a number.
Ex: 1alice

Please update the document.

Thanks
BBP: @mizunashi

**Comment by mizunashi** [comment]
Additional notes.

For subnamespace and Mosaic, the first letter number is prohibited.
It seems that Javascript gives an error.

I think that it is better to have consistency.

**Comment by QuantumMechanics** [comment]
Thanks, allowed starting with a number

Fix: https://github.com/NemProject/NanoWallet/commit/5662616d3fce520435f5b6fef8a45ca61c6e721f
Language update: https://github.com/NemProject/NanoWallet/commit/80f83c51fb27b32d16a08c33d81e3426a9c19202
