### ISSUE TITLE
Suggestion : Add update notification

### ISSUE THREAD

**Issue by OldCole** [NemProject/NanoWallet#27]
Based on a number of threads on Telegram would it be possible to add something on the initial splash screen to identify a newer version is available. Secondly be able to download and update from the splash screen

**Comment by QuantumMechanics** [comment]
> would it be possible to add something on the initial splash screen to identify a newer version is available

Yes

> Secondly be able to download and update from the splash screen

Download ok but update is impossible

**Comment by OldCole** [comment]
I get what you are saying about download only, think this enhancement would be very beneficial

**Comment by QuantumMechanics** [comment]
Notification added in 2.0
