### ISSUE TITLE
NanoWallet to Bittrex Issue?

### ISSUE THREAD

**Issue by NobleInvestorINC** [NemProject/NanoWallet#270]
So, I sent XEM from my NanoWallet to Bittrex over an hour ago and haven't seen it yet. I went to the block explorer and noticed the transaction is being sent back and forth. Can someone explain how to resolve this issue?

**Comment by QuantumMechanics** [comment]
Hi, there is nothing to do once the transaction is sent. It should arrive at destination or expire
