### ISSUE TITLE
Forgot to put message when sending

### ISSUE THREAD

**Issue by nickfoo** [NemProject/NanoWallet#276]
Dear Support,

Sorry. It is the first time I am doing a transfer for XEM to NAV
and I overlooked inputting the message (NQBV2VSoENNTGNQQrqzPoZAMS1A5KuYeB6). Is there any way you could help me retrieve the coins? The transaction details are as follows.

 NBLQ6P-E7Z5CV-ANJNXG-OR74UQ-LOJ2YM-GJJOZ4-YFAQ 	- 200.050000 XEM 	
	Sat, 02 Sep 2017 02:49:34 GMT
Transfer transaction
From
ND6XLD-UXA2GS-KEV2EW-GTH2AU-O6QTPT-SSV5BS-6JFZ
To
NBLQ6P-E7Z5CV-ANJNXG-OR74UQ-LOJ2YM-GJJOZ4-YFAQ
Amount
200.000000 XEM
Fee
0.050000 XEM
Block
1267180
Hash
1be234a0d0ea2e0920a75aa65909f14bdfa44ed2145ec8f33390c336977ce39e

Regards,
Nicholas

**Comment by matiwinnetou** [comment]
I cannot but I see this is such a common problem for users. Is this NEM specific thing that messages are necessary or in fact exchanges make their life easier by requiring messages?

**Comment by QuantumMechanics** [comment]
Hi, 

> Is there any way you could help me retrieve the coins?

You must contact the exchange

> Is this NEM specific thing that messages are necessary or in fact exchanges make their life easier by requiring messages?

It is the exchange

I think best would be to check in the wallet if the user send to an exchange address and prevent sending if no message is set. Will do that asap
