### ISSUE TITLE
[macOS Sierra] Changelly widget doesn't work (ETH)

### ISSUE THREAD

**Issue by matronator** [NemProject/NanoWallet#278]
System: macOS Sierra
Client: Native wallet for mac (NanoWallet)

## Expected Behavior
After clicking exchange button, it should show the address where to send ETH

## Current Behavior
After clicking exchange button, it disables for a while and then enables again. Nothing changes on the page, no address etc.

## Possible Solution
Fix the changelly widget?

## Steps to Reproduce
1. Click on services
2. Click on buy XEM
3. Select currency (ETH) and amount
4. Click exchange

## Details
<img width="1143" alt="snimek obrazovky 2017-09-02 v 20 49 00" src="https://user-images.githubusercontent.com/5470780/29997953-34488b0e-9020-11e7-960a-fb31b80493ec.png">

**Comment by merc1305** [comment]
Same behaviour on web client NanoWallet-2.0.14 : 

https://monosnap.com/file/SEpH84v9Mez8rFWNm9XC1hHyhoP6qo

after tapping exchange: https://monosnap.com/file/9PkTF8C8cKloXsm4WhMWTAViDkTGIP

Unable to select XEM from the list of crypto because XEM is not presented in the list. 

@mizunashi
