### ISSUE TITLE
3rd level mosiac cannot be created

### ISSUE THREAD

**Issue by ikeonet1** [NemProject/NanoWallet#281]
## Expected Behavior
When creating a sub level mosaic, I should be able to create namespace:mosaic1:mosaic2. 
## Current Behavior
When I try to create mosaic2, I am not given the option of Parent:mosaic1 to create mosaic2 under. 

## Possible Solution
Add mosaic1 to the Parent Namespace dropdown so that mosaic1 will show and mosaic2 can be created.

Altername 

## Steps to Reproduce

1. Services > Create Namespace
2. Services > Create Mosaic 
3. Services > Create Mosaic  
    a.) Try to create mosaic2 from mosaic1

## Details
I tried to create the mosaic using mosaic1: which errored with the colon. When trying to recreate mosaic1, it overrides mosaic1 when using an existing mosaic name. The Mosaic will be replaced with the new supply value.

**Comment by mizunashi** [comment]
You must make a mosaic like this.
namespase : subnamespace : mosaic

**Comment by ikeonet1** [comment]
Thank you for the clarification. This can be closed.
