### ISSUE TITLE
Creating Mosaic with the same name overwrites existing Mosaic values

### ISSUE THREAD

**Issue by ikeonet1** [NemProject/NanoWallet#282]
Environment. 
Nanowallet version 1.4.13 on testnet

## Expected Behavior
Error when creating a Mosaic with the same name

## Current Behavior
Overwrites existing Mosaic and changes the supply to the newest value. It also charges for the recreation as a new mosaic 10 xem + .15 xem instead of just the .15 xem to modify a mosaic

## Possible Solution
Error to show that an existing mosaic with the same name exists

## Steps to Reproduce

1. Create Mosaic and fill in supply of 1000, transferrable & mutable
2. After initial creation, create Mosaic same name supply 1

## Details
Supply for the preexisting mosaic was changed from 1000 to 1.

**Comment by mizunashi** [comment]
If you do not pass Mosaic to anyone (all you have) you can overwrite it with Create.
I do not know if this is a bug, but it is reported.

**Comment by QuantumMechanics** [comment]
@mizunashi is right, you can overwrite a mosaic if you own 100% of the supply.

It is not a bug, however, I will add the information to the mosaic help
