### ISSUE TITLE
Multisig failed to add cosignatories and change min signature

### ISSUE THREAD

**Issue by renolteng** [NemProject/NanoWallet#286]
## Expected Behavior
Successfully adding one cosignatory and change the min signature needed to +1
From '2 of 3' to '3 of 4'

## Current Behavior
Getting error "FAILURE_MULTISIG_MIN_COSIGNATORIES_OUT_OF_RANGE

## Steps to Reproduce
1. Creating a 2 of 3 multisig account
2. Using 'Edit a multisignature contract' to add a cosignatory and set the 'Change Sigs Needed' to 3

![multisig_add_cosig_issue](https://user-images.githubusercontent.com/9570640/30160063-7d3247b6-93fd-11e7-8bd1-5bf38d630ddb.jpg)

**Comment by tongokongo** [comment]
https://youtu.be/VfawLVWyFho
You need to put "1" in "Change Sigs needed". As you are adding one more. If you would remove 1, you need to put "-1".

**Comment by renolteng** [comment]
OK, understood, thanks!
