### ISSUE TITLE
Creating a Mosaic with '--': Bug in Display on Nanowallet Create Mosaic Page and Explorer

### ISSUE THREAD

**Issue by evias** [NemProject/NanoWallet#287]
Hello there,

I have come into an awkward issue creating my PacNEM Mosaics on the Mainnet, following screenshots:

![Create Mosaic Page](https://user-images.githubusercontent.com/141805/30228998-66f982aa-94e0-11e7-85fd-220d6e038a3e.png)

Please note the **hearts--** value in the input field for *Mosaic Name* and the **--pacnem:hearts** value in the *Full Name* field.

This also seems to happen when I query for my Mosaic on the Explorer **but not on the Transaction List**, so here, first the transaction list where the *name is correct* :

![Transaction Mosaic Create Correct Name](https://user-images.githubusercontent.com/141805/30229105-dfd62e4e-94e0-11e7-81a8-df7f34271ecb.png)

And here the screenshot on the Explorer mentioning **the wrong Mosaic name** :

![Explorer Mosaic Title Error](https://user-images.githubusercontent.com/141805/30229163-23f291ee-94e1-11e7-8903-976a5f4d106a.png)

Please note the **--pacnem:hearts** value on the *top right* of this screen.

This issue is **non-critical** as it implies *only Display*. My Mosaics seem to be created with the correct mosaicId.

Cheers!

**Comment by mizunashi** [comment]
I also tested it. 
There is reproducibility.
![2017-09-09 5 08 28](https://user-images.githubusercontent.com/1645189/30229619-9d952f66-951d-11e7-8ffe-49435016952a.png)

![2017-09-09 5 10 01](https://user-images.githubusercontent.com/1645189/30229634-ac2ac59a-951d-11e7-9603-d076918a9e6d.png)

**Comment by QuantumMechanics** [comment]
> This issue is non-critical as it implies only Display. My Mosaics seem to be created with the correct mosaicId.

Yes only display bug, fixed in 2.0
