### ISSUE TITLE
One failure to connect to node (red circle) circle through nodes

### ISSUE THREAD

**Issue by patmast3r** [NemProject/NanoWallet#289]
## Expected Behavior
If Nano can't connect to the default node, try other nodes until one works. People are currently incredibly confused by what's going on, because all they see is a blank page. Nobody sees the red circle. 
I'd also appreciate there being a feedback for the user so that the user knows that Nano is currently trying to connect. 

## Current Behavior
Just blank page. No information Nano is currently trying to connect to the network. 
It's just bad UX really. 

## Possible Solution
Circle through nodes until a connection was successfully established

**Comment by anmar1** [comment]
how long should i wait before giving up on a node?

**Comment by QuantumMechanics** [comment]
Added an alert https://github.com/NemProject/NanoWallet/commit/4106e33fa9d42dfc5f825a5e5f2bd30ad4e3bac8

2.0 have autoreconnect
