### ISSUE TITLE
Invent a "check for updates" mechanism and alert users

### ISSUE THREAD

**Issue by r3n3x** [NemProject/NanoWallet#29]
Due to the fact that many people still today keep contacting me "what's going on, any issue with NEM?" when they can't see the market information in their outdated NanoWallets.
When we want to go more mainstream - perhaps a "Update-Check" with an alert for that would be advisable. Am happy to host an Application server to host a backend for an API call to check for updates and give a pingback with a short News message.
For now: Call for comments. Let the ideas flow.  Rene

**Comment by OldCole** [comment]
I raised a suggestion yesterday for the same, which @QuantumMechanics has now labelled as a future enhancement. Does the problem and enhancement under Issue #27 describe what you were looking for in this issue?

**Comment by r3n3x** [comment]
@OldCole  Thanks!  Yes it does. NanoWallet is becoming the best Crypto wallet out there....  Good job guys.
