### ISSUE TITLE
Show address on Dashboard

### ISSUE THREAD

**Issue by patmast3r** [NemProject/NanoWallet#290]
## Expected Behavior
The address of the account should be immediately visible to the user. Some people can't find it and there is no good reason for that. 

## Current Behavior
Address is difficult to find for some people. Most poeple expect such basic information to be available on every page or at least on the dashboard.

## Possible Solution
Display it either on the top or somewhere else on the dashboard.

**Comment by QuantumMechanics** [comment]
Done in 2.0 https://github.com/NemProject/NanoWallet/commit/49f3e0f00eade6482e33071df10d46231992ca6c
