### ISSUE TITLE
Delegated Harvesting problem.

### ISSUE THREAD

**Issue by tongokongo** [NemProject/NanoWallet#291]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Expected Behavior
Harvesting status should be uniform in the same account

## Current Behavior
Opening Manage delegated account of multisignature accounts tab in chrome browser gives me delegated harvesting status active. Opening the same tab for the same account it gives me inactive. 
![image](https://user-images.githubusercontent.com/29152385/30397295-af43e1aa-98cc-11e7-8160-d85bbd64bf5d.png)
^Mozilla Firefox, harvesting inactive
![image](https://user-images.githubusercontent.com/29152385/30397259-91d8a916-98cc-11e7-8cbd-0d1ea7de5644.png)
^chrome, harvesting active 
![image](https://user-images.githubusercontent.com/29152385/30397352-e3864ade-98cc-11e7-99a1-55678f54ad1c.png)
^Multisig account, harvesting inactive
![image](https://user-images.githubusercontent.com/29152385/30397473-54804870-98cd-11e7-9aa2-1dfdfefa6165.png)
^Second cosigner account, harvesting inactive

## Possible Solution
I don't know solution

## Steps to Reproduce

1. Start delegated harvesting in cosignatory_1 account -> harvesting active
2. Log into cosignatory_1 account on another browser -> harvesting inactive
3. Or log into cosignatory_2 account or into multisig account -> harvesting inactive
4.

## Details

![image](https://user-images.githubusercontent.com/29152385/30397615-b416bf44-98cd-11e7-8389-c7193e0920e9.png)

This may be connected, while trying to log off from the delegated harvesting (multisig) screen I am getting this error **"Unknown wallet encryption record"**.

![image](https://user-images.githubusercontent.com/29152385/30397680-f188bf4e-98cd-11e7-8715-8f62a783aa5c.png)

Then I got this information after logging off: **"Provided password is not valid."**

**Comment by mizunashi** [comment]
**About the browser.**
In this case, the delegated server information saved by the browser side saved different information.
So, the browser for remote harvesting is incorrectly recognized by the browser. Different results are displayed for this reason.

**About harvesting under multi-sig environments**
About harvesting under multi-sig environments
O accounts with funds.
Suppose O is managing the multisig with M1 and M2.

Here, O has three management methods.
Suppose that the remote account of O is valid before configuring multisig.
After that, O sets up to perform multi-sig administration with M1 and M2.
In this case, you can log in with O and control the harvesting request.

After actually creating the Multisig environment, you can activate Remote account of O and manage harvesting at M1.
However, what to note here is that the Remote account is different in this way from the case of writing above.

This also applies to activating Remote account of O in O2 and managing harvesting. To my satisfaction, the Remote account used will be a separate account from M1.

There are three activation and management methods, and you need to recognize that they use different Remote accounts.

BR has a memory saying that it is better to manage with O.

**Provided password**
I also see this well. (^_^;)
