### ISSUE TITLE
Delegated Harvesting can not be stopped

### ISSUE THREAD

**Issue by MrDil** [NemProject/NanoWallet#296]
- [ ] **DO** Windows 10, latest NanoWallet 1.4.13

## Expected Behavior
I should be able to stop the active Harvesting

## Current Behavior
Nothing happens when i try to stop the active Harvesting. When i want to click on "stop delegated harvesting", it shows me a red circle and i cant click on it

## Steps to Reproduce
1. Tried to change the node, still harvesting.
2. Tried to re-install the Wallet, still can't stop it.

Anyone? Idea?
![unbenannt-2](https://user-images.githubusercontent.com/32196056/30742760-ec47293e-9f9a-11e7-9c8e-fc9a475f5111.jpg)

**Comment by QuantumMechanics** [comment]
Hi, 

Enter you password in the input just above the node selection to unlock the button
