### ISSUE TITLE
 How to correct the embedded characters in English?

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#30]
![2017-03-22 15 09 46](https://cloud.githubusercontent.com/assets/1645189/24184779/fce5cc46-0f12-11e7-9c11-697c217f7820.png)
It is highly likely that problems will occur in languages ​​other than English.
It is necessary to set the blue line part of the image as a language file, or set it as a language file in one sentence.

**Comment by QuantumMechanics** [comment]
Thanks, I didn't noticed. It was supposed to be "Create invoice" but for some reason there is this "Receive" word...

Fixed on my local version, will be in next push
