### ISSUE TITLE
Bug screen on nano wallet 1.4.13

### ISSUE THREAD

**Issue by tylius78** [NemProject/NanoWallet#304]
Hello,
i detected a bug on nano wallet beta 1.4.13
with window 7 and google chrome after a while in one node

when you switch of node and go to ‘‘dashboard’’ then ‘’ in confirmed’’ page a part of the screen(75%) of the page is moving or shaking.
(While nothing moved ‘‘in unconfirmed’’ page)
It’s a bug screen on this page.
link of the video recorded : https://youtu.be/X6RueO0jXXc

here my wallet for some bounty
Best regards
i can remove the video after problem sovled
ND4BRL-ECS75C-2SE2IN-TSZ6F3-EJXTWA-7BADV4-2J75

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 4e4acdbca4c2bb6c62732d030cc09bcdd94ff1dbb9ab86915e994fb72c100ce0

**Comment by tylius78** [comment]
Thats great Jabo sorry i was out! (and working busy) i just read you and answer you tonight
I loved helping Nem comunity! 
Do you want i remove my video or working a word that you solve now the bug ? :dagger: 
Best regard and happy new years Jabo
Long live to Nem!
