### ISSUE TITLE
NANO Wallet Bug?

### ISSUE THREAD

**Issue by anttommo** [NemProject/NanoWallet#306]
Hi there,
I have just been using the NANO Wallet to get on board the COMSA ico.
Unfortunately, when I clicked to send the XEM to COMSA it kept telling me that the Password was incorrect even though I knew that it was correct as it was the Password that I used to Login to the Wallet in the 1st place.
Then suddenly after entering the Password and clicking for the 4th time it said that the transaction was successful and suddenly started to ping and all 4 transfers went through.
This means that I have sent 4 times the amount of XEM than I intended.
Is there any sort of logfile that I can send you etc so that you can fix this?
Cheers.

**Comment by QuantumMechanics** [comment]
Hi,

Weird, I don't know how it could have sent 4 transactions.
When you click on `send`, it lock the button to prevent double sending.
If it says `Password was incorrect` it steps out of the function and don't send.
Success transactions clean up the form and keys so it locks the send button.
There is no accumulation of transactions.

> Is there any sort of logfile that I can send you etc so that you can fix this?

No, on your dashboard is it showing 4 outgoing transactions ?

**Comment by anttommo** [comment]
Yes it is showing 4 outgoing transactions.

Anthony Thomas (Tommo)
+66 81 7626 045

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by mizunashi** [comment]
Since I will investigate, can you send me a hash of 4 transactions?
Thank you.

**Comment by anttommo** [comment]
HI there,

I am sorry but could you tell me how to do that?

Best regards.

Anthony Thomas (Tommo)
+66 81 7626 045

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by mizunashi** [comment]
This is an example of one transaction.
Please let me display 4 transactions like this with NanoWallet.
I hope you fill in the part called Hash that is displayed there.

![2017-10-12 15 57 37](https://user-images.githubusercontent.com/1645189/31483214-6704339e-af66-11e7-80cf-7385bd20a707.png)

**Comment by anttommo** [comment]
Hi there,

I hope these are what you are asking for.

a719d3681503f8ae6441f680f00f0d8b22defc7c1765bf48ac6151951d61b381

540188f42a40058bbd932a39bb9c8de1ea76afc302056336b5d35a4034d6c26a

fdf75dd3d853e30fd0ffabaea2a79b1c300697636e2b79f458596556dec227d3

205e982ddc2568b3aca0dd18c16a5339c2d74dc2c3bce5276ea9bbdf0299141f

Best regards.

Anthony Thomas (Tommo)
+66 81 7626 045

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by mizunashi** [comment]
At the following time, I was able to confirm that XEM was sent to the COMSA address with the same message.

2017-10-06 05:48:10 GMT 4745.421245xem
2017-10-06 05:49:05 GMT 4745.421245xem
2017-10-06 05:49:10 GMT 4745.421245xem
2017-10-06 05:54:09 GMT 4745.421245xem

Please tell us which server is the node setting of NanoWallet now.

I think there is a green circle at the top. Please click on the node there.
And please tell me the contents displayed in "Current node:".

**Comment by anttommo** [comment]
The Current Node displays 108.61.251.209

Anthony Thomas (Tommo)
+66 81 7626 045

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by mizunashi** [comment]
Did you change the node before 4 transactions flowed all at once?
At that time, trouble occurred in one of the nodes, san.nem.ninja, it may be transmitted in that state and it was in a state that it could not be sent.

**Comment by anttommo** [comment]
No. I did not. I would not know how to do so.

Anthony Thomas (Tommo)
+66 81 7626 045

Sent with [ProtonMail](https://protonmail.com) Secure Email.
