### ISSUE TITLE
No wallet infomration after logging in

### ISSUE THREAD

**Issue by kylexis** [NemProject/NanoWallet#308]
HI
I havelogged into my wallet with correct walled ID (drop down) and my correct password.
There is no information on the dashboard at all!   I have tried all the nodes ot see if they are on.. .
Why is there no information screen for amount of NEM, or list to go to other areas?

**Comment by Teakw00d** [comment]
I am having the exact same problem

**Comment by kylexis** [comment]
you have to wait for a node that is working.. try different nodes...

**Comment by anmar1** [comment]
tried every node, still nothing showing on dashboard.

**Comment by kylexis** [comment]
It does that to me some also.. it may be taking time to sense the nodes....
I have had to wait for a day and then check back...
Take care... ask others also for ideas

**Comment by QuantumMechanics** [comment]
Maybe the default nodes were down, if you can't connect to any, even those on https://supernodes.nem.io then you should check your firewall and/or router configuration.
