### ISSUE TITLE
[Question] The maximum password length that can be used with NanoWallet.

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#313]
NCC has 128 characters and NanoWallet has confirmed that it can use longer password.
Please tell me how many characters can actually be used.
Regarding here, if there is a difference between Brain Wallet and Simple Wallet, I would like to teach them, respectively.

The question is now on the forum.
Thank you.

**Comment by cryptoBeliever** [comment]
As far as I can see there is no limit at all for password length.
