### ISSUE TITLE
Can not select a namespace when there are many namespace search candidates

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#315]
**Before submitting your issue, please review the following checklist:**

- [✓ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ALL ] **DO** describe operating system and browser used

## Expected Behavior
After searching the root name space with exploler, the name space searched is displayed.

## Current Behavior
The explorer's namespace search displays the results that contain the specified characters.
And, if the result exceeds 10, we can not refer to eleventh in character string order.

## Possible Solution
- Incorporate forward match / backward match / complete match
- Make it possible to display all search results.

## Steps to Reproduce
Search for the root name space "hi".
1. Go to the Explorer -> Namespace & mosaics page
2. Enter "hi" in the search
3. Not displayed (can not be displayed)

# Details
"hi" Screen of namespace searched
![2017-10-29 10 22 44](https://user-images.githubusercontent.com/1645189/32139973-69b3ebf8-bc94-11e7-9d91-68105b53e455.png)

Proof of existence of "hi" namespace
![2017-10-29 10 18 52](https://user-images.githubusercontent.com/1645189/32139977-78aad0d6-bc94-11e7-9c07-16abb6b24c99.png)

**Comment by cryptoBeliever** [comment]
As I can see there was added paging:

![image](https://user-images.githubusercontent.com/17684281/194402877-6c01e2c6-5f72-4bff-9ffb-a6db01433a70.png)
