### ISSUE TITLE
Quantity is not reflected in explorer when changing supply amount of mosaic.

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#320]
Before submitting your issue, please review the following checklist:

- [✓] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ALL] **DO** describe operating system and browser used

## Expected Behavior
If the total issue volume is changed after issuing Mosaic, the issue volume at the current time is displayed.

## Current Behavior
If the total issue volume is changed after Mosaic is issued, the initial issue volume is displayed.

## Possible Solution
Displays the issue quantity of mosaic at the time of accessing the browser.

## Steps to Reproduce
1. Issue mosaic with variable supply quantity.
2. Increase or reduce supply of mosaic.
3. Confirm change at NEMbex.
4. Search Namespace and Mosaic at NanoWallet.
5. Issuing amount is initial value.

# Details
I think that the initial issue volume of the mosaic that can change the issue volume is worthless as data. The current total issue volume is more important.

![2017-11-09 14 54 34](https://user-images.githubusercontent.com/1645189/32591103-23206b28-c561-11e7-9985-18b3c0662504.png)

**Comment by QuantumMechanics** [comment]
Hi,

BR gave me an API call to fix that a while ago, will be fixed in 2.0 explorer :+1:

**Comment by QuantumMechanics** [comment]
Fixed in 2.0
