### ISSUE TITLE
Missing transactions in History.

### ISSUE THREAD

**Issue by Espo02** [NemProject/NanoWallet#322]
## Expected Behavior
The Dashboar of NANOwallet should show all Transactions of the loggedIN account. From the first to the last.

## Current Behavior
The Transaction history shows only 5 Sites of Transactions. Somewehere in August 2016 it ends (backwards). http://chain.nem.ninja shows more Transactions. I wanted to read a Message of Febraury 2016 which wasn't show in this client and so I cant decrypt it. 

## Possible Solution
Don't limit the Transaction window.

## Steps to Reproduce
1. Open an Old account with a lot Transactions 
2. Try to read the first one ob page 8.

**Comment by simonm99** [comment]
The transactions are paginated - if you look to the right of the "Confirmed" and "Unconfirmed" tab you'll see you are on page 1 of n. You can move further back/forward in your transaction history with the < > links. At least in my version of Nanowallet I can see all transactions made on the account.

**Comment by Espo02** [comment]
Hi simonm99

I klicked the pages from 1st to the 5th page. But there schould be more pages. This account has more the few transactions which are shown on the first 5 pages. My Version is the universal Nanowallet 1.4.13

My Account:
http://chain.nem.ninja/#/account/NDEFC3H4VAIUFQ5GFTIK3IJR4DGKF7PEQKRWLPZ5/932689
![lpz5_1 4 13_missing](https://user-images.githubusercontent.com/17567386/32894135-302d263c-cadc-11e7-8d61-e1807654aa6c.PNG)

**Comment by QuantumMechanics** [comment]
Hi,

NEM API only return 25 transactions per request, I can get everything but it would make too many requests at initialization. I will add a new page will full history in 2.0

**Comment by QuantumMechanics** [comment]
https://github.com/NemProject/NanoWallet/commit/5f1a8cf9e44a6084d48c1883c3afaba1d038c728

**Comment by cryptoBeliever** [comment]
It's possible to change pageSize to max 100 and return max 100 elements in one API-call. It will allow to show last 100 transactions/harvested blocks (not only 25).
