### ISSUE TITLE
missing transaction

### ISSUE THREAD

**Issue by phuonglamto7193** [NemProject/NanoWallet#323]
i sent out my XEM to hitbtc on last couple days. Unfortunately, their deposit address has been under maintenece and It seems pending for a while. Can anyone help me with the issue?
Transfer transaction
From NDB3UK-WDN33T-WRBQVQ-WCUUF5-VKLNEP-ILSGWP-DMSF
To NBX3QK-ZJV2UP-O3NJ5U-LTFW2V-5EE4N2-I5N2RE-X7PO
Amount8 083.000000 XEM
Fee 0.050000 XEM
Block 1373220
Hash 21862ea6aac3f05c9a006a795d76b3f9c6967055368b9acc0bca5a7ad385cc68

**Comment by mizunashi** [comment]
This is the place to report a problem of NanoWallet.
Please contact the next forum.
https://forum.nem.io/t/6550/
Thank you.

**Comment by QuantumMechanics** [comment]
Hi, you must contact the exchange, explain the situation and provide them the transaction hash.
