### ISSUE TITLE
NanoWallet allows ZERO quantity for mosaic transfer

### ISSUE THREAD

**Issue by robwoodgate** [NemProject/NanoWallet#325]
NanoWallet allows a transaction to be sent (and levy collected if mosaic has absolute levy) for an attached mosaic with ZERO quantity specified.

It makes no sense to have a zero mosaic transfer, so NanoWallet should warn / block transaction from being sent in this case.

See this hash as an example of such a transfer:
http://chain.nem.ninja/#/transfer/ddeadb95f5d2481036f4690248f7109c3406a51a553032473de032dfbf935d13

My NEM address is: nbovla-3v7z7h-7tt5vz-4pyrgo-e6y3dr-rqkacb-77ky

Cheers
Rob

Ps - I originally mentioned this in the NEM forum, and there is some discussion there
https://forum.nem.io/t/bug-nanowallet-allows-0-amount-for-mosaic-transfer/8967

**Comment by fyahfox** [comment]
Blocking such transactions is not the way to go. A short info/warning would be ok imo.
