### ISSUE TITLE
Payment has not been received.

### ISSUE THREAD

**Issue by teslla77** [NemProject/NanoWallet#326]
Hello, I sent 19582 XEM from my NANO Wallet on 19 Nov and it has not been received by Changelly:
Changelly indicate "Sorry! The payment was not received.

I type a message　and adress.

Is there something that is considered to be the cause of that?

**Comment by QuantumMechanics** [comment]
Hi,

Issue is probably from Changelly. Contact them, explain that you did not received your XEM and provide them the hash the transaction you sent, you can find it in the transaction details.
