### ISSUE TITLE
Missing NEM Transfer from Poloniex

### ISSUE THREAD

**Issue by rebelman** [NemProject/NanoWallet#327]
I transferred XEM from my poloniex account to NEM Nano wallet.  The transfer initially displayed under Unconfirmed Transactions.  But now it doesn't show anywhere in my Nano Wallet.  It was sent to the following Address from Poloniex account:
2017-11-23 14:19:19
Address: NBG7UT-DUDJ7P-KHU6A6-INZ732-LNZOBU-S2SJLR-R3LE
Txid: a2c877c62539d8edcd14f0910f44e40c215ab40662080ee321830374b0db1ba3

Where is my XEM?  Do I need to contact Poloniex or is this a NEM issue?

**Comment by rebelman** [comment]
Apologies, can see the transaction now!  Seems I didn't set a NODE in Nano Wallet.

**Comment by mizunashi** [comment]
That's right.
Remittance is done on the block chain.
This time, it seems that there was a problem with the NIS node you are referring to.
By changing the reference node, you were able to get the correct information.
