### ISSUE TITLE
Cannot Send Nem, FAILURE_TRANSACTION_CACHE_TOO_FULL

### ISSUE THREAD

**Issue by dangitsdavid** [NemProject/NanoWallet#330]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Expected Behavior
To send XEM back out to an exchange, such as Bittrex.

## Current Behavior
FAILURE_TRANSACTION_CACHE_TOO_FULL
I am unable to send my XEM out. The transaction fee is locked at 0.05 XEM and 0.10 XEM with a message attached.

## Possible Solution
No idea. I tried to find ways to increase my transaction fees but have not found that option available. I waited to send out my XEM but still no luck.

## Steps to Reproduce
1. Send some XEM to NanoWallet 1.4.13 from an exchange, such as Bittrex.
2. Wait for XEM to be confirmed in wallet.
3. Send XEM to Bittrex wallet (XEM wallet address and message)
4. You will then receive a "FAILURE_TRANSACTION_CACHE_TOO_FULL" message

## Details
I can increase my transaction fee by having a longer message, but the exchange will not accept my XEM if I do so. I have to send the exact message stated on the exchange. I am running Windows 10 and using Google Chrome.

**Comment by QuantumMechanics** [comment]
Hi,

"FAILURE_TRANSACTION_CACHE_TOO_FULL" means the transaction cache of the node is full. 

Changing the node should solve the problem.
