### ISSUE TITLE
sending XEM

### ISSUE THREAD

**Issue by rhollonds1** [NemProject/NanoWallet#331]
Hey I am trying to send my XEM to an exchange and it seems to be stuck....as per below from my account....what to do now to get my XEM to send??....R

Confirmed Unconfirmed 0
Account	Amount	Message	Date
 ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR	- 2 129.000000 XEM	Encrypted
Tue, 05 Dec 2017 11:56:31 GMT
Transfer transaction
From NA7DJN-2CECZ2-S6CDLS-TDOJNE-M45JLN-JN54J2-DZGR
To ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR
Amount2 125.000000 XEM
Fee 4.000000 XEM
Message Encrypted --> Decode 
Block 1402021
Hash 35ffb42c98fe39410eab829665a00989ae0aad9d16b0eed9a03794f5a9f3ed6c
 NBZMQO-7ZPBYN-BDUR7F-75MAKA-2S3DHD-CIFG77-5N3D	+ 2 132.788530 XEM		Wed, 16 Aug 2017 10:09:07 GMT
Transfer transaction
From NBZMQO-7ZPBYN-BDUR7F-75MAKA-2S3DHD-CIFG77-5N3D
To NA7DJN-2CECZ2-S6CDLS-TDOJNE-M45JLN-JN54J2-DZGR
Amount2 132.788530 XEM
Fee 4.000000 XEM
Block 1243325
Hash 2d55abb5ddee571ed4e080b4f8ff7d1a0df13f25b187c0b650d6f05411230d2c

**Comment by tongokongo** [comment]
It's sent :)
You made a mistake, you encrypted the message so bittrex doesn't see it. You need to send them message to bittrex customer service, create ticket for this issue. You need to explain that your message in transaction was encrypted. Good luck.

**Comment by rhollonds1** [comment]
Txs so much I have a ticket with Bittrex now for my request.....R
