### ISSUE TITLE
NEM nano 2.0 testnet 

### ISSUE THREAD

**Issue by trikar** [NemProject/NanoWallet#333]
tested with my trezor in Windows and universal client. 
I can't enter with my trezor through Windows, chrome issue
With the client It works. 
Both clients are limited to Send, not to receive

![image](https://user-images.githubusercontent.com/14200336/33696659-6845b0ee-db57-11e7-84cd-94264d4ceb5b.png)
![image](https://user-images.githubusercontent.com/14200336/33696704-98cc0286-db57-11e7-835d-70ffc71b85f0.png)

**Comment by QuantumMechanics** [comment]
Hi,

>  I can't enter with my trezor through Windows, chrome issue

Thanks, will look into it

>  Both clients are limited to Send, not to receive

It was a bit confusing here, so I removed it. Will add it back somewhere else.

**Comment by cryptoBeliever** [comment]
I agree that account public address should be presented more clear for user. Sometimes they doesn't know from where copy they address. There was also extreme cases where user use to withdraw from exchange delegated account address.

**Comment by Sateetje** [comment]
Is it possible to show the address on each page? Maybe an extra row above the dashboard page.

Something like the attached file, but than nicer :)

![address](https://user-images.githubusercontent.com/16215404/34008178-c6b2eee6-e104-11e7-9bb5-974636861ac7.png)

**Comment by cryptoBeliever** [comment]
I will create seperate issue to show address more clearly.
