### ISSUE TITLE
Проблема с выводом монет.FAILURE TRANSACTION NOT ALLOWED FOR MULTISIG Что это?

### ISSUE THREAD

**Issue by alewka2013** [NemProject/NanoWallet#338]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by alewka2013** [comment]
Windows 10

**Comment by mizunashi** [comment]
Это сообщение появится, когда ваша учетная запись будет мультисети.
Когда вы снимаете деньги со своей учетной записи, вам нужен заказ и подпись от подписывающего лица, которое вы устанавливаете при многомерном размере.

Если вы не выполняете такую операцию, мы проверим ее, поэтому, пожалуйста, сообщите мне адрес вашего NEM.
<HR>
That message will appear when your account is multisized.
When you withdraw money from your account, you need an order and signature from the Signer that you set when you multi-sized.

If you are not doing such an operation, we will investigate, so please tell me your NEM's address.
