### ISSUE TITLE
https://github.com/NemProject/NanoWallet/issues/336

### ISSUE THREAD

**Issue by Danilwork** [NemProject/NanoWallet#339]

**Comment by mizunashi** [comment]
#336 has already been closed.

**Comment by Danilwork** [comment]
but there is no answer as to why hanging translation

**Comment by Danilwork** [comment]
But the technical work is proceeding on two different exchanges. So what is happening in the network NEM. And I have the transaction hanging for the third day, if the problem is on the other side, then the sending should be cancelled or leave and there is not be credited. I have a positive balance does not increase and the coins hang, I can't even cancel it.
![image](https://user-images.githubusercontent.com/32951184/33762664-6b27a7fa-dc1e-11e7-9b13-f5a896d63d27.png)

**Comment by mizunashi** [comment]
For the payment to Yobit, similar questions are received.
Currently there is no information on what kind of situation it is.

The sent xem has arrived at Yobit. It is proven in the block chain.
There is no way other than asking Yobit what Yobit is going to do with that money.

Please note that this is not a problem with NanoWallet, so please wait for information at forum.nem.io.
