### ISSUE TITLE
Display of remaining characters in transmitted message

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#34]
I checked how many characters I can send Japanese in advance if it is Japanese.
Likewise, I also checked how many characters I could send encryption.

How long is the character too long when it is actually too long? I think that general people do not know.

I think that this has been judged after throwing it to the API.
I think that it is good to embed character count js in NanoWallet.
Ultimately, it would be very helpful if you could implement a countdown like the number of characters like twitter.

**Comment by QuantumMechanics** [comment]
Hi, 

> Ultimately, it would be very helpful if you could implement a countdown like the number of characters like twitter.

I'll add that :)

**Comment by QuantumMechanics** [comment]
Countdown :)

https://github.com/NemProject/NanoWallet/commit/54887dc4085db602a8366162a6581dab8dd679e5
