### ISSUE TITLE
Почему сеть mainnet не доступна?

### ISSUE THREAD

**Issue by alewka2013** [NemProject/NanoWallet#340]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mizunashi** [comment]
Нажмите узел и выберите другой сервер из выпадающего меню.
В текущем выбранном узле может быть ошибка.
--
Click the node and select another server from the pull down menu.
There may be an error in the currently selected node.

**Comment by alewka2013** [comment]
я пробовал так. ничего не получается
