### ISSUE TITLE
Nano 2.0 encrypted message fee

### ISSUE THREAD

**Issue by cryptoBeliever** [NemProject/NanoWallet#342]
Wallet: Nano wallet 2.0 (Testnet) 
Browser: Chrome for Android (ASAP when I will be at home I verify this on desktop version) 

## Expected Behavior
When message type (encrypted / unencrypted) is changing by user fee information should also change. 

## Current Behavior
Fee information doesn't change when changing to encrypted type. If change to encrypted type fee info doesn't change. It doesn't change also when we put password. It changes in moment when user hit send button. 

## Possible Solution
Info about fees should change when message type is changing like in 1.4.13.

## Steps to Reproduce

1. Go to send view. Put address to send and message. 
2. Change type to encrypted. Fee doesn't change. 

If bug is accepted please send bounty to address:
NDC64AJMAFIZSA2OLJZWRYGFMSN7ZHZISCNMZTM5

**Comment by QuantumMechanics** [comment]
Hi,

Thanks, now fixed in 2.0.2 https://github.com/NemProject/NanoWallet/commit/35480a9c9da0f8bd93c608b8e232d76152606a9c

**Comment by jabo38** [comment]
Bounty paid. Tx hash: fb6f9bab20982e32ec269486052c04ad71b6f0bb68a541fbb341dd2a49fb35e1
