### ISSUE TITLE
Добрый день. Вывел монеты из кошелька на биржу . Монеты пропали , на биржу не поступили. Помогите разобраться в проблеме !!!

### ISSUE THREAD

**Issue by maxim19870302** [NemProject/NanoWallet#344]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by cryptoBeliever** [comment]
Проверьте, включено ли сообщение в транзакцию. Для большинства обменов требуется код сообщения.

---

Please verify if you include message code in transaction. Message code for most exchanges is required.

**Comment by maxim19870302** [comment]
Не включено было, что делать ?

**Comment by maxim19870302** [comment]
Не включил сообщение в транзакцию, что теперь мне делать???

**Comment by cryptoBeliever** [comment]
Вы должны связаться со службой поддержки. Идентификатор транзакции можно найти через explorer.ournem.com, просто введите свой адрес и выполните поиск. Отобразится список транзакций. Нажмите на intetesting транзакции и скопируйте хеш и отправьте для поддержки обмена.

---

You must contact with exchange support and provide transaction id. Transaction id could be found via explorer.ournem.com,  just put your address and search. Transaction list will be shown. Click on intetesting transaction and copy hash and send to exchange support.

**Comment by maxim19870302** [comment]
Служба поодержки биржи или кошелька Nem ??

**Comment by maxim19870302** [comment]
ВВести адрес куда отправлял? Связаться со слжбой поддрежки кошелька Nem или Биржи???

**Comment by maxim19870302** [comment]
Ввести адрес куда отправлял или мой адрес? Связаться со слжбой поддрежки кошелька Nem или Биржи???

**Comment by maxim19870302** [comment]
Ввести адрес куда отправлял или с которого ? Связаться со слжбой поддрежки кошелька Nem или Биржи???

**Comment by cryptoBeliever** [comment]
Введите свой адрес в строке поиска http://explorer.ournem.com, найдите идентификатор транзакции и обратитесь в службу поддержки Exchange

--

Enter your address in search bar http://explorer.ournem.com find transaction id and contact with exchange support.

**Comment by cryptoBeliever** [comment]
Адрес, из которого был отправлен. Если вы отправили из другой биржи, идентификатор транзакции должен быть виден в истории отзыва.
--
Adress from which was sent. If you sent from other exchange transaction id should be visible in withdraw history

**Comment by maxim19870302** [comment]
Мне нужно обратиться в службу поддержки именно биржи куда я отправилил ?

**Comment by cryptoBeliever** [comment]
да

**Comment by maxim19870302** [comment]
Спасибо вам за помощь !!!!!!!!

**Comment by maxim19870302** [comment]
Since it was sent from a personal wallet please send exactly 34.938475 from the same origin but this time please use the unique Message, in an unencrypted format, from your balances page:
Что это значит не могу понять???

**Comment by cryptoBeliever** [comment]
Какой обмен это?
---
Which exchange is this?

**Comment by maxim19870302** [comment]
Я написал в службу поддеркжи биржи полонекс! они прислали мне это сообщение! я перевел свои токены из кошелька Nem им на биржу ! забыв прикрепить сообщение. что они просят меня сделать?

**Comment by cryptoBeliever** [comment]
Вы должны делать то, о чем они просят. Отправлено с вашего аккаунта 34.938475 XEM на адрес Poloniex и на этот раз приложите код сообщения, предоставленный Poloniex. Это будет доказательством для Poloniex, что это ваш адрес. После этого они возвращают ваши жетоны. У вас есть 34.938475 XEM в вашем аккаунте?

---

You must do what they ask for. Sent from your account 34.938475 XEM to Poloniex address and this time attach message code provided by Poloniex. This will be proof to Poloniex that this is your address. After that they return your tokens. Do you have 34.938475 XEM on your account?

**Comment by maxim19870302** [comment]
Я перевел им совсем другую сумму и монеты списались с моего баланса. Что делать?

**Comment by cryptoBeliever** [comment]
Вы должны выполнить вторую транзакцию точно в размере 34.938475 XEM с кодом сообщения для проверки Poloniex. После этого они возвращают вам обе транзакции.

--

You must do second transaction for exactly 34.938475 XEM amount with message code for Poloniex verification. After that they return you both transactions.

**Comment by maxim19870302** [comment]
Что значит код сообщения для проверки Polonex?

**Comment by cryptoBeliever** [comment]
Он должен быть видимым в вашей учетной записи Poloniex. Этот вид выглядит так (отметьте в учетной записи Poloniex):
https://forum.nem.io/uploads/default/original/2X/e/ec7468f693926c25c7ccd1c1d781eb933de34f23.png

Это депозитный вид.

---

It should be visible in your Poloniex account. This view looks like this (check in Poloniex account):
https://forum.nem.io/uploads/default/original/2X/e/ec7468f693926c25c7ccd1c1d781eb933de34f23.png

It's deposit view.

**Comment by maxim19870302** [comment]
Подскажите где напрямую можно купить монеты Xem за рубли ?
