### ISSUE TITLE
Sending out coins to cryptopia

### ISSUE THREAD

**Issue by joebull1** [NemProject/NanoWallet#345]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details
The coins never made to cryptopia wallet after sending for the nano wallet anyone have idea what went wrong

**Comment by cryptoBeliever** [comment]
Hello. Please create topic on forum.nem.io. This is no place for reporting this. Please attach information about your public NEM address. We will help you but please on forum.nem.io :)
