### ISSUE TITLE
Add NOTE to Message field in send section

### ISSUE THREAD

**Issue by archiii92** [NemProject/NanoWallet#346]
Here was suggested a good idea - add little text to Message field with warnings. I can implement this feature.

https://forum.nem.io/t/sending-xem-importance-of-message-field/9852

![](https://forum.nem.io/uploads/default/original/2X/6/69eda763d5909e035b057f39ff88b17bb63b3c1f.jpg)

**Comment by TomRata** [comment]
LOL that's my suggestion, I was about to post it here :)

**Comment by archiii92** [comment]
I'm get here first )

**Comment by cryptoBeliever** [comment]
Yeah. Idea was TomRata orginaly post in https://forum.nem.io/t/sending-xem-importance-of-message-field/9852

**Comment by QuantumMechanics** [comment]
Hi, 

I have added a check in 2.0 some times ago. It shows an alert and block the transaction if destination is an exchange address and no message is set.

https://github.com/NemProject/NanoWallet/blob/2.0/src/app/modules/transferTransaction/transferTransaction.controller.js#L174

**Comment by TomRata** [comment]
When will this be implemented? because the feature wasn't in my Nano wallet yesterday & I could really have used it then, or am I using an outdated version (currently Version: BETA 1.4.13) - Please advise. TIA.

**Comment by QuantumMechanics** [comment]
It is implemented in version 2.0, that will be released soon.

Version 1.x.x is no longer maintained.

**Comment by TomRata** [comment]
Ok, excellent. That'll save a lot of unnecessary hassle for (Nem)bers in the future. :)

**Comment by cryptoBeliever** [comment]
@QuantymMechanics good idea also will be add warning when encrypted message is sent or when multisig transaction is sent. Not many people make this mistake but still I have over 10 cases in last months.
