### ISSUE TITLE
Transaction completed on Cryptopia but Coins not appearing in my Wallet after 24 hours

### ISSUE THREAD

**Issue by Nellebelle** [NemProject/NanoWallet#347]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by apply75** [comment]
I am having the same issue.  cryptopia is appending a : to the end of your address causing it to change the address and send nowhere.  If you download the transaction history you will see the extra : at the end of your address.  Tested with 2 transactions lost both amounts.  just signed up to hitbtc and bought and withdrew without issue into my wallet

**Comment by Nellebelle** [comment]
I'm so freakin pissed!!! WTF over $1000

**Comment by mizunashi** [comment]
I'm sorry.
This is the place to report a bug in NanoWallet.

Please write to https://forum.nem.io/c/tech-support.

**Comment by apply75** [comment]
I'm sorry.
This is the place to report a bug in NanoWallet.

Please write to https://forum.nem.io/c/tech-support.

your lucky i took the time to even reply here and find a resolution you have a billion in assets update your own tickets guys. come on.

**Comment by QuantumMechanics** [comment]
Hi,

This is an exchange issue that has nothing to do with our app.

> cryptopia is appending a : to the end of your address causing it to change the address and send nowhere

If the address is invalid, it will be immediately rejected by NIS. So your XEM are probably still on the exchange.

**Comment by Nellebelle** [comment]
Hey,

I just signed the petition "State of Hawaii House of Represenatives:
legislation" and wanted to see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/cKdBGCmcvb

Thanks!
Marianela

**Comment by apply75** [comment]
Whats this for?
