### ISSUE TITLE
Проблема с вводом на биржу

### ISSUE THREAD

**Issue by shurik29** [NemProject/NanoWallet#349]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details

Приветствую! Хотел сделать депозит на YoBit с другой биржы. Только потом заметил, что статус кошелька "тех. работы". Пошел 2 день.

Вот что говорит саппорт:

Dear User!

Support answer:

Deposit\\Withdrawal coin will be available after you upgrade the source code of the wallet. Unfortunately the developers are in no hurry to send you updates
- therefore, in order to avoid the loss of users, the network is not available.
If you have updated the source code of the coin, send us (https://yobit.net/en/maintenance_request/ Free)and we will promptly correct the problem on the coin.
Thank you for contacted the support.

Помогите, пожалуйста. Как решить проблему?

C уважением!

**Comment by QuantumMechanics** [comment]
Hi,

> Deposit\Withdrawal coin will be available after you upgrade the source code of the wallet. Unfortunately the developers are in no hurry to send you updates

I don't know why Yobit says that..

This message makes no sense, the wallet you use has nothing to do with the exchange ability to receive and send funds.
