### ISSUE TITLE
Fix grammar error at Start/Stop deleg.harvesting

### ISSUE THREAD

**Issue by r3n3x** [NemProject/NanoWallet#35]
Some language problem here I guess.

"If you was already harvesting using Nano ..."
-> If you were already harvesting using Nano 

"local storage have been erased"
-> local storage has been erased

"select the node you was using to restore app status"
-> select the node you used to restore the app status

--->> however the whole text doesn't make proper sense to me :-)

@jabo38  ... EN Mothertounge speaker?

**Comment by saulgray** [comment]
There are some other grammar issues as well. If someone would like to go over this file and make those grammar changes, it would be much appreciated. https://github.com/NemProject/NanoWallet/blob/master/src/app/modules/languages/en.js

**Comment by QuantumMechanics** [comment]
https://github.com/NemProject/NanoWallet/commit/2e127faeba0cdb7254ffbb914b1d73ecfe5ba77b
