### ISSUE TITLE
Can't see more than 10 unconfirmed multisig transactions

### ISSUE THREAD

**Issue by renolteng** [NemProject/NanoWallet#353]
## Expected Behavior
Getting 14 transactions to sign

## Current Behavior
Can only see 10 transactions, can't even see the other 4 after logging out and in again.
Sometimes the transactions that are already signed can't be seen.
I checked NCC and NanoWallet at the same time, all 14 transactions were seen normally.

## Possible Solution
some modifications on dashboard of NanoWallet

## Steps to Reproduce
1. Initiate 14 transactions with a 3 of 4 multisig account
2. Use another cosignatory account to check unconfirmed transcations
3. Sign the existing ones and check again
4. Try logout and login again

**Comment by fyahfox** [comment]
same as https://github.com/NemProject/NanoWallet/issues/295

**Comment by cryptoBeliever** [comment]
Duplicate #295.
