### ISSUE TITLE
Missing coins exchanged on changelly 

### ISSUE THREAD

**Issue by funkymusic1232** [NemProject/NanoWallet#358]
Hello all,

Im sorry if this isnt allowed, I recently became an investor in crypto currency. I purchased some BIT from coinbase and then transferred them to changelly to convert to XEM to my nano wallet i just set up. I got all confirmations from coinbase that they sent the coins to changelly, I confirmed on changelly that the transfer went successfully, and ive been waiting for the funds to show up on my nano wallet. Unfortunately they are not there. Here are some info to maybe help you guys help me.

NANO wallet address: NDSRPZRV5TBCK23SHUOWFM566PER7Z3GLYKD2LHI

Changelly transaction details:

SENDER	funkymusic1232@gmail.com
INPUT TRANSACTION HASH	72f1d6e7eed82bdf902435df262c8d7243cd171c40abeb63c86bf28e07cad895
AMOUNT	0.0044616 BTC
MONEY RECEIVED	15 Dec 2017, 08:56:07
FEE	1.678391 XEM
EXCHANGE RATE	1 BTC = 30,184.993462 XEM
RECEIVER	NDSRPZRV5TBCK23SHUOWFM566PER7Z3GLYKD2LHI
OUTPUT TRANSACTION HASH	e931190f6906941519b505be39c03b951b41cbc9985ad14f77675a7faaa546d7
AMOUNT	134 XEM
MONEY SENT	15 Dec 2017, 09:09:23

also i have switched through nodes and still nothing. I dont see any confirmed transactions in my nano wallet nor do i see any unconfirmed transactions. Any and all help would be appreciated.

**Comment by QuantumMechanics** [comment]
Hi,

The XEM are still on Changelly, on the explorer your account is empty: http://explorer.ournem.com/#/s_account?account=NDSRPZRV5TBCK23SHUOWFM566PER7Z3GLYKD2LHI.

It seems they have some issues because the widget doesn't work for me since a few days...

You should contact them and explain that you didn't received your coins

**Comment by funkymusic1232** [comment]
Thank you. I’ve sent them a message.
