### ISSUE TITLE
Unable to Receive/Deposit XEM from Exchange (Windows/ Chrome)

### ISSUE THREAD

**Issue by CryptoThorKitty** [NemProject/NanoWallet#359]
## Expected Behavior
XEM should be deposited into NanoWallet from Bittrex Exchange assuming Node is operating.

## Current Behavior
No Confirmations shown on Nano Dashboard after 36 hours.  XEM is shown as 0 "Available Balance" however, being listed as "Reserved" on exchange indicating XEM as been sent to correct address but not confirmed. 
![xem pending deposit](https://user-images.githubusercontent.com/34582974/34057175-92e9167a-e19b-11e7-8a80-67d7a13b08b4.PNG)

## Possible Solution
Cancel transaction on Exchange >Try different operating/Green Nodes> Try to Deposit/receive funds 

## Steps to Reproduce

1.  Ensure Nodes are operating/Green on NanoWallet
2.  Retrieve Deposit address from NanoWallet
3.  Send NEM to correct wallet address from Exchange
4.  Wait for Confirmations and Deposit to appear in Nanowallet

## Details
I have already tried to switch different operating nodes in order to receive deposit of NEM with no success.  Also have ensured deposit address were correct.  Please advise.

**Comment by QuantumMechanics** [comment]
Hi,

> being listed as "Reserved" on exchange indicating XEM as been sent to correct address but not confirmed.

Then the problem is on the exchange, contact them and explain that your XEM withdrawal seems stuck.

**Comment by CryptoThorKitty** [comment]
They replied and said it was in invalid address.

Can you please confirm that this address is valid?  Thank you for your time
and help. Appreciate it.

"NBPV3JCWUBU5W3JN2QO5QDFZRMCU4DCXDRXF7P67"

‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by QuantumMechanics** [comment]
> Can you please confirm that this address is valid?

Open Nano and log into your wallet. Go to `Account` and if the address showing is NBPV3J-CWUBU5-W3JN2Q-O5QDFZ-RMCU4D-CXDRXF-7P67 then it is valid.

http://chain.nem.ninja/#/search/NBPV3JCWUBU5W3JN2QO5QDFZRMCU4DCXDRXF7P67
