### ISSUE TITLE
About cooperation between address book and dashboard

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#36]
There are labels and NEM addresses registered in the address book.
Is the NEM address displayed on the dashboard now appearing as a label in the future?

**Comment by jabo38** [comment]
We didn't have time to do this before, but I think this would be a great thing and is needed.

**Comment by QuantumMechanics** [comment]
Added https://github.com/NemProject/NanoWallet/commit/dc882f2d91427f7b1b774cf825d7d610631f64b1
