### ISSUE TITLE
[2.0] Encrypted Transaction Chars not counting properly

### ISSUE THREAD

**Issue by tongokongo** [NemProject/NanoWallet#360]
## Expected Behavior
Characters should go down one by one

## Current Behavior
Characters going down by sets of "16" chars. 

## Possible Solution
No idea, sorry, I checked in 1.4.3 and it worked properly. 

## Steps to Reproduce
1. Log in to trezor account
2. Try sending encrypted message 
3. Write char by char observing "characters left" field
4. characters going down in sets of "16" not one by one.

![1](https://user-images.githubusercontent.com/29152385/34064036-0537f34a-e1ab-11e7-9572-1fdfbea25042.JPG)

![2](https://user-images.githubusercontent.com/29152385/34064050-18853534-e1ab-11e7-83b1-e7bed7156c5d.JPG)

## Details
NEM address if bounty:
NDZTPA-7AUVVD-AO2SXQ-77I3V4-ZSLETV-SPF7CT-RROE

**Comment by QuantumMechanics** [comment]
Same as https://github.com/NemProject/NanoWallet/issues/362

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: 68b93e11eeefaa169629e00a8f853668f57161095145a856bd04ddca51ae059a
