### ISSUE TITLE
[2.0] Can't access "Decode 

### ISSUE THREAD

**Issue by tongokongo** [NemProject/NanoWallet#361]
Before submitting your issue, please review the following checklist:

## Expected Behavior
After clicking "decode message", Trezor window should open.

## Current Behavior
Nothing happens

## Possible Solution
?

## Steps to Reproduce

1. Send encrypted message to Trezor wallet
2. click "decrypt" in nanowallet dashboard
3. try clicking "Decrypt message"

![3](https://user-images.githubusercontent.com/29152385/34064183-02792966-e1ac-11e7-97be-7779c8c20879.JPG)

## Details
NEM address if bounty:
NDZTPA-7AUVVD-AO2SXQ-77I3V4-ZSLETV-SPF7CT-RROE

**Comment by QuantumMechanics** [comment]
Hi, we know about this, @saleemrashid is working on fix

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: 111f7b8294795cf1f291148bda964421063e9b00d790858e569edb61721be27f
