### ISSUE TITLE
[2.0] Sending encrypted message limited to around 320 chars

### ISSUE THREAD

**Issue by tongokongo** [NemProject/NanoWallet#362]
## Expected Behavior
When I write encrypted message and "characters left" field is bigger than 0 -> transaction should work

## Current Behavior
When I write encrypted message and "characters left" field is around 701-720 characters, or less, I can't send it. Getting error: "Failed: bytes overflow". In 1.4.3 I was getting error while field was lower than 0 (message too long).  Don't know exact number, bug is related to:
https://github.com/NemProject/NanoWallet/issues/360

## Possible Solution
?

## Steps to Reproduce
1. Open Trezor, start creating transaction, encrypted message option.
2. Write message
3. When "characters left" field is smaller than 704, try sending it
4. Observe the error

![image](https://user-images.githubusercontent.com/29152385/34064308-f02b6fc0-e1ac-11e7-934a-b65c3c7e167b.png)

## Details
NEM address if bounty:
NDZTPA-7AUVVD-AO2SXQ-77I3V4-ZSLETV-SPF7CT-RROE

**Comment by QuantumMechanics** [comment]
@saleemrashid fixed the encrypted messages in the nem-sdk a day ago https://github.com/QuantumMechanics/NEM-sdk/commit/dc517323370c33ae797dfb7e0f4bf85f58ef4e59

It may have fixed this issue.

**Comment by saleemrashid** [comment]
This is not exactly a bug. The limit comes from https://github.com/trezor/trezor-mcu/blob/v1.6.0/firmware/protob/types.options#L45. There will be a new firmware to fix #361 and I can increase the limit to 1024 characters in that firmware.

**Comment by mizunashi** [comment]
TOREZOR firm 1.6 & NanoWallet 2.0.8
<hr>

Left 768 OK (256 chars) {unencrypt} on TREZOR
Left 767 NG (257 chars) {unencrypt} on TREZOR

Left 704 OK (256 chars) {encrypt} on TREZOR
Left 704 NG (257 chars) {encrypt} on TREZOR

(In the case of encryption, the Left characters change in parts of multiples of 16 characters.
So Left will be the same.)

Left 0 OK (1024 chars) {unencrypted} not TREZOR
Left 0 OK (975 chars) {encrypted} not TREZOR

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: 68b93e11eeefaa169629e00a8f853668f57161095145a856bd04ddca51ae059a
