### ISSUE TITLE
Cannot see menu in nano wallet

### ISSUE THREAD

**Issue by Febrero** [NemProject/NanoWallet#363]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior
Should see menu icons like:  dashboard, send, services, balance, etc

## Current Behavior
Cannot see any menu button. Connected to primary network

## Possible Solution
no idea sorry guys.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Febrero** [comment]
sorry doing in chrome!

**Comment by QuantumMechanics** [comment]
Hi, in this case you can try changing the node from the navbar
