### ISSUE TITLE
nano wallet - receive adress not selectable

### ISSUE THREAD

**Issue by Gahzayah** [NemProject/NanoWallet#364]
I use nano wallet 1.4.13, windows 10, hp spectre 360°.

In the "send/receive" section its not possible to select the full receive adresss. (tablet-mode).
I am also missed a button or somthing else to copy a adress to the clipboard.

The input fields not optimized for selecting text. (touch displays).

In general there a lot of interaktions that could be optimized for using in tablet mode.

**Comment by QuantumMechanics** [comment]
Hi,

Nano has not been optimized for small screens or touch devices.

The receive section does not exist anymore in 2.0 but in account page I have added a button to copy the addess to the clipboard https://github.com/NemProject/NanoWallet/commit/5c5c0d8cbdcac1b95038a92a8ae1a7e2885b9383
