### ISSUE TITLE
Where are my coins PLEASE!!!!!

### ISSUE THREAD

**Issue by ormerod76** [NemProject/NanoWallet#366]
I am not able to see my coins at my wallet.... Am I missing something please?

Complete	XEM	5233.00000000
2017-12-16 21:03:40
Address: NCAZJHQT2ZZSBJCUROAANGMG3NFORGHODKV6MYFL
Txid: b079ba25a4f56dbd88d36ab06a5f6ff34aa9f5eb0fcbfee124861c04237aad11

**Comment by QuantumMechanics** [comment]
Hi,

Make sure that `Node` circle in navbar is green. If not, you can click on it and select another node.

**Comment by bartnuman** [comment]
Same problem. But on all nodes, the circle stays red...

**Comment by QuantumMechanics** [comment]
Below the nodes list you can enter a custom IP, go to https://supernodes.nem.io and try some of them.

**Comment by bartnuman** [comment]
It works. It turned out was due to a blocked port 👍
