### ISSUE TITLE
[2.0]

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#367]
2.0.8 bugs

After logging in with TREZOR and adding an account you will be asked for your password.

![2017-12-17 14 15 34](https://user-images.githubusercontent.com/1645189/34076798-cc0c6174-e334-11e7-89ae-51c69bf33048.png)

**Comment by QuantumMechanics** [comment]
Fixed https://github.com/NemProject/NanoWallet/commit/367ced9e65127a25174dcb502484caf4a182d1c2
