### ISSUE TITLE
[2.0.10] Manage delegated account & Herbesting Page Bugs

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#368]
I found a bug at 2.0.10.

Going to the delegate harvesting page will result in this message.
Also, the host does not appear in the host setting of harvesting.

If you do not select the harvesting node and hit the start harvesting button, harvesting may be active.

![2017-12-19 6 44 34](https://user-images.githubusercontent.com/1645189/34130305-ad9571e8-e48a-11e7-9e82-ecc887685400.png)

![2017-12-19 6 44 43](https://user-images.githubusercontent.com/1645189/34130319-b34541f4-e48a-11e7-9ec5-8ec6df460710.png)

I rushed up, so I'm sorry.
NCVGXT-CV7YYG-CUTOWR-SEALEV-HVTDFR-J54BQY-DKTI

**Comment by mizunashi** [comment]
@QuantumMechanics 
Can I stop publishing?
Please hurry.

**Comment by QuantumMechanics** [comment]
Fixed https://github.com/NemProject/NanoWallet/commit/41ad869ae4923ea25a47b6d5e2bbed3601b00d14
