### ISSUE TITLE
The problem of entering the brain wallet Nano Wallet Beta 2.0.13

### ISSUE THREAD

**Issue by TeeX33** [NemProject/NanoWallet#371]
The problem of logging into the nanowallet of version 2.0.13 occurs if you use the previously created brain wallet in version 1.4.13 for the authorization to using vlt+password. You can only enter into the wallet by creating a new one using the previously saved private key. Users who previously created a brain wallet without saving the private key can not use the new version. Previously, it was assumed that the password for a brain wallet = private key

bounty NCNPO2-K2GZJ3-ZSSOGL-XUJ2QS-YLMNDC-AFNHAW-K6RS

**Comment by QuantumMechanics** [comment]
Hi,

Bug with brain wallet login, now fixed https://github.com/NemProject/NanoWallet/commit/7dde20244e868b1018086432c58cb65141e7049e

Going to release again.

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: 0a924be108708f98cfebed0287c6045da916965e0ba0c00959eab53d159ab239
