### ISSUE TITLE
[2.0.13] Can't send transaction  (Mainnet)

### ISSUE THREAD

**Issue by ghost** [NemProject/NanoWallet#372]
2.0.13 Universal Client (Mainnet)
Trezor 1.6.0

## Expected Behavior
Supposed to send normal transaction to another address

## Current Behavior
"Send"-Button is not clickable
![screen shot 2017-12-19 at 10 11 57](https://user-images.githubusercontent.com/34475192/34149374-24a40654-e4a5-11e7-8e53-8f8cf7304757.png)

## Steps to Reproduce
Login in to Universal2.0.13 with Trezor WITH Passphrase.
Try to send normal transaction.

Bounty: 
NCJADP-BV2663-HAF33J-6REKZP-T4QS6E-JEP4QD-6PPP

**Comment by QuantumMechanics** [comment]
Hi,

Are you sure you are using 2.0.13 ?

We can't see the bug on our end

**Comment by jabo38** [comment]
1. Have you updated your Trezor with the latest firmware?
2. You did have XEM and/or a message loaded, right? 
3. Can you double check to make sure the address was entered properly?

**Comment by ghost** [comment]
@jabo38 
I double checked and still the send-button stays unclickable(in 2.0.14)
Furthermore this message appears...
![screen shot 2017-12-19 at 22 42 56](https://user-images.githubusercontent.com/34475192/34180295-6f52ae44-e50e-11e7-92e5-824eeb3a3305.png)
But it is disappearing after a couple seconds.

**Comment by mizunashi** [comment]
Please change node, try again.

**Comment by ghost** [comment]
It's working! I selected a node  and now it runs as it should. 

But when I logged in, the node circle was still green even if there was no node selected in the first place and after the red-alerts disappeared.
![screen shot 2017-12-20 at 08 29 50](https://user-images.githubusercontent.com/34475192/34195991-575ce212-e560-11e7-8810-90fde709311b.png)

**Comment by mizunashi** [comment]
Recently, although the nodes are running, there are nodes whose chains are not synchronized, or where the response is slow due to concentration of access.
In this case, the circle becomes green, but an error may occur.
If an error occurs, select a different node.
