### ISSUE TITLE
Hello! I do not have a balance in my wallet and there are no transaction histories! There are no wallet settings! Please help!

### ISSUE THREAD

**Issue by zgen1999** [NemProject/NanoWallet#373]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

You should have at least the `Node` button with a circle, click on it and try another node from the node list

**Comment by cryptoBeliever** [comment]
If you want help please report on forum.nem.io in Tech Support). This is not best place because here should be only conformed errors (not helpdesk problems)
