### ISSUE TITLE
[Feature] Add CZK currency to the list of currencies

### ISSUE THREAD

**Issue by pokorm** [NemProject/NanoWallet#374]
Hi, it would be great if I can choose [CZK](https://en.wikipedia.org/wiki/Czech_koruna) currency from top dropdown list in nano Wallet.

**Comment by QuantumMechanics** [comment]
Hi,

The list of currencies is from https://blockchain.info/ticker API

I have no control on that without adding a new API request.

**Comment by pokorm** [comment]
Ah, ok then. I will try to contact them and ask for that.

Thanks for info ;-)!
