### ISSUE TITLE
Start.html file missing in zip download

### ISSUE THREAD

**Issue by old-greywolf** [NemProject/NanoWallet#376]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [X ] **DO** describe operating system and browser used
OS:  Linux Mint 18-3 64-bit, 
Browsers:
Firefox Quantum, 57.0.1 (64-bit)
Chromium Version 63.0.3239.84 (Official Build)

## Steps to Reproduce

1.  Download NanoWallet-2.0.13-linux64.zip from https://github.com/NemProject/NanoWallet/releases/download/2.0.13/NanoWallet-2.0.13-linux64.zip
2.  Extraxt into any directory.
3.  Look for Start.html file.
4.  Notice that the Start.html file is not present.

## Details
  I also tried the file https://github.com/NemProject/NanoWallet/releases/download/2.0.13/NanoWallet-2.0.13.zip, which does have the Start.html file, but it gives me errors: 7 specs, 7 failures:
    Mosaic definition transaction module tests
        encountered a declaration exception

    Mosaic supply change transaction module tests
        encountered a declaration exception

    Importance transfer module tests
        encountered a declaration exception

    Provision namespace transaction module tests
        encountered a declaration exception

    Transfer transaction module tests
        encountered a declaration exception

    Wallet service tests
        encountered a declaration exception

    WalletBuilder service tests
        encountered a declaration exception

**Comment by QuantumMechanics** [comment]
Hi,

There is no `start.html` file in the build versions, only in universal version.

To start the linux build, open a console in the directory and type:

`./NanoWallet`

**Comment by old-greywolf** [comment]
./NanoWallet: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory
But the file (libnw.so) is in the directory.

**Comment by mizunashi** [comment]
I have never used the Linux version, so I can not answer.
It might work if you add a directory with that library to the LD_LIBRARY_PATH environment variable.

**Comment by old-greywolf** [comment]
gizmo@ROSEWILL ~/NanoWallet-2.0.13-linux64 $ ./NanoWallet
[31704:31704:1219/130729.065888:FATAL:chrome_main_delegate.cc(1014)] Check failed: !loaded_locale.empty(). Locale could not be found for 
#0 0x7fd434c310d7 <unknown>

Received signal 6
#0 0x7fd434c310d7 <unknown>
  r8: ffffd576cc85eac0  r9: ffffd576cc85eab0 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffee0ffa690 r13: 0000000000000089 r14: 00007ffee0ffa688 r15: 00007ffee0ffa680
  di: 0000000000007bd8  si: 0000000000007bd8  bp: 00007ffee0ffa1c0  bx: 00007ffee0ffa1c0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007fd4324ca428  sp: 00007ffee0ffa018
  ip: 00007fd4324ca428 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by mizunashi** [comment]
Unn.... This information is unlikely to be useful.
Is it possible to install a browser and use Universal Cliant?

**Comment by old-greywolf** [comment]
Yes, I tried the Universal Client, in Firefox and Chromium.  the browsers display 7 specs 7 failures.  I am not a developer, just some guy trying to get a wallet running, so I do not understand the output of the messages mean.  It lo like a bunch of line numbers called out in javascript.  I punched it into the NEM:Helpdesk Telegram group, and someone directed me here.  If anyone in interested in the verbose failure messages, I will post them.  But the 7 specs are listed in my original post.

**Comment by mizunashi** [comment]
Let's test with Universal Version.
Please paste Javascript error message here.

As a separate case, is 3rd-party cockie set to accept at Browser setting?

**Comment by old-greywolf** [comment]
Firefox:  Accept third-party cookies: Always
Chromium:  Block third-party cookies:  slide button is OFF
= = = = =
Jasmine   2.4.1
7 specs, 7 failures                                          finished in 0.005s
Spec List | Failures

Mosaic definition transaction module tests encountered a declaration exception
ReferenceError: angular is not defined in file:///home/gizmo/Nano_Wallet_2.0.13/tests.js (line 92873)
[505]</<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:92873:5
addSpecsToSuite@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:16347
Env/this.describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:15726
describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:2:30680
[505]<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:92865:1
s@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:246
e@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:425
@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:11

Mosaic supply change transaction module tests encountered a declaration exception
ReferenceError: angular is not defined in file:///home/gizmo/Nano_Wallet_2.0.13/tests.js (line 93353)
[506]</<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:93353:5
addSpecsToSuite@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:16347
Env/this.describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:15726
describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:2:30680
[506]<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:93346:1
s@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:246
e@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:425
@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:11

Importance transfer module tests encountered a declaration exception
ReferenceError: angular is not defined in file:///home/gizmo/Nano_Wallet_2.0.13/tests.js (line 92722)
[504]</<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:92722:5
addSpecsToSuite@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:16347
Env/this.describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:15726
describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:2:30680
[504]<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:92713:1
s@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:246
e@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:425
@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:11

Provision namespace transaction module tests encountered a declaration exception
ReferenceError: angular is not defined in file:///home/gizmo/Nano_Wallet_2.0.13/tests.js (line 93678)
[507]</<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:93678:5
addSpecsToSuite@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:16347
Env/this.describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:15726
describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:2:30680
[507]<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:93670:1
s@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:246
e@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:425
@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:11

Transfer transaction module tests encountered a declaration exception
ReferenceError: angular is not defined in file:///home/gizmo/Nano_Wallet_2.0.13/tests.js (line 94118)
[508]</<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:94118:5
addSpecsToSuite@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:16347
Env/this.describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:15726
describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:2:30680
[508]<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:94111:1
s@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:246
e@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:425
@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:11

Wallet service tests encountered a declaration exception
ReferenceError: angular is not defined in file:///home/gizmo/Nano_Wallet_2.0.13/tests.js (line 94758)
[509]</<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:94758:5
addSpecsToSuite@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:16347
Env/this.describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:15726
describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:2:30680
[509]<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:94753:1
s@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:246
e@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:425
@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:11

WalletBuilder service tests encountered a declaration exception
ReferenceError: angular is not defined in file:///home/gizmo/Nano_Wallet_2.0.13/tests.js (line 94894)
[510]</<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:94894:5
addSpecsToSuite@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:16347
Env/this.describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:1:15726
describe@https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js:2:30680
[510]<@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:94891:1
s@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:246
e@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:425
@file:///home/gizmo/Nano_Wallet_2.0.13/tests.js:1:11

**Comment by mizunashi** [comment]
@QuantumMechanics Do you know something from this log?
