### ISSUE TITLE
About mistake of remittance address

### ISSUE THREAD

**Issue by yuuhi0320** [NemProject/NanoWallet#378]
I mistook the mynemwallet address and sent it to the namespace address!

This is the transaction ID
2017/05/20 00:30
TXID  6cdeaf313774999785eaa5ca4862a5516274bdc3bab30a2699e13174f02d9c98

I want to get back the money！
Please tell me what to do！

**Comment by yuuhi0320** [comment]
sorry .TXID mistake
TXID : 5d872f457592a1662c8713e2d97ccb733236763d9f56ade1bc
hash : 6cdeaf313774999785eaa5ca4862a5516274bdc3bab30a2699e13174f02d9c98

**Comment by QuantumMechanics** [comment]
Hi,

The tx hash is not valid, nothings shows on explorer http://chain.nem.ninja/#/transfer/6cdeaf313774999785eaa5ca4862a5516274bdc3bab30a2699e13174f02d9c98

**Comment by yuuhi0320** [comment]
oh...
I lost it at nano wallet time( 2017/05/19) 
In other words, it is the data that I send mistake address for the old wallet before the hard fork.
[readme.txt](https://github.com/NemProject/NanoWallet/files/1577319/readme.txt)


This URL is the evidence of a problem.
I interacted before, but I was not able to deal with it properly.
What's going on?
Does the TXID disappear?
I want to ask here

http://mijin.io/forums/forum/%E6%97%A5%E6%9C%AC%E8%AA%9E/nem/2277-nano-wallet-%E3%81%AE%E9%80%81%E9%87%91%E5%85%88%E3%82%A2%E3%83%89%E3%83%AC%E3%82%B9%E3%81%AE%E3%83%9F%E3%82%B9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
