### ISSUE TITLE
Security warning in devtools console

### ISSUE THREAD

**Issue by semolex** [NemProject/NanoWallet#382]
## Expected Behavior
No security warning at devtools console

## Current Behavior
Security warnings present:
```pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details.```

## Possible Solution
Implement sanitization and fix not-escaped characters.

## Steps to Reproduce
1. Open NanoWallet, go to Window>Devtools.
2. Look at the devconsole

## Details

Checked on wallets: Version: 2.0.14, Version: BETA 1.4.13
<img width="1255" alt="screen shot 2017-12-21 at 4 46 47 pm" src="https://user-images.githubusercontent.com/7127330/34260769-9df330cc-e66f-11e7-8e9b-037a1de1880e.png">

Wallet: NCRUIO-A4KYM5-OLWWE2-O6J6SO-TR3XMW-5JMW6W-PW7L

**Comment by mizunashi** [comment]
What is the version of NanoWallet?

**Comment by semolex** [comment]
@mizunashi
Wallet version: BETA 1.4.13
OS: macOS Sierra

**Comment by semolex** [comment]
Same can be reproduced with Version: 2.0.14

**Comment by QuantumMechanics** [comment]
Hi,

2.0.14 is sanitized everywhere an input of the outside world is appended.

Did nothing to the i18n system because I really don't see how it could be attacked on your local machine. Also it is used with brackets {{ }} (ng-bing), that automatically escapes.

See https://docs.angularjs.org/api/ngSanitize/service/$sanitize

**Comment by QuantumMechanics** [comment]
Not an expert, so actually I might be wrong about use of brackets with angular-translate.

Just in case, I have set a 'sanitizeParameters' strategy, not sure of efficiency.

Tried other strategies but 'sanitize' renders Japanese and Chinese with hex values and 'escape' does not render the links..

At least no warning showing now

**Comment by semolex** [comment]
So no moves required when running locally? That is ok then.

**Comment by semolex** [comment]
@QuantumMechanics actual line of code: 42134 in `main.js`

```return logFn.apply(console, args);```

**Comment by QuantumMechanics** [comment]
https://github.com/NemProject/NanoWallet/commit/a987256126c1f5872788560f76a5826a913a7a90

> So no moves required when running locally?

Yes
