### ISSUE TITLE
an error occurred trying to fetch market information

### ISSUE THREAD

**Issue by Trankvilizator** [NemProject/NanoWallet#384]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior
I have downloaded NanoWallet Version: 2.0.14, registered and logged in, but I see an error (see details)

## Steps to Reproduce

1. Open Nano Wallet 
2. Log in
3. Error

## Details
https://monosnap.com/file/epPPnd924b0idCHIgaPzJsyj2GH0QZ

**Comment by QuantumMechanics** [comment]
Hi,

If after some attempts it still doesn't work, it could be that your connection can't fetch Poloniex market data 

Someone reported this a few months ago https://github.com/NemProject/NanoWallet/issues/67
