### ISSUE TITLE
Dashboard -NanoWallet shows wrong percentage change(24hr)

### ISSUE THREAD

**Issue by gramkn** [NemProject/NanoWallet#385]
I'm using Firefox browser.  Windows 8 64bit os
## Expected Behavior
It should accurately show the percentage change of Xem price over last 24hrs>

## Current Behavior
 It is showing a range of 9.5%-12%, even when it's clearly wrong 

## Possible Solution
 date reference?

## Steps to Reproduce

1. go to dashboard
2. hit refresh button
3.observe percentage
4.calculate correct percentage

## Details
It seems to have just started recently, within the last 2 days, I was using the older nano wallet, so I updated to the new one and tried the .html and it's still incorrect.
![screenshot-2017-12-21 dashboard nano wallet](https://user-images.githubusercontent.com/34754874/34276936-45622c20-e669-11e7-8109-a6fca69f9f78.png)

if it warrants a bounty, my address is:  NCTJ5H-CJB755-AX3M4S-4FOURA-62WJWL-QPWNS7-PXL7

**Comment by QuantumMechanics** [comment]
Hi,

I checked and see no problem. Nano shows exactly what is displayed by Poloniex
