### ISSUE TITLE
all my NEM disappeared from wallet

### ISSUE THREAD

**Issue by Fdour1975** [NemProject/NanoWallet#386]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used
Windows 10, Chrome
## Expected Behavior

Should have 500 NEM in my wallet
## Current Behavior

When I loggued into my wallet just now I dont see any credit left, all my 500 NEM disappeared !
## Possible Solution

No idea 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Deanscanlon1** [comment]
Mine too 10,000!!!

**Comment by Fdour1975** [comment]
no way !???? hacked ???

**Comment by Deanscanlon1** [comment]
Hoping its a glitch?

**Comment by QuantumMechanics** [comment]
Hi,

Read the FAQ in wallet and change the node

**Comment by Deanscanlon1** [comment]
ALL SET 
THANK YOU FOR YOUR QUICK RESPONSE
