### ISSUE TITLE
my 10,150 XEM has dissappeared from my wallet!

### ISSUE THREAD

**Issue by Deanscanlon1** [NemProject/NanoWallet#387]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

Try to change the node please

**Comment by Deanscanlon1** [comment]
I can’t find FAQs

**Comment by Deanscanlon1** [comment]
Got it 
Thank you 
THANK YOU!!!
