### ISSUE TITLE
Enhancement Request: Node Cicrle Color

### ISSUE THREAD

**Issue by roleerob** [NemProject/NanoWallet#389]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

Using Nano Wallet 2.0.14 on Windows 10.  Open wallet from launching NanoWallet.exe, so have never been clear as to what browser is behind the screen which comes up.. I have both Edge and Chrome on my computer, with Edge as the default.

## Expected Behavior

First, let me clearly state that Nano Wallet is apparently working as expected. 

## Current Behavior

Being new to Nano Wallet, I had read that I should be sure the "Node Circle" was not red.  Well, as far as I could tell it was not red.  However, it turned out it was not green either (read detail below).

Even after determining the cause of my problem, it is still difficult to clearly see the "Node Circle" is now green.  Looks dark and could be dark gray, black, maybe even dark blue, as well as green ...

## Possible Solution

1st Enhancement Request:  At a minimum, please consider ways to make the "Node Circle" color more obvious.  Most obvious to me would be to make it a filled ball, rather than a thinly-lined circle, but I'll leave that up to you.

2nd Enhancement Request:  As an additional consideration, perhaps upon starting up the best available node could be determined programmatically and set for the user?

## Steps to Reproduce

1.
2.
3.
4.

## Details

My very first transaction in my newly installed Nano Wallet did not go through (transferring XEM from Bittrex into my wallet).  Turns out, after going to the NEM forum for help, that it was my node that was not working.  Very difficult to tell that, so needlessly both held up myself, as well as taking up someone else's valuable time, when shouldn't have been necessary.

**Comment by mizunashi** [comment]
1. There are various opinions about color.
Especially people with color weakness, etc. I think that it is quite frustrating.
In Japanese games, you can use the settings adjusted for color blind people.
Even at NanoWallet, like the opinion of you, I think that it is necessary to paint the circle and have an intuitive color scheme.

2. Currently, because nodes are green, situations sometimes can not be said that there is absolutely no problem.
I think that we are currently adjusting on the development side.

Thank you for valuable opinion.

**Comment by QuantumMechanics** [comment]
Hi,

1) Circle and color are now more visible https://github.com/NemProject/NanoWallet/commit/b96323ca5b9f5f0289c08c9306e64e1fcfbe886a
2) Nano is already trying to fetch the closest node possible but many things can affect the node quality and it is not easy to test.

Thanks for your suggestions
