### ISSUE TITLE
i sent xem to wrong adress

### ISSUE THREAD

**Issue by hoss12** [NemProject/NanoWallet#390]
From Primary
To NBRT3Y-QTVHLT-YBDUXH-2HHURI-5KCYDW-RWJ63Y-WIGG
Amount29.000000 XEM
Fee 0.100000 XEM
Message housshouss
Block 1431336
Hash 1428e14d40dac48602f92b87b7e5043512bfe1894d680a957a9f0a05521e5eab

**Comment by QuantumMechanics** [comment]
Hi,

We can't do anything about it. Only way to get your XEM back is to contact the recipient NBRT3Y-QTVHLT-YBDUXH-2HHURI-5KCYDW-RWJ63Y-WIGG and ask for a return.

**Comment by hoss12** [comment]
---------- Original Message ----------

**Comment by QuantumMechanics** [comment]
The details you posted says:

> From Primary
> To NBRT3Y-QTVHLT-YBDUXH-2HHURI-5KCYDW-RWJ63Y-WIGG

It means that you sent from the primary account of NanoWallet **to** NBRT3Y-QTVHLT-YBDUXH-2HHURI-5KCYDW-RWJ63Y-WIGG.

If you own NBRT3Y-QTVHLT-YBDUXH-2HHURI-5KCYDW-RWJ63Y-WIGG then make sure to be logged into this account

**Comment by mizunashi** [comment]
NBRT3Y-QTVHLT-YBDUXH-2HHURI-5KCYDW-RWJ63Y-WIGG is Yobit exchange address.

**Comment by hoss12** [comment]
There is no reciepian for that address it is exchange yobit address I sent from yobit to my xem wallet than I replayed 29 cam to it by accident. Thank you anyway for the replays
