### ISSUE TITLE
Hardcoded english word "in" on several places in MarketInfo section of NanoWallet 2.x

### ISSUE THREAD

**Issue by roundminer** [NemProject/NanoWallet#393]
There are hardcoded english words "in" appearing in MarketInfo section of NanowWallet 2.x 

## Expected Behavior
It shouldn't be visible in other languages

## Current Behavior
Whatever language you choose, there is always this english word "in" within MarketInfo before selected market currency.

## Possible Solution
I have already posted a solution in Pull request #392

## Steps to Reproduce
1. Log into wallet
2. Go to dashboard and wait for Market Info section to be populated
3. Choose any other language
4. See "in" words in any other language

## Details
Tested on Windows 10 platform
Chrome Version 63.0.3239.108 (Official Build) (64-bit)

NEM bounty/donation address:
NCIG52B3J4MSSCDAY4JIUSPUUMMKDIWLYAYAPVQZ

**Comment by mizunashi** [comment]
@QuantumMechanics 
I think that it is a demand for localization.

**Comment by roundminer** [comment]
No need to change localization files, I have already posted fix in pull request (linked here under "Possible Solution"), which uses brackets and is compatible with all translations.

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: 36c0dfa4e2d5a3c1375e0f14481898b81df6c491ad8977ecc3561ed8cd66c9db

**Comment by TonyCrypto** [comment]
#136  Is related, need to be closed as well.  @fyahfox @QuantumMechanics
