### ISSUE TITLE
Enhancement Request: Cold wallet support

### ISSUE THREAD

**Issue by yaaccount** [NemProject/NanoWallet#394]
## Details
It would be really cool to have this:

https://forum.nem.io/t/nem-hot-cold-wallet-the-first-ever-nem-cold-offline-wallet-you-can-use-to-send-and-receive-funds

directly in nano. You only need a camera on your devices for this to work.

1) Don't store private key in NanoWallet at all. Use just public address to obtain account information.
2) Generate unsigned transaction in Nano, export it (QR as a first of possibly more modules implementing tximport/txexport interface)
3) Import signed transaction (again, QR module for now)
4) Let nano broadcast the signed transaction

I would even participate in a fundraiser to have this feature.

Edit: I believe (without looking at the code) that you already have to have most of the functionality already implemented for Trezor support, right?

**Comment by moderndust** [comment]
Hello, yesterday I took my wallet offline from NEM (XEM) to Bittrex, however I made a mistake and ended up putting the wrong message, only the address of the wallet was correct, I would very much like the help of someone who can solve this problem , thank you...
