### ISSUE TITLE
No funds received from exchange on Alfacashier

### ISSUE THREAD

**Issue by ANON0405** [NemProject/NanoWallet#396]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

I don't know Alfacashier, make sure that the payment has been sent from them.

Also, check if you are connected to a node in Nano, circle next to `Node` in navbar should be green.
