### ISSUE TITLE
funds not recieved in nem wallet

### ISSUE THREAD

**Issue by Mark00001** [NemProject/NanoWallet#397]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior
 funds deposited after being unconfirmed

## Current Behavior
 unconfirmed deposit has dispapeared

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mizunashi** [comment]
Please access the node menu and select a different node from the pull down menu.

**Comment by Mark00001** [comment]
ok wich node?

**Comment by mizunashi** [comment]
Please change to various other than the current node.

**Comment by Mark00001** [comment]
ok it is in my wallet now, with a different node, could you please take a moment and explain to me how that works?

**Comment by Mark00001** [comment]
ok

**Comment by Mark00001** [comment]
thanks for the quick response, still trying to get used to this wallet

**Comment by mizunashi** [comment]
In general, there is no problem if the node has a green circle.
However, when the load of the node is high, or the chains may not be synchronized.
In that case, the only solution is to change the current node.

**Comment by Mark00001** [comment]
and changing the node has no affect on my address or depositing / withdrawing?

**Comment by mizunashi** [comment]
No problem. You can choose any node.
Even if you withdrew money from a chain that branched from the original chain, you will not have withdrawal.

**Comment by Mark00001** [comment]
thanks for the help
