### ISSUE TITLE
Missing Receive Button on Windows

### ISSUE THREAD

**Issue by FastandBulbous** [NemProject/NanoWallet#401]
The Receive tab that used to be visible from the Send menu item is no longer visible
It is therefore not possible to send xem to a new wallet created with v2.0.14 Beta

- [ ] **DO** describe operating system and browser used
Windows 10

## Expected Behavior
<Receive function should be accessible from GUI

## Current Behavior
<Send page has only Send and not Send & Receive

## Possible Solution
<Restore Receive function

## Steps to Reproduce

1. Download current version of NanoWallet to a Windows machine
2. Create a new account (Sign up)
3. Try to obtain an address to receive funds

**Comment by ghost** [comment]
Same issue on Linux wallet too.

**Comment by bobboris** [comment]
ALso found no receive botton on mac. Not finding the receive botton and being new to the wallet I sent money to the address displayed in the account tab, but it hasn't come through, although the transaction is visible in the block tracker. 

http://explorer.ournem.com/#/s_account?account=NBFMY4-ZUTNER-MX3U5J-LN6I3U-RIHOA4-HM43HW-POWB

**Comment by QuantumMechanics** [comment]
Hi,

The receive button have been removed in 2.0. I will add a dedicated module.

The account address can be found in the `Account` module by clicking `Account` in the navbar

**Comment by imkane** [comment]
The Guide needs to be updated ;)
