### ISSUE TITLE
Send option under Create Mosaic button not working in wallet v 2.0.14

### ISSUE THREAD

**Issue by ghost** [NemProject/NanoWallet#402]
Before submitting your issue, please review the following checklist:

## Expected Behavior
Mosaic should be created upon populating all fields for creating mosaic and namespace being available but send button is unclickable.

## Current Behavior
Cannot click on the send button under create mosaic after populating all fields.

## Possible Solution
UX GUI error needs to be recitified.

## Steps to Reproduce

1. Create Name space or ensure a namespace exists
2. Go to create mosaic.
3. Populate all fields
4. Send button is not clickable.

**Comment by tongokongo** [comment]
2.0.14 Windows/Chrome. Works for me, maybe write something in the "description" field. It is less visible than other fields...

**Comment by ghost** [comment]
this issue can be closed , doesnt seem to happen after restarting the wallet.
