### ISSUE TITLE
Wrong exponent in importance score

### ISSUE THREAD

**Issue by Folindril** [NemProject/NanoWallet#403]
## Details
I'm using Windows 64bit version.
Importance score in NanoWallet is shown like 0.1391 * 10(-4).
But on other resources like http://chain.nem.ninja you can see 0.1391 * 10(-5).
The value shown in NanoWallet is 10 times higher.

**Comment by QuantumMechanics** [comment]
Hi, 

It was `* 10(-5)` before but got asked in telegram tech to change for `* 10(-4)`.

I think that  http://chain.nem.ninja is wrong.
