### ISSUE TITLE
Deposit to HitBTC not showing

### ISSUE THREAD

**Issue by yeti1444** [NemProject/NanoWallet#405]
Made two deposits 36 hours ago of XEM and the transaction still does not show in any way on HitBTC. My funds are gone from the NanoWallet and it said success. Could there just be a backlog? What do red instead of green arrows mean from the NanoWallet?Appreciate any guidance.

**Comment by QuantumMechanics** [comment]
Hi,

If the transaction shows in `confirmed` then it has reached HitBTC but they have not credited you. 

>  What do red instead of green arrows mean from the NanoWallet?

Red arrow = Outgoing
Green arrow = Incoming

**Comment by yeti1444** [comment]
Thank you!
