### ISSUE TITLE
Windows app data directory?

### ISSUE THREAD

**Issue by imkane** [NemProject/NanoWallet#406]
Is there any way to specify the data directory, perhaps with a command-line param?

**Comment by QuantumMechanics** [comment]
Hi,

There is no use of app data directory. Nano has no access to folders and files in your computer. It is only limited to browser scope

**Comment by imkane** [comment]
But the folder your app is running in is >200 MB ;)

Is that just all program files?

**Comment by QuantumMechanics** [comment]
Windows app comes packaged with chrome browser directly so it is quite big. 

You can use the universal version that is ~6MB and contains only the app.
