### ISSUE TITLE
2.0.14 distro hasn't index.html file

### ISSUE THREAD

**Issue by alexey2baranov** [NemProject/NanoWallet#408]
## Expected Behavior
I would like to see index.html file  into NanoWallet distro https://github.com/NemProject/NanoWallet/releases/download/2.0.14/NanoWallet-2.0.14-linux64.zip

## Current Behavior
There is no index.html file

## Possible Solution
Looks like manual should be updated

## Steps to Reproduce
1. download https://github.com/NemProject/NanoWallet/releases/download/2.0.14/NanoWallet-2.0.14-linux64.zip
2. extract arch

## Details
debian x 64

**Comment by mizunashi** [comment]
I do not know because I have never used it on Linux, but it should be distributed in an executable format.
Please execute the nanowallet directly in the directory.

Example:
$ ./NanoWallet
 or
double click in Finder?

**Comment by QuantumMechanics** [comment]
Hi, 

To start the app on Linux you must open a console pointing to the NanoWallet directory and type `./NanoWallet`

Will add more precise documentation in future versions
