### ISSUE TITLE
Sent funds leave wallet but do not appear on the blockchain

### ISSUE THREAD

**Issue by sandstep17** [NemProject/NanoWallet#409]
- [ ] **DO** describe operating system and browser used. Windows 10 & Chrome Version 63.0.3239.84 (Official Build) (64-bit)

## Expected Behavior
Funds should transfer

## Current Behavior
The Funds have left my wallet but not appeared at receiving address. I can't find the transaction on the blockchain with NEM Explorer

## Possible Solution

Return the funds to the wallet and advise on how to achieve the transfer

## Details
Here are the from and to addresses and the hash

 NAFQ7J-3FHJG4-MWY4CT-X7IP3D-S732GK-ZPSNNF-E7I5	- 3 108.050000 XEM		Fri, 05 Jan 2018 14:58:31 GMT
Transfer transaction
From NB4W3I-PKGPBO-UJ2NYL-BRDQPK-DM5XXW-JW6N25-ATUB
To NAFQ7J-3FHJG4-MWY4CT-X7IP3D-S732GK-ZPSNNF-E7I5
Amount3 108.000000 XEM
Fee 0.050000 XEM
Block 1434329
Hash 1bf8442d19be9f7283bc03673d2af27c8ecbd7e5c3e9ea9a585b430c180eb540

Thank you for your time... Pete

**Comment by mizunashi** [comment]
Suppose this Transaction hash is correct.
Currently this transaction is not on the block chain.
In this case, I think that there was no trading in one day and the funds are back.
(To be exact, it means that the transaction did not exist)
Would you please check again, balance?
Thank you.

**Comment by sandstep17** [comment]
Thank you, mizunashi: The wallet now shows the balance and the spurious transaction has gone. I appreciate you spending time on this issue. best regards... Peter
