### ISSUE TITLE
 Are there plans for multilingualization of the welcome document?

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#41]
The following documents contain very important contents. Are there plans for multilingualization?
Currently, it can not be replaced with a language file.
By the way, Japanese tend to ignore everything if there is English.

![2017-04-03 12 16 15](https://cloud.githubusercontent.com/assets/1645189/24594403/cba0eb58-1867-11e7-9396-c96e266ef1d2.png)

**Comment by QuantumMechanics** [comment]
Added https://github.com/NemProject/NanoWallet/commit/15dcf5cd8ebf2420415be39dd34ae0542e1d7bc1
