### ISSUE TITLE
XEM didnt get sent from cryptopia to nano

### ISSUE THREAD

**Issue by productive324rq12** [NemProject/NanoWallet#412]
XEM didnt get sent even after confirmed. XEM developers checked and cryyptopia has not sent it out, would you be able to push forward my last withdrawl?

It was between cryptopia and nanowallet.

  | Complete | a2a101a4b1c286448fa899114b4ab3d60d08d332f5af454a60c4148292ccc461 | NAYW2C-I7ARXP-THUWWG-5EBV7A-ABKI5Y-OOKOV4-SDQH:NAYW2C-I7ARXP-THUWWG-5EBV7A-ABKI5Y-OOKOV4-SDQH | 6/01/2018 11:30:00 PM
-- | -- | -- | -- | --

**Comment by mizunashi** [comment]
Deposit transactions are not recorded on the block chain.

Also, I can not understand the meaning of this table for a moment, is not there a thing that the source of withdrawal and the destination of payment are the same?
Please confirm once.
  
![2018-01-09 3 13 40](https://user-images.githubusercontent.com/1645189/34685260-23a3d652-f4eb-11e7-8609-6ef63e7dc471.png)

**Comment by QuantumMechanics** [comment]
Hi,

We can't do anything, you must contact the exchange.

The transaction hash does not point to any transaction on the chain explorer http://chain.nem.ninja/#/search/a2a101a4b1c286448fa899114b4ab3d60d08d332f5af454a60c4148292ccc461
