### ISSUE TITLE
Forgot to place message upon sending XEM

### ISSUE THREAD

**Issue by elt0nskie** [NemProject/NanoWallet#413]
Hi Support,

Good day!

Is there any way for us to retrieve what I have sent yesterday? Because I forgot to place the message upon sending XEM, I am just new in cryto currency and I believe I did it wrong when I send the XEM without the message. Below are the details sent yesterday

Transfer transaction
From; NCBF4M-BYSVOD-6QW5O2-JYVSFX-3X5RQC-VV7BT2-YRIX
To: NC2DF4-NGCE6W-NVTJR4-377NNF-X2W5P4-BEN3FI-KWCV
Amount; 84.000000 XEM
Fee; 0.050000 XEM
Block; 1447848
Hash; 3d0950049b62e7652d9922dde9e1f38456ce88bbc76f0c6f81a10cc5748d6a81

please please help me what to do.

Looking forward for your help and thank you in advance.

Regards,
Eltonskie

**Comment by mizunashi** [comment]
There is a message that needs to be entered on the deposit screen of the exchange.
Please contact the exchange support with Transaction hash and the messege displayed on the exchange.

**Comment by elt0nskie** [comment]
hi Mizunashi,

we have to re-open this case because after talking to the exchange they are asking for this:

need to provide a proof of the confirmation from the wallet you sent the transaction from, stating that the reversed transaction will indeed be refunded back to your account there (even when it's reversed without the message, as originally sent to spectrocoin)

is it possible for your team to provide this?

Thank you

Regards,
Elton

**Comment by mizunashi** [comment]
@elt0nskie 

I do not know what type of request is wearing, but I think that it would be nice to send a screenshot of NanoWallet etc during remittance.

We can not provide information here.
Only the principal can report to the last.

Thanks
