### ISSUE TITLE
Sent 40 XEM from Nanowallet to Bittrex but not received in Bittrex yet

### ISSUE THREAD

**Issue by Roozbit** [NemProject/NanoWallet#414]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details

I sent small amount of XEM from my NanoWallet to Bittrex, it shows confirmed in NanoWallet but not received in Bittrex. 
<img width="915" alt="screen shot 2018-01-07 at 3 59 06 pm" src="https://user-images.githubusercontent.com/35196456/34651124-cf5b32de-f3c3-11e7-88f7-cab5f943faaa.png">

**Comment by mizunashi** [comment]
message is test.
It is necessary to put the message specified by Bittrex here.
There is that message on Bittrex's deposit screen.
Please contact Bittrex support for the messege displayed in Transaction hash and Bittrex.
