### ISSUE TITLE
The Funds have left my wallet but not appeared at receiving address. 

### ISSUE THREAD

**Issue by danicrip** [NemProject/NanoWallet#415]
W7 64 bits

I did withdrawal funds to my nanowallet, but the founds have left my wallet and not appeared in my receiving addres.  
Also I can't find the transaction on the blockchain with NEM Explorer

I asked to my exchange for this problem, and they tell me that is all Ok. The withdrawal is completed.

Can you help me?

## Details
Identificador TX: 18cfcf375a8bb555a669b3ebbf2bcca22e54010f05eeee6a63437e6622652c76
Withdrawal ID: CWCA4ZDACL0GYYVY61ROHHLX8K
Address: NA26PLS6F2J522PZ4AHMDKQZQFHZJZURA3HR3VQQ

**Comment by QuantumMechanics** [comment]
Hi,

I can't find the transaction in the explorer too.. It means the funds never left the exchange. 

Contact them and insist that it is not on the explorer http://chain.nem.ninja/#/search/18cfcf375a8bb555a669b3ebbf2bcca22e54010f05eeee6a63437e6622652c76
