### ISSUE TITLE
BUG: Changefly instant exchange in NEM wallet doesnt work

### ISSUE THREAD

**Issue by Dmatafonov** [NemProject/NanoWallet#416]
If you open **services**->**instant exchanges**->**Buy XEM on changefly** you'll find out that it:

- offers to buy ETH for BTC
- doesnt work even for ETH/BTC or any other currency
- does not have XEM!

![1](https://user-images.githubusercontent.com/8863854/34661943-0be508ac-f45e-11e7-9bd7-acc5d4fea739.gif)

Why put such 'exchanges' to the official wallet?

Developers bughunt bounty: NDNRSW-FEQ256-HQLUYT-L6SOS3-RYHEJK-BLOWL2-C6MJ

**Comment by QuantumMechanics** [comment]
Hi,

We have no control on exchange widgets. It is just a link with our merchant id to put in the page. 

Changelly seems to have some trouble to maintain it stable
