### ISSUE TITLE
does not send funds

### ISSUE THREAD

**Issue by jesse2985** [NemProject/NanoWallet#419]
## Expected Behavior
XEM should be sent to the desired address

## Current Behavior
i enter the address and the message, and when i click send it pops up saying transaction successfully sent but nothing happens.
nothing is deducted from my wallet, nothing appears in confirmed or unconfirmed.

## Possible Solution
make it work

## Steps to Reproduce

1. enter adress
2. enter message 
3. click send
4. follow trezor instructions

## Details
i have tried several times to send XEM out of my nano wallet.
nothing is deducted from my wallet, nothing appears in confirmed or unconfirmed.

i have previously sent xem a number of times with no problems at all. 

thanks
jesse

**Comment by QuantumMechanics** [comment]
Hi,

The app is working as it should. 

Recently some nodes stopped sending web-socket messages, so the app don't receive notifications after transactions... I have no control on that :/

> nothing is deducted from my wallet, nothing appears in confirmed or unconfirmed.

Every transaction have been sent if the app says `Transaction successfully sent`, unless the node was on a fork.

Try to change the node via `Node` in the navbar and it will be fixed.
