### ISSUE TITLE
Forgot to add Message

### ISSUE THREAD

**Issue by MV5648** [NemProject/NanoWallet#420]
Tried sending XEM from NanoWallet to XEM wallet at spectrocoin, but forgot to add the message.  XEM was withdrawn from my NanoWallet but not added to my XEM spectrocoin wallet.  Not really sure what to do.  See below for details.  It's not a lot of money, but enough.  Hope someone can assist.  Thanks.

From Primary
To NDIGV7-FUKZWT-XNERTF-RPKBCZ-LCDUUE-5HJVQH-TJQZ
Amount221.000000 XEM
Fee 0.050000 XEM
Block 1451639
Hash 22d9f66b57ce3080e0f493f9a6d4ea0fe78f81fea595d50473678aafc3ab362c

**Comment by QuantumMechanics** [comment]
Hi,

You must contact spectroin support and provide them the transaction details

**Comment by MV5648** [comment]
Could you please let me know which exchange support and their contact information that I must contact.  I'm sorry, but I am very new at this.  Thank you.

**Comment by mizunashi** [comment]
This is a place to report a bug about NanoWallet.
Please visit https://forum.nem.io/c/tech-support to create a new topic and ask questions for this case.
If you do not have an account, please create it.

Thank you.

**Comment by MV5648** [comment]
Thank you.
