### ISSUE TITLE
Trezor Receive Address

### ISSUE THREAD

**Issue by pointtoken** [NemProject/NanoWallet#421]
No receive address appears in ui. Repo steps:

1. Log in with trezor 
2. Go to Dashboard and no receive address appears 

(unlike the screenshot in the blog post: https://blog.trezor.io/announcement-trezor-integration-nanowallet-nem-xem-cryptocurrency-feature-803e7ffbf023

**Comment by mizunashi** [comment]
Did you try changing the NIS node?

**Comment by pointtoken** [comment]
Yes, if you mean the Node link up top. Regardless of the node I pick, I still never see my actual receive address even though it is exported from the trezor which I can see on the Trezor UI.

**Comment by mizunashi** [comment]
Until the dashboard is displayed from the login screen, it is in the same state as the procedure of this link, is not it?

Then, only the dashboard is not displayed well, and even if the node is changed, it does not change.
Is there any mistake in this content?

Would you tell me which OS and Version you are using, the version of the browser, and the firmware version of TREZOR?
We will continue to investigate.

**Comment by QuantumMechanics** [comment]
Hi,

> Go to Dashboard and no receive address appears

Your account address is not in `Dashboard` but in the `Account` module you can access from navbar.

**Comment by mizunashi** [comment]
I was mistaken.
The Recieve tag does not currently use TREZOR, regardless of whether it is used or not.
