### ISSUE TITLE
transfer problem

### ISSUE THREAD

**Issue by mnea** [NemProject/NanoWallet#422]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Possible Solution

i transfered to anoter account addres but not reached how can i solve the problem i need help
![tra](https://user-images.githubusercontent.com/34472328/34814289-2509dd0a-f6be-11e7-923f-d29e18333afd.PNG)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

If the transaction shows in confirmed then it should have reached the other account.

Try to change node from the `Node` button in the navbar. 

Maybe the node you are connected to is on a fork

**Comment by juergenbenning** [comment]
I have the same problem. Also from the Thu 11.Jan 2018. I checked the notes. The colour from the ring is green. What can I do?

![image](https://user-images.githubusercontent.com/35468587/34960805-c27fed28-fa3c-11e7-985a-0c69223cfa6e.png)
