### ISSUE TITLE
Transfer from source to target decreased.

### ISSUE THREAD

**Issue by yamaha9** [NemProject/NanoWallet#423]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used
MS windows , Googler chrome
## Expected Behavior

Transferred 20 XEM coins from poloniex exchange to my local wallet. And I should receive 20 XEMs in my wallet.

## Current Behavior

Wrong number of coins showing up in wallet. Transferred 20 XEM coins from poloniex . And in NEM wallet i see Amount 5.0  XEM and Fee 4.00 XEM. What happened to remaining XEM coins? 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

Poloniex total fee is 15 XEM. We have no control on that, exchanges can set the fee as they want
