### ISSUE TITLE
nanowallet 2.0.14 node bug

### ISSUE THREAD

**Issue by genus1** [NemProject/NanoWallet#425]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by genus1** [comment]
I posted this issue for weeks in different places and I believe even here someplace.

When harvesting with older version you could select your local IP node on another LAN computer.  This fails on version 14.  Same if you select node at the top and try custom node and set to local IP on NIS running on LAN, the node goes red then green with an arbitrary external node.  If you select a custom node using your external IP back into your local NIS, the node will accept and it will harvest.

I believe in the new version the configure your own node is only allowing external IP.

I have verified this with multiple tests.  I run the old version and it works, I run the new and it does not.  I can access my NIS with postman or check things like chain height using the local IP even though the nano wallet cannot see the local IP.

NCWLSN-V5KW53-U66ZRJ-G26SWN-UNGX4L-J5WN6V-EPMK

**Comment by yaaccount** [comment]
Created PR (#433), the original regex was most probably copy-pasted from somewhere (https://gist.github.com/dperini/729294) including private and local address filter

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: eb953576c307120e0af9c478921b3dc8f3c8addde3f115f304beb3a39f73ff5c
