### ISSUE TITLE
the transfer doesnt arrive after 2 weeks

### ISSUE THREAD

**Issue by abde23** [NemProject/NanoWallet#426]
[Before]([url](

> [url](url)

)) submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details

[](url)
![xem](https://user-images.githubusercontent.com/35443460/34928577-d4b94756-f9be-11e7-82a7-54de63dbf051.png)

**Comment by QuantumMechanics** [comment]
Hi, 

You sent to an exchange without message, contact their support

**Comment by abde23** [comment]
Hi,

what can i do to recover my xem??
can you send me the email adress for talk with my support?

thank you
________________________________
De: QuantumMechanics <notifications@github.com>
Enviado: lunes, 15 de enero de 2018 19:15
Para: NemProject/NanoWallet
Cc: abde23; Author
Asunto: Re: [NemProject/NanoWallet] the transfer doesnt arrive after 2 weeks (#426)


Hi,

You sent to an exchange without message, contact their support

**Comment by QuantumMechanics** [comment]
> what can i do to recover my xem??

You contact the exchange support, show them the transaction hash and tell them you forgot to add a message.

> can you send me the email adress for talk with my support?

No, you can find it on the exchange website
