### ISSUE TITLE
Error entering wallet

### ISSUE THREAD

**Issue by bolush23** [NemProject/NanoWallet#427]
Hello. I have a problem at the entrance to the purse, an error appears (see .screen)
Tell me what it means.

And just wanted to ask, I had 10163 xem on my wallet.
In the active balance passed 9506 units, and so it has been a couple of days. What to do?

![photo5395449792999565416](https://user-images.githubusercontent.com/35454456/34944618-8f3b214c-fa2a-11e7-8f7f-6c1c040468ff.jpg)

**Comment by QuantumMechanics** [comment]
Hi,

It seems this error is coming from the NIS you are connected to.

Try changing node and login again.

**Comment by bolush23** [comment]
and what about my active balance? i have 10163 xem, but my active balance stayed on 9506 a few days. The changing node will resolve this problem?
