### ISSUE TITLE
Transfer problems, even by changing node

### ISSUE THREAD

**Issue by Murtezas** [NemProject/NanoWallet#428]
My transfer has not reached the given adress. I've double checked everything, there ar no writing errors.
I've also changed my node but this has not helped.

![xem transfer problem](https://user-images.githubusercontent.com/33703427/34958267-63b8b85c-fa31-11e7-8362-da1011102048.JPG)

**Comment by QuantumMechanics** [comment]
Hi,

If you changed the node and the transaction is still showing in `confirmed` then it has reached the destination address.

If destination is an exchange you must contact them, show them your transaction details and tell them you have not been credited.
