### ISSUE TITLE
Withdraw does not work. 

### ISSUE THREAD

**Issue by juergenbenning** [NemProject/NanoWallet#429]
I wanted do do a withdraw, but i doesn´t work. see the picture. The node and network shows green colour. What can i do ??

![image](https://user-images.githubusercontent.com/35468587/34960860-0754ca7c-fa3d-11e7-829c-80be7c0464ab.png)

**Comment by QuantumMechanics** [comment]
Hi,

Need more details

Why the hexadecimal message ?

Did you sent to an exchange ?

**Comment by juergenbenning** [comment]
Hi
I sent to Cryptopia and there was the information that I need the hex message

Regards

Am 16.01.2018 um 22:14 schrieb QuantumMechanics <notifications@github.com<mailto:notifications@github.com>>:


Hi,

Need more details

Why the hexadecimal message ?

Did you sent to an exchange ?

**Comment by QuantumMechanics** [comment]
They probably ask for a message but certainly not to send it as an `hexadecimal message`.

The message itself is hexadecimal but it should be sent as a normal `unencrypted message` I guess.

Contact them, provide the transaction hash and tell them that you sent with a wrong message type
