### ISSUE TITLE
Calculation of the number of remaining characters is not a serialized length.

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#43]
In the case of English only messages, we confirmed that the number of characters and the number of line feeds can be sent up to 1024.

However, if you include Japanese (double-byte characters), NIS will return an error, since the number of characters is one character.

Regarding the fee, it is calculated from the length of the serialized character.

In order to support multiple languages, it seems necessary to consider the length of characters when serialized.

![2017-04-04 3 56 19](https://cloud.githubusercontent.com/assets/1645189/24627327/6f4ec414-18ef-11e7-961c-debfb98392ba.png)
![2017-04-04 3 58 30](https://cloud.githubusercontent.com/assets/1645189/24627335/782e55cc-18ef-11e7-9d15-a4d8921c3a5b.png)

**Comment by QuantumMechanics** [comment]
Hi, now it should show the right counter: https://github.com/NemProject/NanoWallet/commit/eb977ef5503282b6f9ae3d293b9ae8fc38faeebc

However there is still a bug with conversion to bytes as reported here: https://github.com/NemProject/NanoWallet/issues/17 that might cause problems. 

Tried different solutions but nothing that is working perfectly with every characters.
