### ISSUE TITLE
Address not valid when I try to by XEM

### ISSUE THREAD

**Issue by ssscsssc** [NemProject/NanoWallet#430]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used
Linux Debian Mozilla Firefox
## Expected Behavior

I should be able to buy XEM
## Current Behavior

It says address is not valid
## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

Need more details

**Comment by ssscsssc** [comment]
In Services-Changelly Instant Exchange I choose Buy XEM and then Pay with Euro, I put an amount and click on Exchange; then it appears a text saying Address is not valid

**Comment by QuantumMechanics** [comment]
We can't do anything regarding the Changelly exchange module.

> it appears a text saying Address is not valid

If you got this message then they have a problem or you are using NEM testnet.
