### ISSUE TITLE
I cannot delete an account I've added to the wallet

### ISSUE THREAD

**Issue by ssscsssc** [NemProject/NanoWallet#431]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used
Linux Debian 9 64bit, Mozilla Firefox 52.5.2
## Expected Behavior

It should be possible to remove an account that an user has added to the wallet
## Current Behavior

I don't see a way to remove the account
## Possible Solution

A Remove OR Delete Account buttom
## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

It is complicated, Nano is a full javascript application and therefore it cannot access the wallet file in your computer to edit it directly (browser security). 

If a user adds or deletes an account, only the wallet loaded in your browser is updated. The `.wlt` file on your computer doesn't change, so you have to download the updated wallet file at every update and that can be very confusing. 

For this reason I am limiting operations on wallets as much as possible.
