### ISSUE TITLE
NEM (XEM) TOKENS DIDNT REACH ADDRESS OR BOUNCED BACK TO MY NANOWALLET

### ISSUE THREAD

**Issue by adamsalfonso** [NemProject/NanoWallet#434]
Before submitting your issue, please review the following checklst:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used
Windows 10 

## Possible Solution
 Refund of my 5 XEM tokens

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

If recipient is an exchange then they did not processed your deposit and you must contact them.

Otherwise the node you are connected to may be on a fork and switching node via `Node` in the navbar should bring your XEM back.

If none of the above then provide more information please.
