### ISSUE TITLE
DIMCOIN can not be Deposit.

### ISSUE THREAD

**Issue by satoshi7nakamoto** [NemProject/NanoWallet#435]
I sent DIMCOIN to the HITBTC exchange.
The deposit address of DIMCOIN is correct.

But transaction processing will not be deposited even if it completes.
It has already been over a month.

How can I improve it?
The exchange named HITBTC will not respond to anything.
HITBTC was damaged by GOX?

This is part of my deposit.

https://p3.zdusercontent.com/attachment/1068942/QcLPX7Gl48bmSMrEIZxJsDdn4?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..oxILXKai-9eZTphXZv2bug.tuDmWrvs2L5jiuEOACk-nfswNgNmz_uUU_8C6D1y2kIPTt0iwVAos_U5HAFkV07QiR1wnQ9iAjm3ZMvmorE6EBIpIpHDe3nDoSS3gjfxoujeRj-TDlAhNWQszVJ3j-QKebI5YOZ3TPBlPsAr_ccWmm4jHOMvZ9d5FzjwNTZuWRX85WlsuYSqQFyb-kaTsijdTKE2TJ1C79N4LZKAgyXofGA8PU3z5xKlwpm2UqI3wXz1psEItIBmVQrw1AOKP25a0hnF_K7qcyvGGv1fxgiaJU4HbIDUx_3asQtNQKQGaY8.z3vMv9gluaaFsIfHs3NFIQ

**Comment by QuantumMechanics** [comment]
Hi,

If the transaction is confirmed then you must to contact HITBTC, there is nothing we can do.
