### ISSUE TITLE
Not user friendly

### ISSUE THREAD

**Issue by dpopp1** [NemProject/NanoWallet#438]
I understand that these applications are new and written by computer savvy people but.....this wallet is not user friendly. There is no recieve button, I cannot locate the coins I had sent to this wallet. I have read the FAQ to try to learn how to use this application and the first FAQ is how does Nano Wallet work? It starts explaining what computer language it uses, I don't care what language it uses or how it works just explain how to use the wallet! That should be at the "about NanoWallet". 

Tried watching a YT video and someone said you have to import a file in order to recieve coins. Really, can you make it more difficult for us to use? You understand that alot of people using the wallet are not computer programmers and don't like to mess around with .bat, .wlt, and whatever files that are needed to be inserted into the programs.  KISS(KEEP IT STUPID SIMPLE). I have enough to worry about with making sure I'm sending it to the right address and have the right amount.  

1.Remove unecessary complicated steps to set up wallet for the user.
2.Insert a Recieve menu where there address is there as other wallets have.
3. First FAQ should How to use the Wallet not How does Wallet work (that should be in the about Wallet)
4. Dashboard page with icons should be able to click on icon and go to the selected area of interest, has no value, just looks nice.

**Comment by QuantumMechanics** [comment]
Hi,

> Tried watching a YT video and someone said you have to import a file in order to recieve coins. Really, can you make it more difficult for us to use?

Nano is a full JavaScript application and therefore it is only limited to the browser scope. It cannot fetch the wallet file by itself in your computer or it would be way too insecure (any website you visit could use JavaScript to browse your computer and get everything they want).

> There is no recieve button, I cannot locate the coins I had sent to this wallet.

I don't understand why people have problems locating the `Account` button in the navigation top bar. It is used by almost every website and apps in the world, pretty obvious your account info is there..

> KISS(KEEP IT STUPID SIMPLE)

It is actually the simplest it can be in the limitations of a JavaScript application.

To answer your points :
1) There is nothing complicated in setting up a wallet, no installation and creating a wallet is a dumb step by step form..
2) It will be added in service later for invoices but not in send.
3) ..
4) Not sure about what you are talking about
