### ISSUE TITLE
good day i need help with havesting i paid the fee to havesting its say i need 10,000 xem vested i have 182.510378 XEM vested please help  

### ISSUE THREAD

**Issue by Jaymazzu** [NemProject/NanoWallet#439]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [x] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

You need at least 10'000 XEM in your account and have to wait until they are vested. It can take a bit if you only have 10'000 XEM
