### ISSUE TITLE
＊＊＊Translator's must-read＊＊＊   Keep the language file up-to-date

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#44]
With the upgrade to NanoWallet 1.3.0, additional modules and minor fixes, the number of items registered in the language file is increasing.

Translators of countries should supplement the additional part with reference to en.js.

In 1.3.0, labels that are no longer used and labels that have changed names also exist.

Additional items in the latest version are here en.js.
2e127faeba0cdb7254ffbb914b1d73ecfe5ba77b

Ultimately, I think that there is no mistake if English and national language files are the same on a row basis.

**Comment by mizunashi** [comment]
In order to eliminate the difference between each language file and English, English sentences are inserted in each language file.

Perform additional translation. Please give me a pull request.

**Comment by dgarcia360** [comment]
@mizunashi  I'll check it! I have done a pull request for spanish language a month ago. I'll compare files to see what it changed.

**Comment by arthur-c** [comment]
Hi,
I started a french translation for the nano wallet, coming soon.

**Comment by janmannl** [comment]
My pull request was accepted that sets english as the default language, eliminating the annoying capitalized _ strings if a sentence / word was not translated. 

https://github.com/NemProject/NanoWallet/commit/8398c13b15b83e7cf61eef8c73cfc046497c2f4c
