### ISSUE TITLE
Shapeshift didn't work, contacted Shapeshift but they asked for transaction ID....how can I find the transaction ID?

### ISSUE THREAD

**Issue by BenOngNEM** [NemProject/NanoWallet#440]
Shapeshift help desk asked me for transaction ID 

5 Jan 2018 
I transacted to change 20.31580867 LTC to XEM

Until now I still have not received the XEM because 

Shape shift acknowledge to have received the LTC but could not complete the transaction because the transfer is too late

Shape Shift is asking me for transaction ID in order for the LTC to be refunded

I cannot find the Shape Shift order ID in the NEM wallet

Questions:
- **How do I retrieve Shape Shift request history in NEM Wallet?** There has to be the ability to do this just in case something like this happen so NEM Nano wallet user is able to retrieve all information

PLEASE HELP, my LTC stuck in Shape Shift

<img width="960" alt="nem wallet shape shift service" src="https://user-images.githubusercontent.com/35854814/35465284-ffaddbf4-034e-11e8-9730-b5860bb7427d.png">
<img width="960" alt="nem wallet shape shift service2" src="https://user-images.githubusercontent.com/35854814/35465285-ffef9a08-034e-11e8-8c34-ff49e5bab118.png">

**Comment by QuantumMechanics** [comment]
Hi,

> I cannot find the Shape Shift order ID in the NEM wallet

Since you have sent LTC for NEM, there is nothing you can find in our wallet.

The transaction ID sounds like the hash of the transaction on the LTC blockchain. 

https://shapeshift.zendesk.com/hc/en-us/articles/206770710-What-is-the-TXID-or-Hash-
