### ISSUE TITLE
Key display screen should specify encoding

### ISSUE THREAD

**Issue by mattrixman** [NemProject/NanoWallet#442]
I recently generated a wallet, and I plan to stamp my key onto metal strips so that the backup will be durable (and will survive things like a house fire).  I have stamps for a-zA-Z0-9, so I plan to back the key up in Base58

The key display screen shows me what I have to assume is hexadecimal, but it doesn't explicitly say so.  Suppose I was wrong, and it was actually Base32, and by coincidence the only letters that appeared were a-f.  In this case, I would encode the key incorrectly.  Years later, I when I used the wrong key to recover the wallet, I would wind up with the wrong key and be unable to access to my funds.

I admit that this is a very unlikely case, but I think that being explicit about how the key is represented will increase user awareness and prevent weird people like me from making costly mistakes.

**Comment by QuantumMechanics** [comment]
Hi,

The private key is hexadecimal, no real need to specify but I will consider adding a note. 

Someone that know how to encode a key must be able to see that ^^

Regarding the wallet file (`.wlt`) it contains your wallet data in base64 and your private keys in it are encrypted with the password you have chosen during creation.

It is your responsibility to always make sure that the wallet you backed up is working before deleting anything on your computer. Also, always keep multiple backups of the `.wlt` file and private key **offline**.
