### ISSUE TITLE
Delay eight days!

### ISSUE THREAD

**Issue by PANACUMREI** [NemProject/NanoWallet#444]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details

Hello people,
I made a transfer on January 22 and until now the coins have not arrived in the wallet, I'm desperate !!! Is it normal to take this much time?

**Comment by QuantumMechanics** [comment]
Hi,

If you have made a transfer from an exchange to Nano, you must contact the exchange because the XEM probably never left their wallet.
