### ISSUE TITLE
Transfer NEM from wallet to poloniex not reach MISSING PLEASE HELP

### ISSUE THREAD

**Issue by Pankaj130513** [NemProject/NanoWallet#446]
Transfer transaction
From NDLJQF-GKMSTL-JYG7ID-FMNGW7-AAEDSS-DDZKRH-KF6W
To NBZMQO-7ZPBYN-BDUR7F-75MAKA-2S3DHD-CIFG77-5N3D
Amount9.000000 XEM
Fee 0.100000 XEM
Message 2419d90ac0a9bae0
Block 1454025
Hash d82bb95d6a7ffd47cdf967f1d5052589cb92076b71eb983771fafdbdfbb440c8

**Comment by QuantumMechanics** [comment]
Hi,

The hash of your transaction doesn't point to any existing transaction on the chain: http://chain.nem.ninja/#/search/d82bb95d6a7ffd47cdf967f1d5052589cb92076b71eb983771fafdbdfbb440c8

Try to change the node, maybe the one your are connected to is on a fork. 

If you were on the fork the transaction will disapear from the `confirmed` tab once you change the node

**Comment by Pankaj130513** [comment]
Hi team,

I am using desktom NEW official wallet. Please suggest step how can i
change node as i am new to blockchain.

Thank you,
Regards,
Pankaj

**Comment by QuantumMechanics** [comment]
In the top navigation bar you have a `Node` button with a colored circle next to it. 

This button open the node selection window, there you can choose a node
