### ISSUE TITLE
Mistake convert an account to multisig please help

### ISSUE THREAD

**Issue by ASAT668** [NemProject/NanoWallet#447]
when convert an account to multisig I made mistake POLONIEX XEM deposit adresse to
  +ADD cosingatory.
 I can't withdraw
becose I can't Log in cosingatory account.
Please help!!
BLOCK 14080325

**Comment by QuantumMechanics** [comment]
Hi,

You must contact Poloniex and ask them to remove their address from the cosignatories.

**Comment by ASAT668** [comment]
Thank you very much. I will contact POLONIEX. 
Please wait a little. I will contact you again.
Takamasa Asahi


Windows 10 版のメールから送信

差出人: QuantumMechanics
送信日時: 2018年2月3日 3:12
宛先: NemProject/NanoWallet
CC: ASAT668; Author
件名: Re: [NemProject/NanoWallet] Mistake convert an account to multisig please help (#447)

Hi,
You must contact Poloniex and ask them to remove their address from the cosignatories.

**Comment by ASAT668** [comment]
NANOWALLET In the case of deletion of multi-site consultant, after inquiring POLONIEX, more than two weeks passed, but there is no reply yet.
Please wait for a while. I'm sorry.

I have a question,

Is there any way other than having POLONIEX remove the address from the list of consignees?

If not deleted, will I lose my wallet XEM?

It is bad that I made a mistake, but if I lose my wallet XEM, I am in great trouble.
Please cooperate. Please help me!

Windows 10 版のメールから送信

差出人: QuantumMechanics
送信日時: 2018年2月3日 3:12
宛先: NemProject/NanoWallet
CC: ASAT668; Author
件名: Re: [NemProject/NanoWallet] Mistake convert an account to multisig please help (#447)

Hi,
You must contact Poloniex and ask them to remove their address from the cosignatories.
