### ISSUE TITLE
Can't Generate An Address to Send NEM To (Trezor)

### ISSUE THREAD

**Issue by MelbourneDeveloper** [NemProject/NanoWallet#448]
I am using Nanowallet on Windows 10 with Trezor. 

## Expected Behavior
Generate an address to send NEM to.

## Current Behavior
There is no option to receive NEM

## Possible Solution
Add a "Receive" button next to the "Send" button.

## Steps to Reproduce
1. Open the app
2. Go to the Trezor Wallet

## Details
I can't generate an address so I can't send NEM to myself.

**Comment by QuantumMechanics** [comment]
Hi,

Nano don't have a send/receive model. If you want to consult your account details (address, etc..) you have to click on the `Account` button in the top navigation bar
