### ISSUE TITLE
To: QM, it seems that the public version is going to be late, so I want to work. OK?

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#45]
It is a situation where the part of multi language is not even left in English and non-Japanese releases.

· Introduction and modification of Spanish (modified in consideration of pull request)
· Fixed Chinese
· Modification of Polish (modified taking pull request into account)

Or should I change all languages ​​from Master?

Because there are many additional tags in English, I plan to correspond to languages ​​other than Japanese in English.

Are you sure you want to do this?

**Comment by QuantumMechanics** [comment]
I usually add the new additions (in English) to the other languages files but I forgot for the last update

Added missing entries in Chinese and Polish: https://github.com/NemProject/NanoWallet/commit/1b6709130b7d9daa7a025b2f7dee8e2b83a1178c

Feel free to pull request

**Comment by mizunashi** [comment]
It is already over what I was about to do. lol
OK. Wait for reflection on Master.

Furthermore, there is a request that I want you to make it in Japanese in a fixed part in English.
The place is the light blue part below.

![2017-04-05 3 04 19](https://cloud.githubusercontent.com/assets/1645189/24683627/3965b1a4-19db-11e7-82c9-77186af1c610.png)


In these, we have to label a part of the program change and all the languages, but I would like to make changes as soon as that work is done.

**Comment by QuantumMechanics** [comment]
Done https://github.com/NemProject/NanoWallet/commit/650090360770d503e916354e089f289c505831ca

**Comment by mizunashi** [comment]
It is too early! lol
