### ISSUE TITLE
Missing transfer from NEM Nano Wallet to Huobi Exchange

### ISSUE THREAD

**Issue by supreme7coin** [NemProject/NanoWallet#450]
I recently transfere a large amount of XEM from my nano wallet to Huobi exchange however, the transaction is not yet showing up on the exchange even though it has been confired on my wallet end. Can anyone help....Please!

**Comment by QuantumMechanics** [comment]
Hi, 

A notice on Huobi exchange is saying that deposits are halted. You must contact them for details.

**Comment by supreme7coin** [comment]
Hey, 

Many thanks for your response. I have scoured the site and have not seen anything about delays on deposits however I have contacted them via email in the meantime so hopefully they can put me at ease. This information you have provided has also helped calm the nerves so thanks again (Y)
