### ISSUE TITLE
NEM to Poloniex not confirmed: I sent NEM to Poloniex and i can see it in my account of Poloniex, but I can also see that there is not one confirmation. What can be the problem?

### ISSUE THREAD

**Issue by Errrwin** [NemProject/NanoWallet#451]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

If you see the deposit as unconfirmed in Poloniex then you have to wait. If it still shows 0 confirmations after more than two hours then Poloniex may have an issue processing your deposit and you should contact them.

**Comment by Errrwin** [comment]
Hi,


I am waiting five hours already. I contacted them already but normally you have to wait a few weeks at Poloniex


________________________________
Van: QuantumMechanics <notifications@github.com>
Verzonden: maandag 5 februari 2018 20:59
Aan: NemProject/NanoWallet
CC: Errrwin; Author
Onderwerp: Re: [NemProject/NanoWallet] NEM to Poloniex not confirmed: I sent NEM to Poloniex and i can see it in my account of Poloniex, but I can also see that there is not one confirmation. What can be the problem? (#451)


Hi,

If you see the deposit as unconfirmed in Poloniex then you have to wait. If it still shows 0 confirmations after more than two hours then Poloniex may have an issue processing your deposit and you should contact them.
