### ISSUE TITLE
SpectroCoin deposit

### ISSUE THREAD

**Issue by Giglio13** [NemProject/NanoWallet#452]
I sent in sunday 4 mornig 7:36 a transaction to spectrocoin, but I don't see my xem in to my spectrocoin account. the addres are correct.  can anyone help me. thank. Christian Gigliodoro, chris.gigliodoro@gmail.com

**Comment by QuantumMechanics** [comment]
Hi,

Can you post the transaction hash here please ?

**Comment by Giglio13** [comment]
Dear sirs,

My  block transaction is: 1488876
My hash transaction is:
68051c07de35f05215604b5dc8593f9cb98cf7df4775a581aed41080c643a757

Thank's

Christian Gigliodoro

Il 10 Feb 2018 02:31, "QuantumMechanics" <notifications@github.com> ha
scritto:

**Comment by QuantumMechanics** [comment]
The transaction hash is present on the chain, so the exchange has not processed your deposit. 

You must contact spectrocoin support, explain that you have not been credited and provide the transaction hash.
