### ISSUE TITLE
Can't update Apostille 

### ISSUE THREAD

**Issue by shunwitter** [NemProject/NanoWallet#453]
Hi, I'm interested in developing my app using NEM Apostille.
In order to know how it's going to work I've tired it with NanoWallet, however, it seems all the actions for private Apostille are disabled or not implemented yet? (I followed this tutorial https://blog.nem.io/apostille-tutorial/ and https://docs.nem.io/en/nanowallet/apostille-module/transfer-notarizations)

<img width="1296" alt="2018-02-11 16 32 51" src="https://user-images.githubusercontent.com/3123900/36070933-47f987d6-0f49-11e8-9af1-bd9719138524.png">

The module is added in [this commit](https://github.com/NemProject/NanoWallet/commit/f74490ee9374d6f342a3ea5035c6dae8d6db2b14#diff-0bda3bbe3dd224f9ef5a687f8fc1e7f5) but buttons are disabled and I couldn't find files for [Update / Message / Split ownership] .

Anyone knows how to execute Apostille actions with NanoWallet? If it's not possible, maybe buttons should be hidden or removed?
Thanks!

**Comment by shunwitter** [comment]
It seems existed but removed. 
3c0e3aa83bc56d28d3d93e2383e897b73a737ed0

Is this because methods to modify private apostille using NEM-sdk haven't been implemented?
https://github.com/QuantumMechanics/NEM-sdk/blob/master/src/model/apostille.js

**Comment by QuantumMechanics** [comment]
Hi,

Advanced Apostille system will be in next release :)
