### ISSUE TITLE
NanoWallet can't connect to custom IP

### ISSUE THREAD

**Issue by wirfeon** [NemProject/NanoWallet#454]
Hello.

It seems that NanoWallet has a problem with connecting to NIS specified by IP address in "Custom node" input field.

Using:
Nano Wallet 2.0.14
Ubuntu 16.04;  4.4.0-112-generic x86_64 GNU/Linux

## Expected Behavior
NanoWallet connects to NIS on IP specified in "Custom node" input field

## Current Behavior
NanoWallet doesn't even try to connect to specified IP and randomly pick one from the select box above

## Possible Solution
N/A

## Steps to Reproduce
1. Run NIS on localhost
2. Put "localhost" in Custom node input field and hit +
3. NanoWallet connects correctly
4. Put "127.0.0.1" in Custom node input field and hit +
5. NanoWallet connects to a randomly chosen node from select box above

## Details
When I looked with wireshark, there were no signs of NanoWallet connecting to localhost (in an IP case). It went straitght out.

The example with localhost is just for replicating. What I need is to connect it to 192.168.1.1 (same problem)

Bug bounty address:
NAT3OV-PEEFXS-E6ASQO-XVPKFX-6WWASH-XLNVWQ-HUD6

**Comment by QuantumMechanics** [comment]
Hi, 

It is fixed in https://github.com/NemProject/NanoWallet/pull/433 

Next version should be fine.
