### ISSUE TITLE
Dashes in the address

### ISSUE THREAD

**Issue by merc1305** [NemProject/NanoWallet#457]
nanowallet 2.0.14
## Expected Behavior
once copy address from account page it should not contain dashes (like NBGJENKJCCSDY7YJTHIW4KEUBB4725GMAGJV46UF). 

## Current Behavior
once copy address from account page its copied with dashes (like NBGJEN-KJCCSD-Y7YJTH-IW4KEU-BB4725-GMAGJV-46UF)

## Possible Solution
Some exchanges accept address with dashes, some not, but the fact is that all exchanges accept address without dashes. Possible solution is to remove dashes on nanowallet and let users copy address without dashes only.

## Steps to Reproduce
1. go to nanowallet and login
2. go to Account tag
3. tap to copy address button or just copy it from the address label https://monosnap.com/file/UcDp9CgzdF7cAgJzV4l8wZQ6soO7O4
4. go to exchange and try to send XEM to copied address
[BUG] on some exchanges see errors that address is invalid. Tested on yobit.net,  Coss.io.

## Details
Really annoying to remove dashes. Some exchanges are accept address with dashes, but some not and this lead to topics like:

https://forum.nem.io/t/create-mosaic-coin-on-yobit-net-or-any-other-exchange/13005/10
https://forum.nem.io/t/dashes-in-the-address/4505
https://forum.nem.io/t/address-with-vs-without-dashes-polo-transaction-now-showing/5511/7

**Comment by QuantumMechanics** [comment]
Removed dashes from copied address https://github.com/NemProject/NanoWallet/commit/ca08e2005104d4a9b0e8a23dfe66f9663d4c2a5c
