### ISSUE TITLE
FAILURE_INSUFFICHENT_FEE issue after deleting number of mosaics

### ISSUE THREAD

**Issue by merc1305** [NemProject/NanoWallet#458]
Google Chrome Version 63.0.3239.132 (Official Build) (64-bit), nanowallet 2.0.14, Mac OS High Sierra Version 10.13.3 (17D47)

Acc1 - TD6SM3-2AZHLF-XC2OUJ-SJUGVA-376E43-QRYGTP-3ODQ	 
Acc2 - TDZZP2-OEPF25-JP2FOX-XC4NMS-B2M4E5-SXKOQG-53SI	
Mosaic: xbyn:byn2 (Levy ||) 

## Expected Behavior

Send mosaic from Acc1 to Acc2, expecting that mosaic will be transferred :) 

## Current Behavior

See FAILURE_INSUFFICHENT_FEE error message https://monosnap.com/file/tztIM6xSv0l08ckOGxZzSETqEDWQbO

## Possible Solution

Just before this action number of xbyn:byn2 mosaic was decreased to let Acc1 have all the xbyn:byn2 mosaic (new total supply is 1460). Owner of xbyn:byn2 mosaic (Acc2) have no this mosaic at all.

## Steps to Reproduce

1. create Mosaic (in my case with Levy ||)
2. Send some new mosaic to another account
3. delete remaining mosaic by "edit mosaic" feature
4. re login to both account to see that total supply is updated ( this is another point, will report it separately)
5. try to send mosaic back to owner

**Comment by merc1305** [comment]
Just make the same operations on mosaic without levy (total supply 3) - Unable to reproduce
Then tried with mosaic with Levy | (total supply 3) - Unable to reproduce
Then tried with mosaic with Levy || (total supply 3, multiplier - 5) - Unable to reproduce
Then tried with mosaic with Levy || (total supply 3, multiplier - 1000000000, Divisibility = 2) - Unable to reproduce
Then tried with mosaic with Levy || (total supply 9000000000, multiplier - 1000000000, Divisibility = 2) - Unable to reproduce

Sorry, but still able to reproduce with xbyn:byn2 only. Unable to reproduce with creation of new mosaic..

**Comment by QuantumMechanics** [comment]
Hi,

Similar issue was reported here: https://github.com/NemProject/NanoWallet/issues/432

Problem should be fixed in new release. It is an error in mosaic calculation, taking the initial supply instead of the current supply. Fixed here: https://github.com/QuantumMechanics/NEM-sdk/commit/f58553785a563407750d4fabd51b5fe888c6f4c4
