### ISSUE TITLE
2.1.2: Error: An error occured while trying to fetch market information!

### ISSUE THREAD

**Issue by Sateetje** [NemProject/NanoWallet#463]
## Expected Behavior
Retrieve market info after logging in

## Current Behavior
Error: An error occured while trying to fetch market information!

## Possible Solution
NA

## Steps to Reproduce
Login with Trezor
After logon, the error showed: An error occured while trying to fetch market information!

## Details
NA

**Comment by Orchid1503** [comment]
The same problem as mine!!!

**Comment by cryptoBeliever** [comment]
Market information is fetched using Poloniex API. Make sure it's available. Also, make sure you are using the standalone version (at this moment connection to Poloniex doesn't work on the browser version because of CORS issues).
