### ISSUE TITLE
2.1.2: Voting module disabled (on Trezor account without balance)

### ISSUE THREAD

**Issue by Sateetje** [NemProject/NanoWallet#465]
OS: W764 Browser: Firefox Dev Edition

## Expected Behavior
Voting module enabled

## Current Behavior
When I login with my Trezor, the voting module is disabled. The account has no balance. The account is used as a cosign for another account with balance.

## Possible Solution
NA

## Steps to Reproduce
1. Login with Trezor (account without balance and added as cosign to another account)
2. Go to Services
3. All voting links are disabled

## Details
![voting disabled](https://user-images.githubusercontent.com/16215404/36355381-a9b729b2-14e2-11e8-814e-01c6b4306a9a.png)

**Comment by Sateetje** [comment]
The Voting module is disabled with balance also (Trezor account)

**Comment by K3rnelPani1c** [comment]
I have the same issue, but my account is not empty, it has XEM in it and is harvesting. But same Grayed out voting

**Comment by cryptoBeliever** [comment]
I checked and it works on 2.6.2. So I expect it was fixed long ago.
