### ISSUE TITLE
Xem transfer to Cryptopia not showing up for over a month

### ISSUE THREAD

**Issue by Leeewin** [NemProject/NanoWallet#466]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Leeewin** [comment]
Sender /
Recipient	Amount 
Fee	Height	Timestamp 
deadline
nbt6rv-aukfxh-wezzdg-2zpggq-ircgyu-je3ddb-wi7o 
nbq73b-ylvgmo-7l2wfg-2vvojh-obwwjk-w7d3v7-ue4e	1884.000000 
0.100000	1474915
2018-01-25 12:45:43 
2018-01-26 12:45:43
tx hash: 7c472fbdbf1b94b1bad9cff9c998f0693786601a06353e3908b2f55400c6f503

**Comment by Leeewin** [comment]
been over a month and nothing

**Comment by akkie** [comment]
This has nothing to do with the NEM wallet. Your transaction is in the blockchain. Please contact Cryptopia for help.

**Comment by Joe159753** [comment]
Cannot transfer XEM to Changelly and Bittrex either from Nano Wallet.
How can I change XEM to other Coins?

[Bittrex]
From NBBISU-DLEEXX-VUNGFU-4FR3Q5-J2JDAT-4G7QQG-T32E
To ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR
Amount10 000.000000 XEM
Fee 0.100000 XEM
Message HEX: 0ab2817e388944d98a
Block 1543070
Hash c3fc780c3bfd34ea7931bd8fdaac045e3c749df42b7621b1f3b3d8471a9498f3

[Changelly]
Transfer transaction
From NBBISU-DLEEXX-VUNGFU-4FR3Q5-J2JDAT-4G7QQG-T32E
To NBLQ6P-E7Z5CV-ANJNXG-OR74UQ-LOJ2YM-GJJOZ4-YFAQ
Amount10 000.000000 XEM
Fee 0.100000 XEM
Message HEX: 00fc4460271111e8bbe625f3c5e68e85
Block 1542640
Hash 020740f8534770f167fa7794dd49b7ecfeb36ac02cf572fa9e43954b7b6c4c5d

**Comment by cryptoBeliever** [comment]
@Joe159753 in this transfer you use HEX message. It should be Unencrypted.
Please contact with Changelly and Bittrex support, provide transaction hash and ask for refund.

Next time please use forum.nem.io or Telegram channel @nemhelpdesk. Github is no place for reporting issues with exchanges.
