### ISSUE TITLE
Hi using window 10 and chrome browser, No recieve tab when selecting send tab and primary address key only shows 36 characters not the required 40.  Thank you  

### ISSUE THREAD

**Issue by Jasond123** [NemProject/NanoWallet#467]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by cryptoBeliever** [comment]
Hello,

Receive tab was removed. Your address is available when you click "Account" in top navigation.
