### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by 2ge** [NemProject/NanoWallet#468]
Hi,

using latest NANO wallet one doesn't have clue, how to get NEM address. I know, user have to click on ACCOUNT on top. The problem is, it looks like inactive element, also it is not clear, one should click there. Why not to make one more tab with RECEIVE title ?

Please fix it, it is serious usability issue not only for me.

**Comment by cryptoBeliever** [comment]
Reported here https://github.com/NemProject/NanoWallet/issues/694
Regarding inactive account link please try switch the node.
