### ISSUE TITLE
Multisig transactions fee (v2.1.2 Universal Client (with Trezor Support)).

### ISSUE THREAD

**Issue by Szpregel** [NemProject/NanoWallet#470]
Fee for multisig transactions (2/3) in the description of the transaction is 0,05 xem + 0,15 xem, but i paid 0,35 xem.

**Comment by AnthonyLaw** [comment]
Hi @Szpregel  it should be correct.

Mutlsig transaction fees is 0,15 xem when you make a transaction.

each consigner make sign, will add on 0,15 xem

in your case summary.

fees transaction  = 0,05 xem
initail multisgi transaction = 0,15 xem
consigner = 0,15 xem

total 0,35 xem

**Comment by cryptoBeliever** [comment]
Not a bug. @QuantumMechanics you can close.
