### ISSUE TITLE
Deposit XEM not showing in NANO Wallet. It is show completed in exchange.

### ISSUE THREAD

**Issue by juanchingli77** [NemProject/NanoWallet#471]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior

I deposit XEM to NanoWallet from Crytopia. Transaction is completed. The Node is Green , But notthing showing .It more than 7 hour. 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by juanchingli77** [comment]
Hi,
My transaction is below:
 

#3274058 | XEM | 886.10143895 | 1.00000000 | Complete | ed384ea6e6fa313a4201bae660a244f1977908b615ece08a8fc452716c087414 | NBE2KLKTSGGZXNKHWTPTUM5EMC2S2YECRKNJ6P4R: | 24/02/2018 10:23:00 AM

It completed in exchange but in my NANO walet is empty? Where is my coins now ?Please help?

**Comment by QuantumMechanics** [comment]
Hi, 

I don't see any transaction with that hash on the chain: http://chain.nem.ninja/#/search/ed384ea6e6fa313a4201bae660a244f1977908b615ece08a8fc452716c087414

Contact the exchange support, the XEM are still in their wallet.
