### ISSUE TITLE
XEM to HUOBI not transferred

### ISSUE THREAD

**Issue by billcr1** [NemProject/NanoWallet#472]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by billcr1** [comment]
Отправка транзакции
Отправитель Primary
Получатель NB7UMK-42XP56-YPS4ND-LDAM62-64NU7T-ZQWMR3-YQHJ
Сумма10 500.000000 XEM
Комиссия 0.050000 XEM
Блок 1516384
Hash 87178c8801dd24a160a6a220ee1c58a5cdce8ed32f5cceaa1a922c5552288afe

**Comment by billcr1** [comment]
火小天 (Huobi)
Feb 25, 13:49 CST

Respected users,




Due to the influence of related matters in NEM.io Foundation Ltd community, to protect user assets, we immediately suspend XEM's recharge and withdraw money without being affected. After NEM official processing is completed, it will resume charging. At the same time, XEM's currency is not affected. If there is any new progress, we will keep you informed.



Fire currency global professional station



February 20, 2018

**Comment by QuantumMechanics** [comment]
Hi,

We can't do anything about exchange issues.

You must contact Huobi support for more information.

**Comment by billcr1** [comment]
Hi! "After NEM official processing is completed"- what does it mean?
