### ISSUE TITLE
NanoWallet 2.1.2 Universal Client shows error messages on Chromebook 

### ISSUE THREAD

**Issue by johmut** [NemProject/NanoWallet#473]
OS : Chrome OS ; Stable Channel ; Version 64.0.3282.167 ; Chrome Browser

## Expected Behavior
I would not expect to see error messages ... 

## Current Behavior
When I click on Services and then Manage Delegated Harvesting, I see two error messages in red at the top right corner of the page. See the screenshot attached. The messages appear only on this page and disappear automatically  after a few seconds.  

## Possible Solution
The same software works fine on Chrome in Linux, just not on Chrome in Chrome OS (Chromebook)
Perhaps add this platform when performing non-regression testing on future releases ? 

## Steps to Reproduce
1. Download the NanoWallet Universal client and extract to a folder on the local disk
2. Click on start.html to open the NanoWallet in the Chrome browser
3. Login to your wallet (already in browser local storage)
4. Click on Services, then click on Manage Delegated Harvesting .... error messages come and go

## Details
Bug Bounty ? Please send reward to NA7RWPAG5EAV3SKX5G7UJX654ZDZ2CW2SYDE3B66

Thanks !
Johan

![nanowallet 212 bug](https://user-images.githubusercontent.com/2090354/36802172-87d0b5f0-1cb4-11e8-8c8e-c73439b25b40.png)

**Comment by johmut** [comment]
Bump ... Nobody here to follow-up on such issues ?

**Comment by johmut** [comment]
Oeps, never wanted to close, reopened ... still hoping for a response

**Comment by johmut** [comment]
Bump ...

**Comment by cryptoBeliever** [comment]
Did you try use another node? Try click circle in top right corner and select another node from list.

**Comment by fyahfox** [comment]
It is very likely that you are having problems with a node here. Please try another node as @cryptoBeliever suggested and report back if you are still having issues.
Of course nobody wants to see error messages, but they should be there if there actually IS a problem ;) Maybe the connection is slow and it is already triggering the error message, and then it loaded and the message is gone.
