### ISSUE TITLE
Missing Transfer

### ISSUE THREAD

**Issue by SergioGut** [NemProject/NanoWallet#474]
Hi,

on the 27th of February I did a payment to Cryptopia address:

NBQ73B-YLVGMO-7L2WFG-2VVOJH-OBWWJK-W7D3V7-UE4E (message 91377b11174b6c41)

and until today 2nd of March, the coins are still missing.

Thank you.

B.R.

Sergio

Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

You must contact Cryptopia, provide them the transaction hash and tell them you haven't been credited
