### ISSUE TITLE
Can't Use NEM With Trezor

### ISSUE THREAD

**Issue by MelbourneDeveloper** [NemProject/NanoWallet#478]
## Expected Behavior
Can login in with Trezor

## Current Behavior
App pops up pinpad window and just says "To use your TREZOR device, proceed with instructions at TREZOR Wallet and try again afterwards. "

## Possible Solution
Fix it

## Steps to Reproduce
1. Open the universal app
2. Log in with Trezor
3. Window pops up but can't enter pin.

## Details
- Windows 10
- Just downloaded app today
- Trezor Firmware 1.6.0

**Comment by jabo38** [comment]
Trezor updated and you need to install the Trezor Bridge
