### ISSUE TITLE
Can't see my account

### ISSUE THREAD

**Issue by DK1512** [NemProject/NanoWallet#479]
<img width="174" alt="unbenannt" src="https://user-images.githubusercontent.com/37215613/37209372-63400fb8-23a5-11e8-9c00-c1d13c570329.PNG">
Hi, can someone help me and tell me how I can see my accout?
The word is somehow behind the word Node.
Thanks

**Comment by imolev** [comment]
Hi, just change the node manually.

-- 
С уважением / Sincerely yours,

Иван / Ivan

Cell: +7 903 6288282
E-mail: ivan.molev@gmail.com, mgimo.finished@gmail.com
------------------------------------------------------
This email may contain information which is privileged or confidential. If you are not the intended recipient of this email, please notify the sender immediately and delete it without reading, copying, storing, forwarding or disclosing its contents to any other person. Thank you.

**Comment by DK1512** [comment]
Thanks
