### ISSUE TITLE
Question about harvesting

### ISSUE THREAD

**Issue by Sharehearts** [NemProject/NanoWallet#481]
as I was making set up for hervesting,I made transaction to remote address befor vested balance reacheed 10,000nem. right now the status says ''activating''   .    how long do I have to wait befor I can process over again . or I gotta make some move for this to be OK?

**Comment by QuantumMechanics** [comment]
Hi,

Activation takes about 6 hours, after that the status will show `ACTIVE` and you will be able to start / stop harvesting in the wallet, if you have 10'000 XEM vested.

**Comment by Sharehearts** [comment]
It’s been shown as activating for over 24hours , because I didn’t wait for the vested balance to reach
 10,000.                I think it will be the same next 24hours.      Can I do something about it ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by QuantumMechanics** [comment]
You can activate the remote without 10'000 XEM.

You only require the XEM to start the harvesting process.

Try changing node if status is still not showing `ACTIVE`
