### ISSUE TITLE
Market information not displayed

### ISSUE THREAD

**Issue by CryptoDaku** [NemProject/NanoWallet#482]
Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Current Behavior

My NEM NANO WALLET NOT ABLE TO DISPLAY MARKET INFORMATION ????

## Steps to Reproduce

1.
2.
3.
4.

**Comment by cryptoBeliever** [comment]
Market information is correctly presented in the latest version so I'm closing. If someone had this issue please make sure you are not using VPN that could block Poloniex API.
