### ISSUE TITLE
перевел XEM с hashflare.io на свой счет NanoWallet но так и не пришли хотя списание произошло что случилось?

### ISSUE THREAD

**Issue by jonlok108** [NemProject/NanoWallet#484]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by cryptoBeliever** [comment]
@jonlok108  Привет. Создайте тему на forum.nem.io в технической поддержке или напишите @nemhelpdesk на Telegram.
Github - не лучшее место для технической поддержки.

--- 

@jonlok108 Hello. Please create topic on forum.nem.io in Tech Support or write @nemhelpdesk on Telegram.
Github is not best place for Tech Support.

@QuantumMechanics please close this issue.
