### ISSUE TITLE
Sent Using Nano Wallet (Trezor), Transaction Confirmed but Tx Hash not found in Block Explorer

### ISSUE THREAD

**Issue by AndyNEM** [NemProject/NanoWallet#486]
## Details

Transfer transaction
From NBKDK6-AWKJFT-O25QSZ-ZNUD5V-IXYH6M-FGEMM4-Y5S3
To ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR
Amount5 323.000000 XEM
Fee 0.100000 XEM
Message d36a5f0ced164597854
Block 1537249
Hash c245e5c73e686a84336802ca5d958de53d1d52cc7b575ed2f558d474a96e6a52

What is the explanation for this please? Coins currently are stuck between my wallet and the receiving wallet at present. Coins were deducted from my wallet.

Thanks

**Comment by mizunashi** [comment]
Change the node to be referenced and check the balance.
The transaction is not on the block chain and has been canceled.

**Comment by AndyNEM** [comment]
Top man. That has solved the problem. It will be ok to try and send with the new node?

Many Many Thanks!

**Comment by mizunashi** [comment]
Last time, there was a problem with the node that was connected when transferring, and the NEM system rejected the transaction as a result.

Please make money remittance at the new node.
Thank you.
