### ISSUE TITLE
NanoWallet doesn't show purchased XEM / Mosaic LYL coins

### ISSUE THREAD

**Issue by icarusjun** [NemProject/NanoWallet#487]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details

Hello,

Please bear with me regarding my problem with LYL coins / NanoWallet

Pic 1 - shows my android app NEM Wallet account

Pic 2 - shows the dashboard wherein a transaction was made 9/3/2018... it was
actually a completed transfer of LYL coins that I've purchased since ICO...
another transaction done by one of your telegram admins wherein he transferred
.05 XEM to my account while troubleshooting this predicament

Pic 3 - shows a verified successful transaction using explorer.ournem.com

Pics 4-9 - this shows my desktop client NanoWallet wherein since the time
that transaction was confirmed until latest timestamp at bottom right corner
shows that I'm not seeing my LYL nor the XEM transferred into my account

Note the following:
- node is green, have tried different nodes for many number of times
- tried re-downloading the NanoWallet client app, even the 32bit version
- tried and retried importing wallet file and/or creating a wallet using private key
- up until the time of this writing, nothing shows...

It seems that I'm the only one experiencing such a problem.  I'm not a newbie nor
am I technologically challenged. However this problem is not only frustrating but
is testing mypatience as well.

Kindly advise as to what else must I need to do.  Thanks

![pic1](https://user-images.githubusercontent.com/37580876/37653380-acebbb1c-2c79-11e8-9b48-9ef5159c6c9d.jpg)
![pic2](https://user-images.githubusercontent.com/37580876/37653384-ade5b16c-2c79-11e8-8428-919a993676aa.jpg)
![pic3](https://user-images.githubusercontent.com/37580876/37653385-af04bf5c-2c79-11e8-85a1-742b1a00ef23.jpg)
![pic4](https://user-images.githubusercontent.com/37580876/37653387-b085dc80-2c79-11e8-9f0c-1067d7e91a43.jpg)
![pic5](https://user-images.githubusercontent.com/37580876/37653389-b17a3a1e-2c79-11e8-80e4-a14775eae9d9.jpg)
![pic6](https://user-images.githubusercontent.com/37580876/37653391-b29934c2-2c79-11e8-9721-f1924c441762.jpg)
![pic7](https://user-images.githubusercontent.com/37580876/37653394-b4046598-2c79-11e8-9fed-ff5b4b1da4dd.jpg)
![pic8](https://user-images.githubusercontent.com/37580876/37653396-b512a8e6-2c79-11e8-8223-52ab4d90b119.jpg)
![pic9](https://user-images.githubusercontent.com/37580876/37653398-b619b5cc-2c79-11e8-85ea-c804e4008b5b.jpg)

**Comment by QuantumMechanics** [comment]
Hi,

It seems Nano is not pulling the right information about your account from NIS.

Looks to me that you are connected to a forked node because the address shown in the `Account` page of Nano is right and your coins are present on mainnet explorer, so it should be good..

**Comment by icarusjun** [comment]
Eventually I believe so it's supposed to already be good as in my nemwallet android app still reflects also a successful transfer... this is quite puzzling... so what does FORKED NODE mean and what do I need to do to fix this?

**Comment by icarusjun** [comment]
FOUND OUT THAT THE CULPRIT TO THIS PREDICAMENT IS ACTUALLY A PARENTAL CONTROL FILTER INSTALLED IN THE LAPTOP.  UNINSTALLED AND VOILA - PROBLEM SOLVED!
