### ISSUE TITLE
Don't see my XEM exchange via nano wallet

### ISSUE THREAD

**Issue by yossishabi** [NemProject/NanoWallet#488]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details

Don't see my XEM exchange via nano wallet

I completly exchanged via changelly web site succesfully but still don't see my fund in Nano wallet , any ideas

**Comment by QuantumMechanics** [comment]
Hi,

Try to change the node and if you still don't see any XEM, contact Changelly, tell them you haven't received your XEM and give them the hash of the transaction you paid.
