### ISSUE TITLE
im trying to log in my nano wallet but the node stays red and i cant see my account. What can i do?

### ISSUE THREAD

**Issue by frankceelen** [NemProject/NanoWallet#489]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi, 

Click on the `Node` button in the top navigation and selected another node.
