### ISSUE TITLE
Nanowallet 2.1.2 - timestamp fetched from local computer

### ISSUE THREAD

**Issue by cryptoBeliever** [NemProject/NanoWallet#490]
In Nanowallet 1.4.13 timestamp for transaction was calculated based on /time-sync/network-time receiveTimeStamp from node API. In Nanowallet 2.1.2 it looks different and node time is not used. Many users reported "timestamp to far in the future" error. It should be fixed.

**How it looks before (in 1.4.13):**
var timeStamp = Math.floor(this._DataBridge.networkTime) + Math.floor(d.getSeconds() / 10);
(this._DataBridge.networkTime - time fetched from /time-sync/network-time receiveTimeStamp)

**How it looks now (in 2.1.2):**
var timeStamp = _helpers2.default.createNEMTimeStamp();

where:

var NEM_EPOCH = Date.UTC(2015, 2, 29, 0, 6, 25, 0);
var createNEMTimeStamp = function createNEMTimeStamp() {
    return Math.floor(Date.now() / 1000 - NEM_EPOCH / 1000);
};

Node time should be used. Many users reported lately "timestamp too far in the future" error returning by NIS.

Bounty (if eligible) address: NBQIOPLQXMRKWDFMJC2C2AVYSJ35QU3TT2AC6O4C

CC: @QuantumMechanics

**Comment by QuantumMechanics** [comment]
Hi,

I know about this, need to take time to fix, will do for next release.

**Comment by fyahfox** [comment]
Bounty paid. Tx hash: 31c294c2e162973a3d67774f0c4a9c54fc16ad3c5a20cfd71407dcf7bbb5870e
