### ISSUE TITLE
Nano Wallet to Poloniex transfer XEM

### ISSUE THREAD

**Issue by maru2546** [NemProject/NanoWallet#491]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details
I have sent XEM 70000 from Nano Wallet to Poloniex, but no success as of Today.
Tx hash is
c370a8ce96a2cb285a1874a62dee5144893b8019b50707a919b7a4994f3f2cb0

I got comment from Ploniex as following.
Please resolve this issue.

"Thanks for your patience as we investigated the wallet in question. 

We discovered an issue with the wallet, and we have since been able to resolve that issue. If you are still having trouble with this wallet or past transactions, please let us know and we will be happy to investigate further. 

Best,
Poloniex Support"

**Comment by cryptoBeliever** [comment]
@maru2546 Hello. Please create topic on forum.nem.io in Tech Support or write @nemhelpdesk on Telegram.
Github is not best place for Tech Support.

@QuantumMechanics please close this issue.
