### ISSUE TITLE
Response to preflight request doesn't pass access control check:

### ISSUE THREAD

**Issue by echto** [NemProject/NanoWallet#492]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior
Successfully sign in with Trezor T

## Current Behavior
 Sign in aborts with error after exporting from Trezor T

start.html#!/:1 Failed to load http://199.217.113.179:7782/nodes/nearest: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
main.js:190577 Objectcode: -1data: TypeError: Failed to fetch__proto__: Object
## Steps to Reproduce

1.  Plug in Trezor T
2.  Login using Trezor
3.  Export wallet

**Comment by cryptoBeliever** [comment]
I'm not able to reproduce anymore.
