### ISSUE TITLE
Empty Wallet when I login

### ISSUE THREAD

**Issue by SenhorCastor** [NemProject/NanoWallet#493]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior

Nano Wallet should show my current balance

## Current Behavior

Shows nothing

## Steps to Reproduce

1. Open Nano Wallet 2.1.2
2.Click Login
3.Select my Wallet
4.Valid Password
5. Login
6. Nothing shows

## Details

I already emptied my local storage and recreated a wallet

**Comment by QuantumMechanics** [comment]
Hi,

Click on `Node` button in the top bar and select another node.
