### ISSUE TITLE
cancel a transaction

### ISSUE THREAD

**Issue by Rolandysy007** [NemProject/NanoWallet#498]
Hi,
I have send XEM successfully from my nano wallet as given below to Bittrex exchange (see detail below):
From
ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR | + 1 375.668050 XEM |   | Sat, 07 Apr 2018 01:25:59 GMT

However, due to my unfamilar with the wallet, I realised I have entered the wrong message  unencrpted and send over. I did not receive XEM in the exchange.

Please help me cancel the above transaction so that the XEM can be returned to my wallet.

thanks for your help.
Roland
email address: roland.ysy007@gmail.com
Screenshot below and attach file.
![image](https://user-images.githubusercontent.com/38505180/38947597-db22e67e-436f-11e8-8f03-1a6b58ab786d.png)

[nano1.docx](https://github.com/NemProject/NanoWallet/files/1925085/nano1.docx)

**Comment by evias** [comment]
you can't cancel a transaction. 

you have to contact bittrex support, NEM cannot do anything for you as the coins are at the exchange now.

in your support request, add a link to your transaction on the NEM explorer so that will have it easier to handle your case.
