### ISSUE TITLE
Not harvesting

### ISSUE THREAD

**Issue by Shinnem** [NemProject/NanoWallet#502]
Hello.Please help me.
I have deposit 20000 nem.
And 
Remote status : Valid
Harvesting status : Valid

But Nanowallet has not harvested from 3 month ago.
Version is 2.1.2
Please tell me how can I fix?
Best regards,Shin.

Before submitting your issue, please review the following checklist:

- [x] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by p4perb0y** [comment]
I lost 10K NEM trying this, i don't where it went hopefully a solution is given.

**Comment by QuantumMechanics** [comment]
Hi,

If remote status and harvesting status are both 'ACTIVE' then it is working, maybe you had no luck yet.

Not even harvested a couple empty blocks ?

**Comment by cryptoBeliever** [comment]
@p4perb0y please contact via https://forum.nem.io/c/tech-support and please provide more details what you mean by "lost 10K NEM"
Thank you
