### ISSUE TITLE
10 000 NEM + 100 NEM disappeared when put towards delegated harvesting

### ISSUE THREAD

**Issue by p4perb0y** [NemProject/NanoWallet#503]
Where did this go?...  Need a solution please. (below are the two transactions i thought i was  putting my
NEM to work to harvest more NEM. instead it's vanished?) I dont see it in any delegated harvesting account and i would try to activate DH and it didn't work.  

ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR | - 10 000.100000                                                                            XEM | d5e251d784254515aa0 | Mon, 26 Mar 2018 05:54:10 GMT
-- | -- | -- | --
Transfer transaction
From
ND55AR-K4F3ET-W223WG-JPH3GE-W27OME-ABNY5R-GAP6
To
ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR
Amount
10 000.000000 XEM
Fee
0.100000 XEM
Message
d5e251d784254515aa0

***********************************************************

ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR | - 100.100000                                                                            XEM | d5e251d784254515aa0 | Mon, 26 Mar 2018 05:43:05 G
-- | -- | -- | --

Transfer transaction
From
ND55AR-K4F3ET-W223WG-JPH3GE-W27OME-ABNY5R-GAP6
To
ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR
Amount
100.000000 XEM
Fee
0.100000 XEM
Message
d5e251d784254515aa0
Block
1560185
Hash
5a5dd3156511219d245d28aed914f85e2958b48dd3ebf0545e27ff755ad2f0f6

**Comment by QuantumMechanics** [comment]
Hi,

These two transactions have been sent to Bittrex... 

Is it possible that you did it ? Otherwise it means your private key have been compromised but as your account still has XEM in it I doubt it

**Comment by p4perb0y** [comment]
how can that be ? im using trezor NEM and i got the addresses from inside my NEM/trezor page.  I waited a while and didnt see anything move or even say it's being sent. so I didn't even realize this was  the case until yesterday.  And that was right when i installed and upgraded my trez for the NEM support im wondering how i could have possibly had my private key comped.

**Comment by p4perb0y** [comment]
There's a realistic chance I was hammered drunk and made some trades.. i can see that happening.  I'll do an account audit before I leap off the balcony.

**Comment by p4perb0y** [comment]
ya my private key shouldn't be compromised. that's whatever/whoever is generating the DH keys within the wallet,..  theft.  might as well dump the rest of it.

**Comment by TonyCrypto** [comment]
Just check out your Bittrex account, it's probably there.

**Comment by p4perb0y** [comment]
I figured it out... I was for sure drunk, I can tell by the time stamp of about midnight.  But it's not in my NEM(XEM) wallet. So I thought wtf, I know I wouldn't send it to a random bittrex account(s).. and bittrex doesn't seem to keep any history that isnt pending or very recent anymore(at least not by default). Luckily, I downloaded a transaction history.txt  around that period. Seems I had traded it for more bitcoin, as it was about to rise, and NEM about to drop , {for a quick buck}.  Now I actually remember doing it.

Thanks for trying to help though :)


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
