### ISSUE TITLE
Create Poll With Zero Balance or Insufficient Balance

### ISSUE THREAD

**Issue by marafiq** [NemProject/NanoWallet#508]
Environment: Windows 7, Windows Nano Wallet 2.1.2
Bug: Create a Poll with Zero or Insufficient Balance. Wallet does not inform user about Poll Creation, "Creating ..." will keep spinning forever. If you look into console, it says "this._Alert.errorInsuficientBalance is not a function"
Solution: Notify user that you have insufficient balance. But more importantly, since Wallet has user balance in memory, we should disable the create button.

Steps to produce:
1- Create a test wallet
2- You must have zero or insufficient balance
3- Fill in data to create a poll
4- Click on Create button
5- It will keep spinning.

Bounty Info
XEM Message: 100513102
XEM Address: NC64UFOWRO6AVMWFV2BFX2NT6W2GURK2EOX6FFMZ

**Comment by QuantumMechanics** [comment]
Hi

Fixed https://github.com/NemProject/NanoWallet/commit/b4fa6f9b6685eb97ae99a0fbf480f7bcb4e5c184

**Comment by cryptoBeliever** [comment]
@marafiq please provide your private address (not exchange) to pay bounty.
Thank you
