### ISSUE TITLE
Error: instead of the password it is written to enter the passphrase

### ISSUE THREAD

**Issue by ghost** [NemProject/NanoWallet#51]
The template incorrectly specifies the label of the field, which can confuse the beginner.

![screenshot_1](https://cloud.githubusercontent.com/assets/27009557/24828278/45107320-1c62-11e7-9797-1b85c0eb3906.jpg)

My address: NB5AX35YADAGQGDCP637BKE5NM5YAICO7LULWW2X

**Comment by mizunashi** [comment]
Hi,
I think that part was corrected in 911201ad643d2e607bc3de5789df7d9331dc16dc

Thanks

**Comment by mizunashi** [comment]
This is about adding.
In Brain Wallet, Passphrese is written in Password BOX, but the label on the left is a password.
Please unify.
![2017-04-08 22 35 37](https://cloud.githubusercontent.com/assets/1645189/24829416/62c468b4-1cac-11e7-8046-ded4dd023344.png)

**Comment by jabo38** [comment]
Bounty Paid Transaction hash: 2a86e4723a3d94763e2f96d8eb33252ee055c49f04ed6399d0cb8041160c9dca
