### ISSUE TITLE
Withdrawal of 300 NEM not processed after 2 weeks. 

### ISSUE THREAD

**Issue by johnpugno** [NemProject/NanoWallet#511]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

Please give more details

**Comment by cryptoBeliever** [comment]
@johnpugno please report it here: https://forum.nem.io/c/tech-support (with more details)
