### ISSUE TITLE
2.2.0 Transaction history load more doesn't work

### ISSUE THREAD

**Issue by TonyCrypto** [NemProject/NanoWallet#512]
Explorer -> Transactions -> Fifth page -> Load more button
Load more button at the end of the last transactions page does not work. I was waiting more than 5 minutes in different browsers and different wallets. It does not fetch the historical blockchain data.

I'm using win7, tested on chrome and firefox, version 2.2.0 universal client. 

\<div class="bg-info" style="cursor: pointer;" ng-show="!$ctrl.noMoreTxes &amp;&amp; $ctrl.transactions.length &amp;&amp; $ctrl.currentPage+1 >= $ctrl._Helpers.calcNumberOfPages($ctrl.transactions, $ctrl.pageSize)" ng-click="$ctrl.getTransactions(true, $ctrl.transactions[$ctrl.transactions.length-1].meta.hash.data)">\<p class="ng-binding">Load more\</p>\</div>

Bounty if applicable:
NDZTPA7AUVVDAO2SXQ77I3V4ZSLETVSPF7CTRROE

**Comment by QuantumMechanics** [comment]
Hi,

It looks like most nodes cannot perform the request...

If you select `hugealice` or `alice` nodes from the nodes list it will work.

I will release a fixed version soon

**Comment by cryptoBeliever** [comment]
@QuantumMechanics could you give example request and node which cannot execute it?
Interesting case.

**Comment by QuantumMechanics** [comment]
Fixed https://github.com/NemProject/NanoWallet/commit/782bc527f4041fd33ec6c9d1d86c45272af5537a

@cryptoBeliever http://185.122.58.141:7890/account/transfers/all?address=NAMOAVHFVPJ6FP32YP2GCM64WSRMKXA5KKYWWHPY&hash=186124cf4496ffb777880b4350015f687773563f141994e2fce853939da5bce6&pageSize=100 will fail but if you change the endpoint to `hugealice.nem.ninja` it will work. Nodes must have history enabled to search for hash.

**Comment by cryptoBeliever** [comment]
@QuantumMechanics yes. This depends on settings:
// The number of hours to keep the hashes of transactions in memory (-1 = keep forever, 36 is the minimum)
// If transaction hashes are in memory, it is possible to query transactions by hash.
nis.transactionHashRetentionTime = -1

// Optional features supported by the local node (pipe-separated).
// TRANSACTION_HASH_LOOKUP: transactions can be retrieved by supplying the transaction hash.
// HISTORICAL_ACCOUNT_DATA: historical account data can be retrieved.
nis.optionalFeatures = TRANSACTION_HASH_LOOKUP

Thank you

**Comment by fyahfox** [comment]
bounty paid
TX hash: 581db44b6803cf14ac7279e743c9d15796dee9f2ce7f21ff4f7561f968fc9ad9
