### ISSUE TITLE
How to run NEM node

### ISSUE THREAD

**Issue by thomsonimjd** [NemProject/NanoWallet#515]
I have been devloping a traden and exchange platform where I have no of cryptocurrencies. I would like to add NEM too in my platform. I could not find any documentation to `how to run a node in jsonrpc mode or any other apis` I need following functionalties for NEM.
`1. Create new address 2. get balance of an address 3. send balance to another address 4. export/import privatekey`

could you please let me know any possibiliities of doing these requirements?

And also let me if there is `testent faucet and explorer` to test on my platform
Thanks in advance.

**Comment by cryptoBeliever** [comment]
Hello,

This is not question related with nanowallet. Please ask it on forum.nem.io or Telegram channels:
@nemred @nemprojects

Thank you.
