### ISSUE TITLE
Wrong addres

### ISSUE THREAD

**Issue by dreadnought14** [NemProject/NanoWallet#516]
I Submitted a withdrawal to the wrong address from Binance is there anything i can do?

Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by QuantumMechanics** [comment]
Hi,

Please provide more details

**Comment by dreadnought14** [comment]
Here is a screen shot of the withdrawal transaction from Binance sent to the wrong address.
    On Monday, June 4, 2018, 11:22:52 AM PDT, QuantumMechanics <notifications@github.com> wrote:  
 
 
Hi,

Please provide more details

**Comment by QuantumMechanics** [comment]
If you withdrew from Binance to a wrong address there is nothing we can do, transactions are immutable.
