### ISSUE TITLE
Trezor T : Failed to create wallet, reason: Unexpected message

### ISSUE THREAD

**Issue by echto** [NemProject/NanoWallet#529]
NanoWallet-2.2.0 does not work with the new Trezor T. 

After exporting NEM address on network Mainnet, NanoWallet aborts with "Failed to create wallet, reason: Unexpected message" error message.

Please advise.

**Comment by mizunashi** [comment]
Currently, Trezor T has not yet responded.

**Comment by echto** [comment]
Ok, Trezor needs to fix the issue, not you.  Thank you.
