### ISSUE TITLE
LYLs not showing up in nano wallet

### ISSUE THREAD

**Issue by 2corinthians91011** [NemProject/NanoWallet#532]
my recent transaction was initially in the UNCONFIRMED tab, however, it did not successfully go through the wallet... now, my lyls are nowhere to be found.

How can I fix this issue? Please help... I've done this a third time without any problem.

**Comment by cryptoBeliever** [comment]
Wow. You posted same question everywhere. Forum, helpdesk support, here. 
Already answered you here:

https://forum.nem.io/t/lyls-not-in-nano-wallet/17521/2

@QuantumMechanics please close this one
