### ISSUE TITLE
Timestamp to far in the future + voting

### ISSUE THREAD

**Issue by meyns** [NemProject/NanoWallet#533]
In the latest version there is still the problem of "timestamp too far in the future".
I am able to fix it, with resincing the windows time.
Also when voting with the timestamp problem, there is no warning message the the vote was not cast, it just says vote sent.

Using windows 10 64-bit pro with nanowallet 2.2.0

**Comment by tonowie** [comment]
This is still an issue. I was unable to announce multisig transaction because of the error. Had to set my system time back a bit...

**Comment by tonowie** [comment]
https://github.com/NemProject/NanoWallet/pull/570 attempts to fix this for multisig transactions

**Comment by QuantumMechanics** [comment]
Fixed with pull #570
