### ISSUE TITLE
no slots available for harvesting

### ISSUE THREAD

**Issue by quasarblue** [NemProject/NanoWallet#534]
Windows / Firefox Nanowallet 2.2.0 Universal Client

## Expected Behavior
Services->harvesting->start delegated harvesting
custom node : 88.99.87.132
being able to activate harvesting on that node

## Current Behavior
no slots available

## Possible Solution
Had to choose another supernode

## Steps to Reproduce
Try to harvest on 88.99.87.132

## Details
The account from which I try to activate harvesting
is already active, but stopped because of vesting balance.
When try to start harvest, writing the same node ip previously choosen
before deactivation, I receive no slots.
Actually 88.99.87.132 should have plenty of
https://nemnodes.org/nodes
it is running without nis restart since lot of time, 
account harvesting deactivation happened because of vesting 
balance, then tried reactivation.

looks like it's the specific account / start stop history problem
 NDVTBA-CKFPE3-RCJFSP-EQQVOI-YQ5Y3A-RPZI6R-FYP5

**Comment by cryptoBeliever** [comment]
@QuantumMechanics is this report clear for you? Could be this problem with nanowallet or node?

**Comment by gimre-xymcity** [comment]
is three a chance you activated using old NCC?
if so try to deactivate and activate again...

**Comment by quasarblue** [comment]
With the restart of the pointed NIS
the problem is no more reproduced.
The account is harvesting now.

Il mer 12 set 2018, 19:11 gimer <notifications@github.com> ha scritto:
