### ISSUE TITLE
New Module spelling mistake

### ISSUE THREAD

**Issue by ghost** [NemProject/NanoWallet#538]
"Import Wallet Backup Module" witch is mistakenly spell as "Import Wallet ---Bankup--- Module"

**Comment by QuantumMechanics** [comment]
Hi,

The dev did a mistake and I thought it could be the name in the wechat app

Will fix

**Comment by QuantumMechanics** [comment]
Fixed https://github.com/NemProject/NanoWallet/commit/e446b5ed23974506f3694e1d57c9a737ff9d07d2
