### ISSUE TITLE
About multisig

### ISSUE THREAD

**Issue by ASAT668** [NemProject/NanoWallet#539]
Previously I asked the same question, but when converting NanoWallet's account to multi sig, I mistakenly registered POLONIEX's XEM address as a co-signer.

At that time, and then you answered me, You must contact Poloniex and ask them to remove their address from the cosignatories. 

I contacted POLONIEX, but I have no reply at all.

I have a question,

Is there a method other than deleting POLONIEX from the consignee's list?

If not deleted, will I lose my wallet XEM?

It is a bad thing to make a mistake, but I face a big problem when I lose my wallet XEM.
Please cooperate. Please help me!

**Comment by mizunashi** [comment]
This is the place to report bugs in NanoWallet.
From the contents of your question, I think that it is contents to post to forum.nem.io.

**Comment by ASAT668** [comment]
Thank you for your advice. I will contact the forum nem io.
