### ISSUE TITLE
About the number of characters of description when creating a mosaic

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#54]
The number of characters of description has limitation of 512 characters in HTML.
However, since multibyte characters are also counted as one character, in fact more information than 512 letters of the alphabet can be entered.

When creating a mosaic when the number of characters is large, an error of js appears as shown in the next screen.

![2017-04-11 16 38 43](https://cloud.githubusercontent.com/assets/1645189/24898078/7eaae7a2-1ed6-11e7-9c14-0a6be585777c.png)

There is no transaction on the screen, no error occurs.
In this state, you can not press the create button even if you correct the description and make it the correct number of characters.
Once you go to a different page, you need to come back.

**Comment by QuantumMechanics** [comment]
Fixed in 2.0 https://github.com/NemProject/NanoWallet/commit/7f30d1674b0e300cd9761f23087ca281f2e9f4ac
