### ISSUE TITLE
[2.3.2] The TREZOR account can not sign "Multisignature aggregate modification transaction"★

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#549]
## Expected Behavior
You can add a signer to an existing multi-sig account.

## Current Behavior
There is a TREZOR account for the signer of the already existing multi-sig account.
In this case, this TREZOR account can not sign "Multisignature aggregate modification transaction".

*You can sign the remittance without problems.*

## Possible Solution
Bugfix

## Steps to Reproduce
1. Prepare a multi-sig account with TREZOR as the signer.
2. Add one person to the signer newly.
3. A signature request arrives for an existing signer, but you can not sign from the TREZOR account and you get an error.

## Details
Error message is here.

![2018-07-28 9 04 58](https://user-images.githubusercontent.com/1645189/43351287-b4a209b0-924a-11e8-8a59-7962db88f05b.png)

**Comment by cryptoBeliever** [comment]
Same as https://github.com/NemProject/NanoWallet/issues/612
