### ISSUE TITLE
Uploaded old Beta wallet to New Nem 2.3.1 but have small question

### ISSUE THREAD

**Issue by scottjgolfer** [NemProject/NanoWallet#551]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details

Hello,
   I recently imported an old beta wallet to the new NEM 2.3.1 wallet that i downloaded.  All my coins are in the wallet, my address is the same, so far so good.  While exploring the wallet features, I was looking for the recieve address and info.  I clicked on the "send" button and it took me to the page to send NEM coins but there was nothing to "recieve" NEM coins.   In my old beta version, when I click on the "send" button, i get the option to select "send" or "recieve".  So my question is, how do I find the recieve address and info?  So my next question is, if i want to send NEM coins to my new NEM wallet from an exchange, how do I get the "recieve info".  Do you guys have a tutorial that i can view?
   I still have my old beta wallet on my computer, not sure if I should do anything with it.
My operating system is Windows 10
Thank you 
Scott

**Comment by cryptoBeliever** [comment]
Receive address can be found when you click "Account" in top navigation (top right corner).
