### ISSUE TITLE
Transaction not received, requiered transaction ID/or TXHASH

### ISSUE THREAD

**Issue by ivanminero** [NemProject/NanoWallet#552]
Hello.

I have done a transction to an exchange but the funds haven't reached the exchange account. The transaction is confirmed in the NanoWallet dashboard, but can't be found in the blockchain. The exchange say the need the transaction ID/or TXHASH to check the transaction, they have tried with the provided Hash but is not possible to find it.

Please could you help me?.

Thanks.
Regards
![nem_transaction](https://user-images.githubusercontent.com/2802525/44212580-fe9bdc00-a16b-11e8-88c6-d84711bd7df8.jpeg)

**Comment by GodTanu** [comment]
http://explorer.nemchina.com/#/s_block?height=1758723

It overlaps with the time of updating NIS.
Is there no remaining balance?
I thought that the chain forked momentarily.

**Comment by cryptoBeliever** [comment]
Try change node. If node was in fork transaction is not valid.

**Comment by ivanminero** [comment]
Thanks, the funds are back in my wallet. I will try the transaction again.

El 10 sept 2018, a las 23:01, cryptoBeliever <notifications@github.com<mailto:notifications@github.com>> escribió:


Try change node. If node was in fork transaction is not valid.

**Comment by cryptoBeliever** [comment]
Great. @QuantumMechanics you can close this one.
