### ISSUE TITLE
проблемы с отправкой NEM

### ISSUE THREAD

**Issue by zoro198061** [NemProject/NanoWallet#553]
Добрый день. Я совершил транзакцию, отправил NEM на биржу Binance. Но мои токены так и не пришли! Почему?

[платеж NEM.docx](https://github.com/NemProject/NanoWallet/files/2297429/NEM.docx)

**Comment by sergv63** [comment]
HEX: 130a7d3774ed98d7ad44a85e354080   Перед строкой сообщения при выводе появился HEX. Я так понимаю это причина двойное кодирование. Как убрать  HEX????  НЕМ завис при выводе .
