### ISSUE TITLE
Changelly 'Exchange' button is Unresponsive in NanoWallet and Shapeshift Shows 'Page Not Found'

### ISSUE THREAD

**Issue by neoversionsix** [NemProject/NanoWallet#555]
## Steps to Reproduce

1. Click on 'services' in nano wallet
2. Click on 'Buy XEM on Changelly' or Shapeshift
3. Click on 'Exchange' (Changelly)
4. Shapeshift will show 'page not found'

**Comment by QuantumMechanics** [comment]
Fixed in https://github.com/NemProject/NanoWallet/commit/f63e435eeaabce31381dab27ef512e7e634d4bef
