### ISSUE TITLE
Multisignature signing - transaction don't appear in "Unconfirmed" section of cosigner

### ISSUE THREAD

**Issue by tongokongo** [NemProject/NanoWallet#558]
Scenario: multisignature 2 of 4.
Cosigner A; nanowallet
Cosigner B: nanowallet and mobile app backup
Cosigner C,D: offline, not important
Transaction:
http://chain.nem.ninja/#/multisig/45fe3561cdf6ba0494721eda40c8a6d355d0c8f32d108a1847435c873de0b71e

## Expected Behavior
After creating multisignature transaction from wallet A, multisignature transaction should appear in the cosigner B nanowallet in the "Unconfirmed" section. 

## Current Behavior
Transaction is not showing in the nanowallet (wallet B) in the "Unconfirmed" section.
![multisig](https://user-images.githubusercontent.com/29152385/45597133-53559100-b97c-11e8-8b4a-74a7a78b45de.JPG)
 I logged in/off many times. I changed nodes (all with the same, highest height), switched to version 2.2.0 etc. 
Meanwhile for the same cosigner, it's showing in the mobile app with the priv key of cosigner B:
![mobile](https://user-images.githubusercontent.com/29152385/45597128-2d2ff100-b97c-11e8-97ce-a831bf683f72.png)

To show that my nanowallet is connected, that's a screenshot of the confirmed transaction in wallet B few seconds after the transaction was confirmed in the NEM blockchain:
![multisig_confirmed](https://user-images.githubusercontent.com/29152385/45597147-8861e380-b97c-11e8-819f-82d97781000f.JPG)

## Possible Solution
I tried all possible ways of finding out the case, and I failed. It happened to me for a second time, usually those multisig transactions aren't causing me any problems. Don't know how to reproduce it as it happens extremely randomly. I believe other people had this problem as well. 

NEM wallet if bounty applicable:
NAWNNR-2SEDKU-YOBSKU-Q3VLZE-7WQW3D-YJ6UTE-SXOJ

**Comment by cryptoBeliever** [comment]
I've also noticed this bug. But what is interesting when I switched to mobile wallet (imported private key) it showed correctly transaction to confirm. So maybe problem is in way how nanowallet fetch unconfirmed transactions (websockets vs api call)? If websockets are not reliable maybe we should switch to api call?

**Comment by yaaccount** [comment]
See my comments here: https://github.com/NemProject/NanoWallet/issues/418#issuecomment-445587336
