### ISSUE TITLE
is possible get transaction hash from NIS or SDKs?

### ISSUE THREAD

**Issue by JokerCatz** [NemProject/NanoWallet#559]
is possible get transaction hash from NIS or SDKs?

I can't get transaction hash (like btc : txid or eth : txhash) without broadcast , & I can't get it from NIS API like `/block/at/public` too ( if I want get it without from my account or offline sign ) ... anybody can help me or use another SDKs (without the web explorer ... ) ?

**Comment by cryptoBeliever** [comment]
Please ask questions on forum.nem.io or on @nemhelpdesk/@nemprojects Telegram channels.

**Comment by JokerCatz** [comment]
I found /local/* can be get it
