### ISSUE TITLE
percentage increase displayed incorrectly for market data

### ISSUE THREAD

**Issue by leomcardle** [NemProject/NanoWallet#56]
In the nano wallet on the dashboard page.  The market data today is displaying "0.08 %", but XEM is up by 8%.  Obviously the math here is wrong and needs to be corrected.  Should be an easy fix.  

If there is a bug bounty for this, please send to my NEM address:
NDA35S-AWTJFU-KNQROW-TWRPXD-QLYCL3-GI7VXR-ODIN

Thanks.  Just FYI the sequence of delegated harvesting needs some serious UX work.  It took me the greater part of a day to figure out how to activate delegated harvesting.  The issue is related to the fact that you're requiring the password in the 2 different blocks BEFORE the activation buttons appear.  This sends mixed messages to the user, because current UX protocol requires that the user should be able to push the button they wish to use, such as to start or stop delegated harvesting.  After they push this button, you should query them for their password at that time in a pop up dialogue or create a error message to have them put in their password.  This would eliminate much of the confusion.

**Comment by evias** [comment]
i would agree to a more "reactive" approach to error handling than the one the UIs proposes now. (which is more "preventive"). I sometimes myself am "looking for the missing info" on forms because i forget to input something, so I agree this "grey out of buttons" is working well but also, it is not verbose enough in terms of feedback to the end user :)

**Comment by QuantumMechanics** [comment]
https://github.com/NemProject/NanoWallet/commit/bc27e4d5590344519f31df54896ab669749c4dbd
https://github.com/NemProject/NanoWallet/commit/9e9f9e98e174f3ca7cdab91c41a4e2a2465ceaa7

**Comment by jabo38** [comment]
Bounty Paid Transaction hash: e41e2802abc2694cf661f1c2e4f3b07ff4600ac2cb543d388430657f22702d52
