### ISSUE TITLE
2.2.0 Transaction history load more doesn't work - better solution

### ISSUE THREAD

**Issue by cryptoBeliever** [NemProject/NanoWallet#566]
Issue was already reported here: https://github.com/NemProject/NanoWallet/issues/512 but in my opinion provided fix is not enought and this feature need to be rewritten a little bit.

1) Right now to "load more" nano is using hash (for first page hash is empty):
	
		/account/transfers/all?address=<address>&hash=<hash>&pageSize=100
	
	Because of that it requires from node to turn on hash retention to -1 (forever):
		
		nis.transactionHashRetentionTime = -1 #  keep forever
	
	This is not default setting and most of nodes doesn't have it set to forever (36 hours is default). 	
	Without this we receive errors like this:
	
		{"timeStamp":114339498,"error":"Bad Request","message":"Neither transaction id was supplied nor hash was found in cache","status":400}

	Solution? Replace with id!
	
	Example requests:

	Loading with hash (second call causes error):
		http://hugealice.nem.ninja:7890/account/transfers/all?address=ND2JRPQIWXHKAA26INVGA7SREEUMX5QAI6VU7HNR&pageSize=100
		http://hugealice.nem.ninja:7890/account/transfers/all?address=ND2JRPQIWXHKAA26INVGA7SREEUMX5QAI6VU7HNR&pageSize=100&hash=ab0d79250f80831bb0771a5238105578d7fb11533a6692526fd312bad08ddbed
	
	Loading with id (no problem):
		http://hugealice.nem.ninja:7890/account/transfers/all?address=ND2JRPQIWXHKAA26INVGA7SREEUMX5QAI6VU7HNR&pageSize=100
		http://hugealice.nem.ninja:7890/account/transfers/all?address=ND2JRPQIWXHKAA26INVGA7SREEUMX5QAI6VU7HNR&pageSize=100&id=3185038
		http://hugealice.nem.ninja:7890/account/transfers/all?address=ND2JRPQIWXHKAA26INVGA7SREEUMX5QAI6VU7HNR&pageSize=100&id=3169966
	
	and so on. We using last id from previous call to do next call.
	Please keep in mind that id for same transaction differs for different nodes so it's necessary to clear loaded transactions after node change.

2) In https://github.com/NemProject/NanoWallet/commit/782bc527f4041fd33ec6c9d1d86c45272af5537a hugealice.nem.ninja is hardcoded. Right now hash retention time changed for hugealice and users are unable to load more transactions. After fix from point 1 if for mainnet should be removed.

**Comment by yaaccount** [comment]
Anyone to review or test it? Is there a process for testing? Unit? Integration? Exploratory?

**Comment by cryptoBeliever** [comment]
@QuantumMechanics could you look at it? As far as I remember Rin test it but this is how looks process now? 
Looks ok for me but I'm not JS master ;)
