### ISSUE TITLE
[2.3.2] Invalid-Conformation for Multiple Choice Vote 

### ISSUE THREAD

**Issue by ghost** [NemProject/NanoWallet#577]
## Expected Behavior
After voting with multiple choice (during Community POI Foundation Election Vote) i expected a visual confirmation that my vote went through and everything was allright.

## Current Behavior
After voting with multiple choice (during Community POI Foundation Election Vote) the confirmation mistakenly shows an "invalid transaction"-label (see attached), tough the vote went through.

![bildschirmfoto 2018-12-12 um 21 28 32](https://user-images.githubusercontent.com/34475192/49897748-46e7b400-fe57-11e8-9fca-74ec768fb9c4.png)

## Possible Solution
Green Label for confirmation that vote went through

## Steps to Reproduce

1. Login to NEM 2.3.2
2. Go to Voting-Section
3. Choose a poll where multiple choice is possible 
4. Select multiple answers and vote
5. in the upper right corner an "invalid vote"-label appears

Bounty: NCJADPBV2663HAF33J6REKZPT4QS6EJEP4QD6PPP

**Comment by cryptoBeliever** [comment]
At this time NEM Nano Wallet 2.4.2 with an updated version was available. It should be used. There was an updated voting module in that version. Also works fine in the latest version.
