### ISSUE TITLE
"Edit a multisignature contract" Multi-sig multiple delete can be specified

### ISSUE THREAD

**Issue by GodTanu** [NemProject/NanoWallet#58]
Multiple accounts can be specified

![111](https://cloud.githubusercontent.com/assets/20492223/25064254/a398265c-2231-11e7-9aa1-9ea5cbbfca87.JPG)

However, 'FAILURE_MULTISIG_MODIFICATION_MULTIPLE_DELETES' occurred.

![222](https://cloud.githubusercontent.com/assets/20492223/25064256/ab74f832-2231-11e7-8e1b-b4f49453c0eb.JPG)

I think that it is better to make it impossible to select

**Comment by QuantumMechanics** [comment]
Fixed https://github.com/NemProject/NanoWallet/commit/9a12b73c493da34539c2f6e7d1d1e6ccb7feacd4
