### ISSUE TITLE
Trezor Connect window will not load properly

### ISSUE THREAD

**Issue by j-mikhail** [NemProject/NanoWallet#584]
## Expected Behavior
When using the NEM Wallet with Trezor Support, selecting the Mainnet and clicking "Next" should open the Trezor Connect pop-up window, automatically authenticate, and move ahead.

## Current Behavior
The Trezor Connect pop-up window remains stuck at "Loading...". A cursory examination of the debug console reveals this error:
```
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://connect.trezor.io’) does not match the recipient window’s origin (‘https://connect.trezor.io’).
```

## Details
The error message is odd, as the target and window origins appear to be identical. Unclear what causes this issue. Tested in Firefox 66b6 and Chrome 70.0.3538.77. All script, tracker and canvas blockers disabled. All cookies, including third party, allowed.

**Comment by bosomt** [comment]
@j-mikhail works fine in NEM Wallet v2.4.7
