### ISSUE TITLE
The index.html don't open under Chrine

### ISSUE THREAD

**Issue by microSoftware** [NemProject/NanoWallet#59]
Hello, 
When I open index.html with Chrome. I see chrome loading something but there is no new tab opening.
But when I open index.html with Firefox it works: file:///Users/alan/Desktop/NanoWallet/start.html#!/
And then if I copy this address to Chrome it works.
So I think it's a problem with the main.js that avoid Chrome to open the tab idk.

OS : El Capitan
Chrome : v57

**Comment by cryptoBeliever** [comment]
Not able to reproduce it on the new Chrome version.
