### ISSUE TITLE
The problem of entering the brain wallet  with Nano Wallet 2.4.4

### ISSUE THREAD

**Issue by TeeX33** [NemProject/NanoWallet#593]
The problem of logging into the nanowallet of version 2.4.4 occurs if you use the previously created brain wallet in version 1.4.13 for the authorization to using vlt+password. You can only enter into the wallet by creating a new one using the previously saved private key. Users who previously created a brain wallet without saving the private key can not use the new version. Previously, it was assumed that the password for a brain wallet = private key

NCNPO2-K2GZJ3-ZSSOGL-XUJ2QS-YLMNDC-AFNHAW-K6RS

**Comment by GodTanu** [comment]
This problem seems to be addressed individually by the NEM Foundation.

https://forum.nem.io/t/please-stop-using-brain-wallet-and-refund-to-you/8147

**Comment by cryptoBeliever** [comment]
You can:
1. get old version of nanowallet (https://github.com/NemProject/NanoWallet/releases?after=2.0.13) 
2. look what private key you have
3. import private key into new wallet version using Private key option

I suggest you to create new "Simple wallet" and move funds there from brain wallet.
