### ISSUE TITLE
Mosaic NPXSXEM

### ISSUE THREAD

**Issue by Silveira1** [NemProject/NanoWallet#594]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Silveira1** [comment]
Hello, the NPXSXEM mosaic has disappeared from my account. Is there a problem about it?

**Comment by cryptoBeliever** [comment]
Mosaic expired but Pundix team renewed it in the grace period. Should be visible now. @QuantumMechanics you can close the issue.
