### ISSUE TITLE
The funds have not been received. I send nems from my NEM wallet to the Binance exchange and they have not yet arrived. Отправитель Primary Получатель NC64UF-OWRO6A-VMWFV2-BFX2NT-6W2GUR-K2EOX6-FFMZ Сумма 4 210.000000 XEM Комиссия 0.050000 XEM Блок 2383643 Hash c6bcfa521c91609da07e1e1ebbca4c2778fb2c4b2c4ea308b155c153a282c130

### ISSUE THREAD

**Issue by palka2403** [NemProject/NanoWallet#601]

**Comment by palka2403** [comment]
I send nems from my NEM wallet to the Binance exchange and they have not yet arrived.
Отправитель Primary
Получатель NC64UF-OWRO6A-VMWFV2-BFX2NT-6W2GUR-K2EOX6-FFMZ
Сумма 4 210.000000 XEM
Комиссия 0.050000 XEM
Блок 2383643
Hash c6bcfa521c91609da07e1e1ebbca4c2778fb2c4b2c4ea308b155c153a282c130

**Comment by cryptoBeliever** [comment]
You didn't include message code as states in Binance deposit instructions. Transaction:
https://explorer.nemtool.com/#/s_tx?hash=c6bcfa521c91609da07e1e1ebbca4c2778fb2c4b2c4ea308b155c153a282c130

Please contact with Binance, provide transaction hash and ask for manually credit this transaction to your account.

**Comment by palka2403** [comment]
Ok, thanks!

чт, 23 квіт. 2020 о 14:12 cryptoBeliever <notifications@github.com> пише:
