### ISSUE TITLE
Please upgrade Trezor connect , NEM wallet is not working with latest Trezor firmware

### ISSUE THREAD

**Issue by bosomt** [NemProject/NanoWallet#602]
Please upgrade Trezor connect , NEM wallet is not working with latest Trezor firmware.

Works fine with 1.8.x firmware
Doesn't work with 1.9.0 firmware

![image](https://user-images.githubusercontent.com/31506317/80564644-a9ab0280-89ee-11ea-911b-9baceeca3c33.png)

ends in 

![image](https://user-images.githubusercontent.com/31506317/80564667-bcbdd280-89ee-11ea-9c2a-31dff7b4a619.png)

when using current firmware

**Comment by cryptoBeliever** [comment]
@bosomt are you using Trezor One or Trezor T?

**Comment by bosomt** [comment]
@cryptoBeliever im using both , but 1.x.x firmwares are for T1

**Comment by mizunashi** [comment]
My Trezor T environment is shown in the diagram.
It works fine in this environment.

https://trezor.io/support/technical/
![ 2020-09-07 16 10 53](https://user-images.githubusercontent.com/1645189/92358793-077df280-f125-11ea-944b-27913edfde00.png)

The version of NanoWallet is 2.4.7.

**Comment by bosomt** [comment]
I can confirm that 2.3.3 works fine. 
I just sent transaction

**Comment by cryptoBeliever** [comment]
I will try verify with Trezor One. Thanks.

**Comment by cryptoBeliever** [comment]
@bosomt I upgraded firmware for Trezor One to 1.9.3 and I'm able to login without problems using NEM Desktop wallet 2.4.7

**Comment by bosomt** [comment]
i was able to send transaction via 1.9.3 as well
looks like new FW versions are working again

https://explorer.nemtool.com/#/s_account?account=NDF4JO-NFCYNN-QGRM5F-346GDZ-HWMKQ7-TW6CEZ-V2E4

closing
