### ISSUE TITLE
Transaction is not completed

### ISSUE THREAD

**Issue by Waschuk** [NemProject/NanoWallet#604]
Hello,

the message to XEM wallet address was empty or wrong ( I don't even know what that is supposed to be). This issued the problem, that transaction was not completed, according to e-mail was sent to me later.
But how to solve this problem now?

transaction ID: zu172gcbjvevuvjd
Adress: NA3HEU-UKOS5S-G23JA5-6ZM4YF-VA4L3U-VIAOU2-35XA

Pls support my by this topic.
Thanks in advance

![nem überweisung](https://user-images.githubusercontent.com/65838299/82762068-23bc8480-9dff-11ea-81fc-5dd5aa09624b.JPG)

**Comment by cryptoBeliever** [comment]
It's not place to report issues with changelly. You should contact with Changelly or NEM Support (support@nem.group)
