### ISSUE TITLE
Trezor Symbol opt in not completing. 

### ISSUE THREAD

**Issue by Sytd3h5** [NemProject/NanoWallet#607]
I tried to opt in twice for the Symbol token. Both times I got stuck at the fetching opt in data page after signing the transaction with my trezor and it wouldn't proceed. Now I have two sets of everything (private keys, mnemonic phrases, etc) and no confirmation of whether either of my opt ins were successful or not. Please advise. I am doing all this on Chrome using windows 10.

**Comment by cryptoBeliever** [comment]
If you got "Window blocked" error please enable pop-ups. Please use @nemhelpdesk Telegram channel or forum.nem.io

**Comment by QuantumMechanics** [comment]
Closing, please comment if not solved.
