### ISSUE TITLE
Opt-In version - dependencies to private repositories

### ISSUE THREAD

**Issue by cryptoBeliever** [NemProject/NanoWallet#610]
In package.json are two private dependencies:

```
"catapult-optin-module": "git+https://github.com/nemgrouplimited/symbol-optin-module.git",
"symbol-paper-wallets": "git+https://github.com/Peersyst/symbol-paper-wallets.git",
```

Because of that it's impossible to build app right now if someone don't have access. Those dependencies should be released.

**Comment by QuantumMechanics** [comment]
@Peersyst please make the dependency public, the application must remain buildable and reviewable by the community. I have important updates to do as well. Thank you

**Comment by eorodionov** [comment]
Bump, is there a solution to this? I also cannot build because of private repos.

**Comment by cryptoBeliever** [comment]
Fixed.
