### ISSUE TITLE
Please don't use "2.4.7" in the next release. 

### ISSUE THREAD

**Issue by jabo38** [NemProject/NanoWallet#611]
For clarity, each release should have a different number. For instance I have a version 2.4.7 where I can make votes and a version 2.4.7-optin where I can't. 

If we are going to tag "optin" in the name, I think it should at least be "2.4.8-optin" or later.

**Comment by QuantumMechanics** [comment]
I did not had time to review the opt-in changes and the pull request has been merged with an old version of the voting module.

I would like to release a version 2.4.8 with a fix but the pull added private dependencies to the packages.json file and it prevent me from doing any build as mentioned in issue #610

Not sure why this has been allowed, merges must not be blocking in any way, anyone should be able to build the project and review dependencies :/

Is it possible to contact the owner of the dependencies to make them public or give me access ?

**Comment by cryptoBeliever** [comment]
@QuantumMechanics I asked to contact you via Telegram. If this is not a good way please send me other contact that I should pass :)

**Comment by QuantumMechanics** [comment]
Telegram is perfect, thank you very much :)

**Comment by jabo38** [comment]
@QuantumMechanics thank you for looking into this. I'd suggest there is no reason to have "optin" after the release number personally. It isn't like in the years to come that would still need to be in there.

**Comment by QuantumMechanics** [comment]
I agree, will remove the "optin" tag in next release.

**Comment by rg911** [comment]
> Telegram is perfect, thank you very much :)

Hi @QuantumMechanics 
would be good to connect you on telegram as well, already sent you a message, my username is @rg911
