### ISSUE TITLE
XEM still marked as red / not transferred after two days?

### ISSUE THREAD

**Issue by NPB2020** [NemProject/NanoWallet#614]
I downloaded build-2.4.7-optin and opened my wallet. I have transferred out my NEM funds, however after two days the 'paperplane' is still red meaning my funds are still not transferred out of my wallet.

What to do?

**Comment by QuantumMechanics** [comment]
The red 'paperplane' on the dashboard indicate an outgoing transaction. Your funds went out if under the "Confirmed" tab. I close the issue but you can comment if not solved.
