### ISSUE TITLE
Ledger - Missing translations

### ISSUE THREAD

**Issue by cryptoBeliever** [NemProject/NanoWallet#628]
There are missing translations for alert pop-ups. 
For example:

![image](https://user-images.githubusercontent.com/17684281/107517998-cb0c6200-6bae-11eb-8089-4cab6692d01c.png)
![image](https://user-images.githubusercontent.com/17684281/107518072-e0818c00-6bae-11eb-873b-1363b13f512f.png)

**Comment by QuantumMechanics** [comment]
Partially fixed in b24c7a4, needs translations

**Comment by cryptoBeliever** [comment]
Closing. I expect translations should be added in the next translations round made by community.
