### ISSUE TITLE
Opt-in Rus translation

### ISSUE THREAD

**Issue by postoronnii** [NemProject/NanoWallet#629]
![image](https://user-images.githubusercontent.com/11311924/107523105-987a5d80-6bde-11eb-850e-47f10334e222.png)
![image](https://user-images.githubusercontent.com/11311924/107523719-3c640900-6bdf-11eb-8c24-8a65f7dc297e.png)
![image](https://user-images.githubusercontent.com/11311924/107523776-4be35200-6bdf-11eb-8fc9-cb00eef47cf9.png)
![image](https://user-images.githubusercontent.com/11311924/107523827-569de700-6bdf-11eb-9d6e-c7984fa392da.png)
![image](https://user-images.githubusercontent.com/11311924/107523877-65849980-6bdf-11eb-84a6-df6ed9042144.png)
![image](https://user-images.githubusercontent.com/11311924/107523922-6fa69800-6bdf-11eb-9c96-fa343340ef2a.png)

**Comment by cryptoBeliever** [comment]
Since Opt-in will be removed in the next version I'm closing this issue.
