### ISSUE TITLE
hw-transport-node-hid & electron package version issue

### ISSUE THREAD

**Issue by rg911** [NemProject/NanoWallet#631]
The current `hw-transport-node-hid` is `5.31.1` which builds the native apps for all 3 operation systems. However, the 5.31.1 node-hid comes with `usb@1.6.3` which won't work with the latest macOS. Wallet throws "cannot open device with path" all the time. Only way to get ledger work on mac is to update node-hid to 5.41.1 (with usb@1.6.4). However, the current electron `8.5.5` won't cope with it. 

It is recommended to review the electron & dependencies package version and update them to the latest stables.

**Comment by QuantumMechanics** [comment]
Fixed in b24c7a4
