### ISSUE TITLE
can't scan QR codes for import wallet on version 2.5 Mac DMG

### ISSUE THREAD

**Issue by jabo38** [NemProject/NanoWallet#634]
# Expected Behavior
when going to log in and then the import wallet page, I should be able to scan a wallet QR code to import said wallet. Via the universal client and browser, this works fine, but via the DMG install, it doesn't. Normally a user would be asked to give the wallet permission to access the camera, in this build, there is no prompt to allow it and therefore no ability to scan.

**Comment by cryptoBeliever** [comment]
Works on Linux build so for verification Windows/Mac.

**Comment by QuantumMechanics** [comment]
Fixed in b24c7a4
