### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by carlesdh** [NemProject/NanoWallet#648]
<img width="1097" alt="Captura de pantalla 2021-03-12 a las 14 08 52" src="https://user-images.githubusercontent.com/65666437/110976280-7986fc80-833f-11eb-9ce8-55d450b704c8.png">
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

**Comment by cryptoBeliever** [comment]
Hello,

This is a spam mosaic sent to multiple random addresses.
You should ignore this one. And don't try to send it away because there is leavy (you will pay tax in XEM) attached to this mosaic.

Thank you
