### ISSUE TITLE
xem and xym

### ISSUE THREAD

**Issue by crisift** [NemProject/NanoWallet#651]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.

## Details

I don't understand the wallet platform, I opt-in for xym ... before 12March it was showing my balance of xym on the right/down corner. But now I have no idea where are my coins. Can someone tell me what is happening ? how do I get my coins ?

**Comment by filchef** [comment]
I have 3 private key with XEM inside from 2016 so today 03.16.2021 I try to claim my XYM 
I import my private key in 3 different accounts and try to clime XYM from services - Symbol Opt In
So when I try to do this was message XYM is over and to update my wallet but wallet is last beta version.
Possible Solution - Perhaps this situation of importing the private keys after the day of the event is not provided by the developers.
Steps to Reproduce 
1.Import the private key to one account 
2.Try to claim XYM

**Comment by crisift** [comment]
Thank you for your feedback filchef ... Symbol team must make a video ... or to explain exactly what is happening ... 
I tried to import my key to symbol wallet .... but nothing ... no xym coins

**Comment by Auri2140** [comment]
Hola. ¿Cómo han podido desaparecer mis XYM de Symbol wallet, sin dejar rastro? Los reclamé en su momento y llegaron perfectamente y ahora de repente han desaparecido. Me podrían ayudar? Gracias

**Comment by cryptoBeliever** [comment]
Hello. If you are already opt-in your coins are in Symbol wallet. You can access using mnemonics phrase you received during opt-in:
https://docs.symbolplatform.com/guides/migration/post-optin-xym-retrieval.html

If you did not opt-in you can do it post-launch:
https://docs.symbolplatform.com/guides/migration/post-launch-optin-xym-retrieval.html
