### ISSUE TITLE
An error occurs every time you click to enter the management delegated page

### ISSUE THREAD

**Issue by krypton-master** [NemProject/NanoWallet#652]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Steps to Reproduce

1.
2.
3.
4.
<img width="1299" alt="屏幕快照 2021-03-18 10 13 52" src="https://user-images.githubusercontent.com/74108560/111563627-432ffe00-87d3-11eb-80c1-4038ef93ea64.png">

**Comment by cryptoBeliever** [comment]
Hello. Supernodes endpoint was unavailable. Now should it work. Please close if all ok.
