### ISSUE TITLE
forgot my NEM MEMO while sending

### ISSUE THREAD

**Issue by francoiskruijsen** [NemProject/NanoWallet#653]
hi guys,
i am from holland and made a mistake while transfering my XEM NEM from my personal NEM wallet to my Binance Wallet.
I sent the XEM to my Binance Wallet but forgot to fill out the NEM MEMO....and i am affraid my XEM NEM is gone!
Can anyone help me please on how to maybe solve this problem????

**Comment by Aragas1983** [comment]
Também estou com um problema bem parecido, só que no meu caso acabei digitando o MEMO errado.

**Comment by Aragas1983** [comment]
> oi pessoal,
> eu sou da Holanda e cometi um erro ao transferir meu NEM XEM de minha carteira NEM pessoal para minha carteira Binance.
> Enviei o XEM para minha carteira Binance, mas esqueci de preencher o MEMO NEM ... e temo que meu NEM XEM tenha sumido!
> Alguém pode me ajudar por favor em como talvez resolver esse problema ????

Cara, tenho boas notícias para você, tem um tutorial que ensina a recuperar os tokens em casos como esse.

https://www.binance.com/pt-BR/my/wallet/recovery/form/d

https://www.binance.com/pt-BR/support/articles/40b87335db904481888ef406b105442b

**Comment by francoiskruijsen** [comment]
Thanks a lot aragas, I have informed with binance and they have created a ticket and hopefully there will be a solution! Thank for your reply and answers!!!!!

> > oi pessoal,
> > eu sou da Holanda e cometi um erro ao transferir meu NEM XEM de minha carteira NEM pessoal para minha carteira Binance.
> > Enviei o XEM para minha carteira Binance, mas esqueci de preencher o MEMO NEM ... e temo que meu NEM XEM tenha sumido!
> > Alguém pode me ajudar por favor em como talvez resolver esse problema ????
> 
> Cara, tenho boas notícias para você, tem um tutorial que ensina a recuperar os tokens em casos como esse.
> 
> https://www.binance.com/pt-BR/my/wallet/recovery/form/d
> 
> https://www.binance.com/pt-BR/support/articles/40b87335db904481888ef406b105442b

**Comment by francoiskruijsen** [comment]
Could take a few days....but that’s worth it of course!
