### ISSUE TITLE
help in displaying my xem

### ISSUE THREAD

**Issue by nikollai777** [NemProject/NanoWallet#656]
Hello dear GitHub team! My name is Nikolai and I really need your help, help me withdraw my xem from NanoWalet, I threw my coins back in 2018 and, due to my stupidity, I did not understand well enough to create a multi-signer, I log into my account, I see my money, but  unfortunately I can't use them in any way. Please help me.

**Comment by cryptoBeliever** [comment]
@nikollai777 you can move coins from multiig only if you have access to cosigners.
It's not problem on github (since it's not bug in app). Please contact via https://forum.nem.io/.
