### ISSUE TITLE
NEM mobile wallet

### ISSUE THREAD

**Issue by kutja-blip** [NemProject/NanoWallet#657]
Hi, 

Apologies for newbie question.

I have a NEM desktop wallet on PC that I want to export to my NEM mobile wallet. 
I want to export the same wallet I use with Ledger NANO X that is synced with my NEM desktop wallet.
I am unable to copy the QR code in the 'export wallet QR (android)' as the cursor won't allow me to select it. 
The 'share account info QR' I can select but the mobile NEM wallet reports that it is not a valid account ?

If I log into NEM desktop without Ledger Nano, I can export QR code to my phone but I lose the security of using Ledger Nano.

Thank you in advance !

**Comment by cryptoBeliever** [comment]
Hello,

NEM mobile wallet don't support Ledger integration so you can't import the same wallet.
Your mnemonics are stored on Ledger and this makes your wallet safe. You can't export it.

If you have more questions please contact via https://forum.nem.io/. 

Thank you
