### ISSUE TITLE
Opt In has finished, please update your wallet to get the latest details

### ISSUE THREAD

**Issue by Teitelboim** [NemProject/NanoWallet#658]
To get XYM tokens I need mnemonic phrase but I can not get it from NEM Wallet. While trying to make 'Symbol Opt In' I recieved that message: 'Opt In has finished, please update your wallet to get the latest details'... and there is no any mnemonic phrase. Nem wallet is updated to the last version. Please recommend what to do. Thanks.

**Comment by cryptoBeliever** [comment]
Hello,

if you already opted-in then you received mnemonics during this process (paper wallet with mnemonics words).
To claim tokens you need to have it and use Symbol wallet:
https://docs.symbolplatform.com/guides/migration/post-optin-xym-retrieval.html

If you have more questions please contact via https://forum.nem.io/. 

Thank you
