### ISSUE TITLE
Withdraw fail of XEM

### ISSUE THREAD

**Issue by Dravian1986** [NemProject/NanoWallet#659]
Hi all,

new here, but I recently tried to transfer my XEM coins to another platform to be able to buy something there. Now my coins were removed from my account but never arrived at the other wallet. How do I fix this problem?

Kind regards,
Dravian

**Comment by cryptoBeliever** [comment]
Hello,
If you sent it to exchange, please make sure you included memo as states on the exchange deposit page.
If not, contact exchange support, give transaction hash (id), and ask to send coins back.
If you need help please contact via https://forum.nem.io/.

Thank you
