### ISSUE TITLE
XYM Pre-launch Opt-in users can't generate Paper Wallets using Symbol Opt In function

### ISSUE THREAD

**Issue by eorodionov** [NemProject/NanoWallet#668]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. If you need help https://forum.nem.io should be first place to visit.
- [ ] **DO** describe operating system and browser used

## Expected Behavior
Using NanoWallet, I want to go to Services > Symbol Opt In (click Claim XYM with the Symbol opt-In button) > Ready > Display my XYM Paper Wallet for a pre-launch opt-in.

## Current Behavior
Using NanoWallet, I go to Services > Symbol Opt In (click Claim XYM with the Symbol opt-In button) > Ready > I get a message saying "You didn't have enough XEM in Snapshot or you already claimed them in a pre-launch opt-in."

## Possible Solution
There needs to be a way to generate a XYM migration paper wallet for users who opted-in pre-launch BUT did not generate a XYM Paper Wallet yet.

## Steps to Reproduce

1. Login into NEM wallet using NanoWallet
2. Navigate to Services > Symbol Opt-In (click Claim XYM with the Symbol opt-In button) > Ready
3. Click **Ready**
4. **Select account to opt-in** page loads
5. **"You didn't have enough XEM in Snapshot or you already claimed them in a pre-launch opt-in."** message appears

## Details

I did not know I have to generate paper wallet, I simply opted in pre-launch and expected to be able to come back and access my XYM wallet info whenever I want AFTER launch. 

With the current system, there is no way to access XYM migration paper wallets for users like me. My XYM funds are now locked without any way to access them.

How do I know it's a bug:
1. Using [Opt-In Summary page](http://report.experimental.symboldev.network/ok1.html) I can see my NIS account in Migrated Balances list. This confirms I had enough XEM in Snapshot.
2. I never saw an option to create a paper wallet after opting in before March 15th, 2021.
3. I have other users reporting the same issue on [Reddit](https://www.reddit.com/r/nem/comments/rz59up/problem_accessing_symbol_paper_wallet_from/).

**Comment by cryptoBeliever** [comment]
Hello. There is no way to do that. Symbol account was generated randomly during opt-in and if you did not saved paper wallet nobody can generate it the second time. During the opt-in process you had to confirm (without there was no way to continue) the backup of your Symbol paper wallet / mnemonic phrase.
