### ISSUE TITLE
No market Data

### ISSUE THREAD

**Issue by logart89** [NemProject/NanoWallet#67]
Error "Can't fetch market Data" 

I have the last version of nanowallet 1.3.4 
Last version of java. 

No firewall or little snitch to block traffic. So i don't understand why i'm the only one here that i've seen with that error.

**Comment by logart89** [comment]
It appears that this error only appears to me with the internet in my home, in all my computers. Do i need to open ports or something?

**Comment by logart89** [comment]
I tried with the internet of my phone and not even with that i could fix it.

**Comment by logart89** [comment]
This is the reason of the problem https://forum.nem.io/t/no-market-data-in-nano-wallet/4949/3

Please take the XEM price ticker from other place, not from poloniex.

**Comment by cryptoBeliever** [comment]
I will create separate issue to fix that.
