### ISSUE TITLE
Suggestion: Import Account from Private Key Function

### ISSUE THREAD

**Issue by clusterfari** [NemProject/NanoWallet#70]
Currently there is the option to "add account" which generates another account and public key derived from the initial private key.

It would be awesome if you could additionally import an already existing account from public/private-keys here.

This would for instance allow me to manage my account from the mobile device in the same wallet as my pc account.

**Comment by QuantumMechanics** [comment]
Hi,

This feature was implemented before but removed because users could forgot they imported an account manually and only backup the primary private key. So imported accounts would be gone.

**Comment by clusterfari** [comment]
Thanks Quantum mechanics! This makes of course sense. 
Meanwhile I found out that you have already implemented a workaround to achieve what I was looking for.
I signed out, then signed up again chosing the option "private key wallet" where the public key is reconstructed when I enter a known private key - then I create and save the new wallet from this information and use it via "log in" again - works like a charm
