### ISSUE TITLE
Account Selection

### ISSUE THREAD

**Issue by adsactly** [NemProject/NanoWallet#71]
When selecting the various accounts some of the Account Balances show up nothing but I know the coins are there because I see them on the Explorer.

**Comment by QuantumMechanics** [comment]
Hi,

It is weird, is any transactions showing on dashboard when balance shows 0 ? 
Can you spend from those accounts (try making a transaction to yourself) ?

**Comment by adsactly** [comment]
It won't let me even see the balances using NanoWallet for all my individual Accounts. Only the Main Account can be viewed. and one other account both of which are near empty.

**Comment by QuantumMechanics** [comment]
Yes but that do not answer my above questions, I can't determine your problem with that. You should be able to see balances unless the request to chain for you account data fail or the secondary accounts for your primary are wrong which is a pretty serious issue. 

The second case would be if you log into an account that is supposed to have more than 0 XEM but shows a balance of 0 and that you cannot spent from it

**Comment by adsactly** [comment]
OK well using the old system I have been able to see my balances. Not sure why It doesn't work with the NanoWallet thou.
