### ISSUE TITLE
Conversion USB/XEM and EUR/XEM doesn't work

### ISSUE THREAD

**Issue by roymaccedd** [NemProject/NanoWallet#72]
Using Nano Wallet 1.3.4

Steps to reproduce the issue:
1. Go to Services
2. Go to Changelly Instant Exchange/BUy Xem
3. Select any amount and USD or EUR 

The resoult amount of Xem are always 0

![eur-xem](https://cloud.githubusercontent.com/assets/28217586/25562963/47458f7c-2d92-11e7-97f0-f04d13870fe0.jpg)
![usd-xem](https://cloud.githubusercontent.com/assets/28217586/25562964/477d0cc2-2d92-11e7-890f-bd7acdccef10.jpg)

My addr is: NCLUDO-MJLJQF-S4VE7E-C2CGZW-N2CS3G-OSE3RS-5C5U

**Comment by QuantumMechanics** [comment]
Hi, it is working perfectly from here. 
Changelly widget is an external service so it can have downtimes.
Can you try again ?

**Comment by roymaccedd** [comment]
You are right.
It works now
thank you
