### ISSUE TITLE
wallet SOS

### ISSUE THREAD

**Issue by shake4you** [NemProject/NanoWallet#73]
opened my wallet this morning - nothing inside - NEM gone - no more data from the past - no more wallet adress and other things missing - is there a known network problem or got the blockchain hacked overnight? Could be a problem of firefox too ?!?

**Comment by bengross1979** [comment]
I have the same problem, Everyhitng gone in my wallet

**Comment by mizunashi** [comment]
How is Node going?
If a red circle is displayed, switch to another node. Green is OK.
At the moment, alice 6 is in a state that it can not be used.
![2017-05-01 18 24 16](https://cloud.githubusercontent.com/assets/1645189/25576711/d94e78de-2e9b-11e7-94e5-d8b974ccfdaa.png)

**Comment by bengross1979** [comment]
Wow thanks - i t works!

**Comment by bengross1979** [comment]
All solved!


I got a small hearth attack this morning - still very new to this [😊]

Thank you for the quick reply!




________________________________

**Comment by shake4you** [comment]
solved - took another node - thx
