### ISSUE TITLE
XEM funds not sent from wallet

### ISSUE THREAD

**Issue by Rolmanina** [NemProject/NanoWallet#74]
I created a Nano wallet.  Sent 385 XEM from Bittrex to wallet OK.  Then sent 351 XEM back to Bittrex and this did not work!  Have I now lost this?

**Comment by QuantumMechanics** [comment]
Hi, 
What is happening when you try to send ? Do you have an alert error ?
is your balance showing 385 XEM ?

**Comment by Rolmanina** [comment]
Hello

Thanks for your quick reply.
I don’t see any alerts.
My balance shows as 34 XEM.

I copied and pasted the dashboard as shown below if that helps.

nanoWallet<http://mijin.io/nanowallet/start.html?referrer=https%3A%2F%2Fwww.google.ca%2F#!/>
·          Dashboard<http://mijin.io/nanowallet/start.html?referrer=https%3A%2F%2Fwww.google.ca%2F#!/dashboard>
·          Send<http://mijin.io/nanowallet/start.html?referrer=https%3A%2F%2Fwww.google.ca%2F#!/transfer-transactions>
·          Services<http://mijin.io/nanowallet/start.html?referrer=https%3A%2F%2Fwww.google.ca%2F#!/services>
·          Explorer<http://mijin.io/nanowallet/start.html?referrer=https%3A%2F%2Fwww.google.ca%2F#!/explorer/home>
·         34.000000 XEM
·
Account

Amount

Message

Date


 ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR

351.000000 XEM

Mon, 01 May 2017 02:05:04 GMT

 ND2JRP-QIWXHK-AA26IN-VGA7SR-EEUMX5-QAI6VU-7HNR

385.000000 XEM

Sun, 30 Apr 2017 18:19:00 GMT


Harvesting income on latest 25 blocks

Nothing to show


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by QuantumMechanics** [comment]
So you sent 385 XEM from Bittrex to Nano, then sent 351 XEM from Nano to Bittrex right ?
Did you join a message with your transaction to Bittrex ? Seems not from what I see on your pasted dashboard.

**Comment by Rolmanina** [comment]
I didn’t join a message as far as I know.  Should I have?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mizunashi** [comment]
When transferring money from Wallet to Bittrex, you had to remit not only the remittance destination address but also the message shown in the image below.

![2017-05-02 3 41 03](https://cloud.githubusercontent.com/assets/1645189/25590059/e5485788-2ee9-11e7-948f-c24d49f7293f.png)

If you contact Bittrex's support, remittance should be reflected.

**Comment by Rolmanina** [comment]
Wow.
Okay thanks for your help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
