### ISSUE TITLE
Missing Funds

### ISSUE THREAD

**Issue by toricc** [NemProject/NanoWallet#78]
Checked into my account today and all my NEM is gone, what gives.  Hope it's a glitch on your end, please advise

**Comment by skani007** [comment]
I just opened a topic with exactly the same problem but i solved it. In my case it wasn't connected to a node. In you're nano wallet look if the node in the right uppercorner is red. In that case it's not connected it should be green. Click on in an select any node that works.

**Comment by toricc** [comment]
Great info, thanks for the help. That was the problem.
