### ISSUE TITLE
Funds didn't came in while Node disconnection. Transaction still pending over 12hs on Blockchain wallet

### ISSUE THREAD

**Issue by sicalorod** [NemProject/NanoWallet#79]
How long it will take for the funds to come in after reconnecting nods?

**Comment by sicalorod** [comment]
I meant to say Node disconnection...

**Comment by QuantumMechanics** [comment]
Hi, 

You just need to connect to another node and it should be good.  What do you mean by pending ? It is in unconfirmed ?

**Comment by sicalorod** [comment]
Yes, I already connected to a node and still been processing for hours....

**Comment by sicalorod** [comment]
It was sent today 2am and the node was reconected 5 hours ago.. It still pending...

**Comment by QuantumMechanics** [comment]
Can you show me the account address ? So I can look on the chain

**Comment by sicalorod** [comment]
It seems between yesterday and today it manage to go through, but it tool a while.

**Comment by sicalorod** [comment]
Thks
