### ISSUE TITLE
Multilingualization of remoteStatus

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NanoWallet#81]
As new, GENERAL_ACTIVE and GENERAL_INACTIVE were created in the language file as harvestingStatus.

I would like you to expand this term and apply it to remoteStatus as well.

It will be GENERAL_ATCIVETING and GENERAL_INACTIVATING to be added in the language file,
Since I can not judge whether it is better to separate harvest and Remote Status, I will leave it to the development side.

This suggests that translating only GENERAL_ACTIVE and GENERAL_INACTIVE will make it look bad.
"start.html#!/importance-transfer 's top of right side"
![2017-05-06 4 54 38](https://cloud.githubusercontent.com/assets/1645189/25762475/cfb206ca-3219-11e7-8ed9-da2adabde86e.png)

**Comment by QuantumMechanics** [comment]
Hi,

> I would like you to expand this term and apply it to remoteStatus as well.

No problem, I will.

You can translate GENERAL_ACTIVE and GENERAL_INACTIVE, it'll be used for remote status too.

**Comment by mizunashi** [comment]
Thanks QM♡
When Harvesting was in Japanese, the status of the next Remote was English, it was just bad look, so I requested it.

Of those, I think that I want to rewrite the translation part by myself and add it to all languages and pull it.
However, I can not do what to do with variable names lol lol

Posted at the last place of 
https://github.com/NemProject/NanoWallet/commit/70f2c769fd237cef1ba871ab2603afacd274d7b7

**Comment by mizunashi** [comment]
Hi, QM
When Harvesting was in Japanese, the status of the next Remote was English, it was just bad look, so I requested it.

Of those, I think that I want to rewrite the translation part by myself and add it to all languages and pull it.
However, I can not do what to do with variable names lol
----
As a separate case, did you read it here?

**Comment by mizunashi** [comment]
I made a mistake "Close". I do not know how to cancel this.
｡ﾟ( ﾟஇωஇﾟ)ﾟ｡

**Comment by mizunashi** [comment]
reopnen issue.
sorry.

**Comment by QuantumMechanics** [comment]
Done :) https://github.com/NemProject/NanoWallet/commit/011a62959ca7087fc2bce6b80041180df0703204
