### ISSUE TITLE
Suggestion: Market Information in Multiple Currency

### ISSUE THREAD

**Issue by Chaos514** [NemProject/NanoWallet#84]
I don't know if the source you use for the market information provides it, but it would be interesting to allow to display the total value of the wallet in other currency than USD. 

The wallet is amazing. Keep up the good work.

**Comment by QuantumMechanics** [comment]
Hi,

Sure I'll look into it for future versions.

> The wallet is amazing. Keep up the good work.

Thanks :)

**Comment by QuantumMechanics** [comment]
Added in 2.0
