### ISSUE TITLE
Don't suggest user to copy private key to text file

### ISSUE THREAD

**Issue by songproducer** [NemProject/NanoWallet#88]
A minor detail I noticed in the warning box when setting up a new wallet. Should read instead something like 'an encrypted file, or written down on paper'.

**Comment by QuantumMechanics** [comment]
Hi,

It is okay if it is stored offline as recommended

**Comment by songproducer** [comment]
I realise that, but the way it was written didn't make clear that the text file needs to be offline.

**Comment by QuantumMechanics** [comment]
> To backup a private key, save it in a text file, print it or write it somewhere safe.
> It is recommend to store the private key offline.

This ?

**Comment by songproducer** [comment]
Yes - the confusion comes from the word 'or' which has an 'exclusive' sense. Adding the words 'on a permanently offline computer' immediately after 'text file' would remove doubt.
