### ISSUE TITLE
Wallet broken

### ISSUE THREAD

**Issue by AceHole98** [NemProject/NanoWallet#89]
Hello,
I watched some tutorial/guides and made my wallet. However, it does not have any of the functions shown/mentioned (like send, receive, account and so on). All It shows is this:
![sdsd](https://cloud.githubusercontent.com/assets/28578135/25873716/37273842-3518-11e7-9286-5c435eac777e.PNG)

**Comment by QuantumMechanics** [comment]
Hi, 

Red circle next to `Node` means it is not connected. Please click on it and select another node.

The app needs to fetch some data from the chain in order to works properly, this is why you don't see any links (page would have lots of errors).

**Comment by mfports7** [comment]
WOW!!!!!!!!! Your amazing! Thank you!!!!!!!
