### ISSUE TITLE
Where is the menue bar?

### ISSUE THREAD

**Issue by Wulfilar** [NemProject/NanoWallet#92]
Hello community!
I just downloaded NanoWallet software on my iMac under Mac OS 10.12.
First of all, start.html remains empty when opened with Safari. The whole story does not run under Safari 10.1.
Under Firefox(48.0.2) , creation of wallet results in existence of file <NameOfWallet>.wlt.
Fair enough.
BUT:
When accessing it aas written under "3 Log in and backup", further steps as listed under:
https://forum.nem.io/t/nanowallet-guide/3568
are impossible to complete.
Reason:
The menue bar depicted in picture Wj2Irv.png does not exist!
Left, "nanoWallet" exists.
But beginning with "Dashboad" and ending at "0.000000 XEM", then again beginning after "Node" the item "Account" none of the mentioned items of the menue appear on screen.
 
Thus, the procedure:
"Open "Account" by clicking on it in the top right corner of the NanoWallet. Account Information shows, for example, your NEM address for receiving funds and also your vested balance for harvesting."
 cannot be performed, and buildup of wallet ends here!

Any explanation?
Software is truly updated.
Best regards,
Wulfilar

**Comment by QuantumMechanics** [comment]
Hi, please read https://github.com/NemProject/NanoWallet/issues/89
