### ISSUE TITLE
Delegated account not harvesting

### ISSUE THREAD

**Issue by songproducer** [NemProject/NanoWallet#93]
I waited longer than 6 hours, Remote status is 'ACTIVE'.

I am shown:

> You need 10'000 vested XEM to start delegated harvesting

I have 10 272.814433 XEM.

Vested balance shows:
1 027,281444 XEM

**Comment by QuantumMechanics** [comment]
Hi,

> Vested balance shows:
**1 027**,281444 XEM

You have 1027 XEM vested and 10'000 are required

**Comment by songproducer** [comment]
This is really confusing. The white paper states:

> To be eligible for entering the importance calculation, an account must have at least
> 10,000 vested XEM. All accounts owning more than 10,000 vested XEM have a non-zero
> importance score.

I have more than 10,000 XEM but why is this not enough by a factor of 10?

**Comment by jabo38** [comment]
Hi @songproducer this will calculate your Vested XEM. http://samesake.com/xem/harvesting-calculator/ Once it is over 10,000, you will be good.
