### ISSUE TITLE
Create sell XEM link

### ISSUE THREAD

**Issue by elucian** [NemProject/NanoWallet#94]
This is a feature request to create this link on the Services page. It is only fair and honest to have this option so that one can make a profit by sealing XEM. I know the point is to use XEM for transactions but if we have a Buy XEM link it looks bad if we do not have also a Sell XEM link option.

**Comment by jabo38** [comment]
Yes, we are planning on adding that feature in the future.  We just were starting out slowly.

**Comment by waterproof151** [comment]
2nd this request. Thanks!

**Comment by elucian** [comment]
I have decided not to use XEM. I do not need this feature.
