### ISSUE TITLE
Encrypted transaction sent to Bittrex

### ISSUE THREAD

**Issue by ilyasydney** [NemProject/NanoWallet#95]
Hi,

Just sent an encrypted transaction from NanoWallet to Bittrex only to learn that they don't accept NEM encrypted. It's only been 30 mins and it's probably too early to panic. Yet I'd like to be prepared for any contingencies. 

Please advise if I could reverse the transaction or propose for alternative action here?

**Comment by QuantumMechanics** [comment]
Hi,

No reversal possible, NEM blockchain is immutable.

You must contact the exchange and explain the situation.

**Comment by ilyasydney** [comment]
Ok, will do. Thank you for the advise.
