### ISSUE TITLE
Nano Wallet not Harvesting!

### ISSUE THREAD

**Issue by BitPayUser** [NemProject/NanoWallet#97]
I have over 150k NEM in my nano wallet. I followed the instructions and activated my account. My remote status is ACTIVE since few days. Then i selected a node for delegated harvesting. My vested balance shows 35k NEM. But i am not getting any rewards from harvesting. It shows 0 harvested blocks. I stopped harvesting and selected a different node, but haven't harvested any blocks yet. Is this usual? How long does it take to see harvesting?

**Comment by jabo38** [comment]
once you have your full balance vested you can get more blocks.  I know somebody with 25k vested recently said he can get about 1 block a week.
