### ISSUE TITLE
o Node button covering up "Account:"

### ISSUE THREAD

**Issue by jbrelin** [NemProject/NanoWallet#99]
When following the NanoWallet Guide (https://blog.nem.io/nanowallet-tutorial/) I cannot run the tutorial completely because the "o Node" button is covering up accounts. What I see is "o Node : Primary", and not "o Node" "Accounts:Primary". The NanoWallet guide directs the reader to click on accounts as if it is available, but it is not. Please make it clear in the NanoWallet Guide why this may be happening. Possibly it is because I have not set up an account. If so, please explain what needs to be done before following the guide.

**Comment by jbrelin** [comment]
I suspect this may be occurring because I am behind a company firewall that is blocking access. Is there a port that I need to ensure is open to allow the above to work?

**Comment by QuantumMechanics** [comment]
Hi, 

Node button is not covering up the account button, you are probably not connected to the Node

See: https://github.com/NemProject/NanoWallet/issues/89

**Comment by jbrelin** [comment]
Thank you for that, but this did not solve my problem. All the nodes I tried connecting to on this computer (which proves I am connected to the internet, otherwise I would not be able to write this), did not work. I believe this is a closed-port issue on my end because I am working at a large company which has extensive firewall restrictions. I assume the right port to open up is 7890?

Thank you.

**Comment by jbrelin** [comment]
Here may be some more useful information:

When running the runNcc.bat batch file, I get this error:

2017-05-17 16:48:30.985 INFO NEM Deploy is ready to serve. URL is "http://172.26
.96.53:8989/". (org.nem.deploy.CommonStarter startServer)
2017-05-17 16:48:40.770 WARNING Time synchronization not possible, NIS not avail
able. (org.nem.ncc.time.synchronization.NccTimeSynchronizer synchronizeTime)

From this, it appears the port I should open is 8989, is this correct? BTW, I am no network expert, but I tried pinging http://172.26.96.53:8989/ and it said it could not find the address.

**Comment by jbrelin** [comment]
Well, I seemed to have fixed it by disabling my wireless connection. It appears I have been connecting to a super-secure wireless host.

**Comment by jbrelin** [comment]
Well, not so fast. It appears IT is shutting down ports on me or something because the wired connection now is not connecting to any node like it did yesterday. The only way I can now connect is via my personal hot spot on my phone!

**Comment by QuantumMechanics** [comment]
Closing because issue related to your network
